In [188]:
import pandas as pd
from Levenshtein import distance
import numpy as np
import re
import unicodedata

In [189]:
#read the Compensation Office csv file into a dataframe
df_csv = pd.read_excel('/home/Benha/Projects/Arbeit/FIZ/compensation-office-analysis/data_new/2025_06_03_Liste der Entschädigungsämter mit Adressen, Varianten, Normalisierungen und Archiven.xlsx')
df_csv.sample(20)

,Layout class,Filename,Bundesland,Transkription Compensation Office,Normalisierung Compensation Office1,Normalisierung Compensation Office2,Zuständiges Archiv,Zuständiges Archiv - GND-Nummer,Unnamed: 8
59,BY-Spätphase (abweichend 1),1922_02_18_25_0,Bayern,Bayerisches \nLandesentschädigungsamt\nPrinz-L...,Bayerisches Landesentschädigungsamt München,NaN,Bayerisches Hauptstaatsarchiv,2005486-5,NaN
390,RLP-Frühe-Phase,1903_01_16_53_0,Rheinland-Pfalz,Regierungsbezirksamt\nfür Wiedergutmachung\nun...,Regierungsbezirksamt für Wiedergutmachung und ...,NaN,Landesarchivverwaltung Rheinland-Pfalz,2029741-5,NaN
382,RLP-Frühe-Phase,1903_01_18_77_0,Rheinland-Pfalz,Regierungsbezirksamt\nfür Wiedergutmachung\nun...,Regierungsbezirksamt für Wiedergutmachung und ...,NaN,Landesarchivverwaltung Rheinland-Pfalz,2029741-5,NaN
133,Hinweiskarte_schwarzes_Datum,1903_03_20_53_0,Schleswig-Holstein,Kiel,Kiel,NaN,Landesarchiv Schleswig-Holstein,2017048-8,NaN
106,HH-NI-NRW-SH-Hauptphase,1897_05_15_19_0,Nordrhein-Westfalen,b) Der Oberkreisdirektor -Amt für Wiedergutmac...,"Der Oberkreisdirektor, Amt für Wiedergutmachun...",NaN,Landesarchiv Nordrhein-Westfalen,10094504-1,NaN
257,offizielle Bezeichnungen und Adressen,NaN,Nordrhein-Westfalen,Der Regierungspräsident in Arnsberg,NaN,NaN,Landesarchiv Nordrhein-Westfalen,10094504-1,NaN
80,HH-NI-NRW-SH-Hauptphase,1880_03_30_6_0,Schleswig-Holstein,Landesentschädigungsamt\nSchleswig-Holstein in...,Landesentschädigungsamt Schleswig-Holstein in ...,NaN,Landesarchiv Schleswig-Holstein,2017048-8,NaN
48,BY-HB-Frühe Phase,1850_03_13_1_0,Baden-Württemberg,Karlsruhe,Karlsruhe,NaN,Landesarchiv Baden-Württemberg,10107080-9,NaN
112,HH-NI-NRW-SH-Hauptphase,1873_02_09_4_0,Hamburg,"Hansestadt Hamburg, Sozialbehörde, Amt für Wie...","Sozialbehörde, Amt für Wiedergutmachung Hamburg",NaN,Staatsarchiv (Hamburg),2022556-8,NaN
243,offizielle Bezeichnungen und Adressen,NaN,Rheinland-Pfalz,Wiedergutmachungsamt Rheinland-Pfalz Berlin\nB...,NaN,NaN,Amt für Wiedergutmachung Saarburg,1354917804,NaN
5,ABC-Karten,1930_12_13_33_0,Niedersachsen,Helmstedt,Helmstedt,NaN,Niedersächsisches Landesarchiv,6510041-4,NaN
87,HH-NI-NRW-SH-Hauptphase,1856_03_13_1_0,Nordrhein-Westfalen,Der Oberkreisdirektor - Amt für Wiedergutmachu...,"Der Oberkreisdirektor, Amt für Wiedergutmachun...",NaN,Landesarchiv Nordrhein-Westfalen,10094504-1,NaN
237,offizielle Bezeichnungen und Adressen,NaN,Rheinland-Pfalz,Regierungsbezirksamt für Wiedergutmachung und ...,NaN,NaN,Amt für Wiedergutmachung Saarburg,1354917804,NaN
367,offizielle Bezeichnungen und Adressen,NaN,Baden-Württemberg,Landesbezirksstelle für die Wiedergutmachung K...,NaN,NaN,Landesarchiv Baden-Württemberg,10107080-9,NaN
424,Tabellen-Typ (abweichend),1904_01_11_30_0,Bund,"Oberfinanzdirektion: Köln, Riehler Pl. 2, 5000...",Oberfinanzdirektion Köln,NaN,Bundesarchiv (Koblenz),39454-3,bis 1993 (4stellige PLZ)
98,HH-NI-NRW-SH-Hauptphase,1880_02_13_22_0,Nordrhein-Westfalen,Köln,Köln,NaN,Landesarchiv Nordrhein-Westfalen,10094504-1,NaN
175,offizielle Bezeichnungen und Adressen,NaN,Schleswig-Holstein,"Ministerium für Soziales, Gesundheit, und Verb...",NaN,NaN,Landesarchiv Schleswig-Holstein,2017048-8,NaN
312,offizielle Bezeichnungen und Adressen,NaN,Hamburg,Arbeits- und Sozialbehörde - Amt für Wiedergut...,NaN,NaN,Staatsarchiv (Hamburg),2022556-8,NaN
366,offizielle Bezeichnungen und Adressen,NaN,Baden-Württemberg,Landesamt für Wiedergutmachung\nKarlsruhe,NaN,NaN,Landesarchiv Baden-Württemberg,10107080-9,NaN
264,offizielle Bezeichnungen und Adressen,NaN,Nordrhein-Westfalen,Regierungspräsident Arnsberg,NaN,NaN,Landesarchiv Nordrhein-Westfalen,10094504-1,NaN

In [190]:
#creaae a list of unique compensation offices from the csv file
gt = df_csv['Transkription Compensation Office '].unique().tolist()
print("Number of unique compensation offices: ", len(gt))

Number of unique compensation offices:  428

In [191]:
#read the sliced extracted data jsonl file into a dataframe
df_json = pd.read_json('compoff_extracted.jsonl', lines=True)
df_json.sample(20)

,CompensationOffice1,BZKNr,filename
348454,Köln,671 648,1934_01_07_15_0.jpg
109026,Hessen,D/7250/03/A/Rot,1903_07_14_84_0.jpg
164938,Niedersachsen,120986,1922_04_12_81_0.jpg
929114,Köln,710759,1936_04_25_6_0.jpg
1050986,NaN,66.481/III/7151,1940_04_30_9_0.jpg
1036680,Braunschweig,8-02385,1895_05_10_5_0.jpg
546249,Entschädigungsbehörde Köln,Art. V-56-II-Nr. 18 536,1915_04_08_37_0.jpg
279830,Hessen,I 6 W / 35399,1921_10_27_45_0.jpg
1115863,Bezirksamt für Wiedergutmachung KOBLENZ,120488,1899_12_27_16_0.jpg
650864,Freie und Hansestadt Hamburg Sozialbehörde Amt...,220405,1905_04_22_51_0.jpg
985897,Niedersachsen,1 28235 b,1890_03_18_11_0.jpg
565185,Landesamt für die Wiedergutmachung,EK 1735,1928_06_27_12_0.jpg
24176,Härtefonds Hessen,HF 719,1939_03_24_25_0.jpg
1596193,Niedersachsen,12262,1910_01_22_75_0.jpg
742505,Entschädigungsamt Berlin,55 775,1878_07_09_6_0.jpg
1178258,Entschädigungsamt Berlin,330 738,1914_01_06_52_0.jpg
423295,Bezirksamt für Wiedergutmachung KOBLENZ,441651,1912_06_03_102_0.jpg
460670,Entschädigungsbehörde Köln,57 031,1941_05_05_2_0.jpg
1022309,Landesamt für die Wiedergutmachung Freiburg,7326,1895_02_22_11_0.jpg
1818810,Bezirksamt für Wiedergutmachung Koblenz,400816,1942_03_23_Neu_8_0.jpg

In [192]:
#create a dataframe with the entries that have a non-null value in the CompensationOffice1 column
print("Number of cards: ",len(df_json))
mask_not_null = df_json['CompensationOffice1'].notna()
print(f'Number of non-null entries: {mask_not_null.sum()}')

Number of cards:  1901284
Number of non-null entries: 1825946

In [193]:
#create a function to normalise the compensation office names by removing punctuation and whitespace, converting to lowercase and replacing umlauts with their equivalent

#def normalise(word):
#    return re.sub(r'\s+', ' ', str(word)).strip().lower()
def normalize(s):
    if not isinstance(s, str):
        return ""
    
    s = s.lower()

    # Normalize umlauts and ß
    replacements = {
        "ä": "ae", "ö": "oe", "ü": "ue", "ß": "ss"
    }
    for k, v in replacements.items():
        s = s.replace(k, v)
    
    # Normalize unicode (just in case)
    s = unicodedata.normalize("NFKD", s)
    
    # Remove punctuation and whitespace
    s = re.sub(r'[\W_]+', '', s)
        
    return s

gt_normalized = [normalize(office) for office in gt]

In [194]:
#create a mask for the entries in the json dataframe that match any of the normalized compensation office names in the gt list
mask_matched_0 = df_json['CompensationOffice1'].apply(normalize).isin(gt_normalized)
print(f'Number of matches: {mask_matched_0.sum()}')

df_unmatched = df_json[mask_not_null & ~mask_matched_0]
print(f'Number of unmatched entries: {len(df_unmatched)}')

Number of matches: 1494694
Number of unmatched entries: 331252

In [195]:
#print the unique values in the CompensationOffice1 column of the unmatched dataframe and their counts
print(len(df_unmatched['CompensationOffice1'].unique().tolist()))
df_unmatched['CompensationOffice1'].value_counts()

27629

CompensationOffice1
Bezirksamt für Wiedergutmachung Köln                                   32785
Hess. Staatsministerium                                                29978
Freie und Hansestadt Hamburg Sozialbehörde Amt für Wiedergutmachung    16429
Landesamt für die Wiedergutmachung                                     14641
Hansestadt Hamburg, Sozialbehörde, Amt für Wiedergutmachung            11836
                                                                       ...
Regierung Aachen (Welt.)                                                   1
Regierungspräsident Arasberg                                               1
Kreisssonderhilfsausschuss des Landkreises Garsch. Schlaumburg             1
Bayerisches Landesamt für den Regierungsbezirk München                     1
Reg.-Präsident /Präsident des Vereinsbezirks Hannover                      1
Name: count, Length: 27629, dtype: int64

In [196]:
#create a list of manually corrected compensation office names that are not in the gt list but are in the json dataframe and normalise them
list_corrections = ["Bezirksamt für Wiedergutmachung Köln", "Hess. Staatsministerium", "Freie und Hansestadt Hamburg Sozialbehörde Amt für Wiedergutmachung", "Hansestadt Hamburg, Sozialbehörde, Amt für Wiedergutmachung", 
                    "Der Innenminister des Landes Nordrhein-Westfalen", "Landesamt für die Wiedergutmachung Baden-Württemberg", "Oberfinanzdirektion Niedersachsen", "Statistisches Landesamt Nordrhein-Westfalen" , "Oberfinanzdirektion Niedersachsen"
                    , "Rhein. Pfalz - Berlin", "Regierungsbezirksamt für Wiedergutmachung und verwaltete Vermögen Köln", "Aachen", "Landesbeirat für die Wiedergutmachung, Stuttgart", "Freiburg i.Br.", "Hamburg, Sozialbehörde, Amt für Wiedergutmachung",
                    "Freie und Hansestadt Hamburg", "Regierungsbezirk Mainz", "Hessisches Ministerium für Jugend, Familie und Gesundheit" , "Reg.-Präsident / Präsident des Verw.-Bezirks Hannover", "Amt für Wiedergutmachung des Landes Rheinland/Pfalz in Berlin Hauptabteilung II",
                    "Schleswig-Holstein in Kiel", "Kreissozialamt Hannover", "Reg.-Präsident Hannover", "Amt für Wiedergutmachung Rheinland-Pfalz" , "Saarburg Bezirksamt für Wiedergutmachung", "Freie und Hansestadt Hamburg, Arbeits- und Sozialbehörde, Amt für Wiedergutmachung",
                    "Niedersachsen-Präsident / Präsident des Verwaltungsbezirks Hannover", "Regierungsbezirksamt für Wiedergutmachung und verwaltete Vermögen Neustadt a. d. Weinstraße", "KSHA Hannover", "Regierungsbezirk für Wiedergutmachung und verwaltete Vermögen Trier",
                    "Oberfinanzdirektion Magdeburg", "Regierungsbezirkskammer für Wiedergutmachung und verwaltete Vermögen Mainz","Regierungsamt Arnsberg (Westf.)", "Regierungsbezirkskammer für Wiedergutmachung und verwaltete Vermögen Mainz",
                    "Regierungsbezirksamt für Wiedergutmachung und verwaltete Vermögen München", "Landesamt für die Wiedergutmachung Baden-Württemberg Stuttgart"]

list_corrections_normalized = [normalize(office) for office in list_corrections]
gt_completed = gt_normalized + list_corrections_normalized
df_json['CompensationOffice1'] = df_json['CompensationOffice1'].str.replace("Bayrische", "Bayerische")
mask_matched_1 = df_json['CompensationOffice1'].apply(normalize).isin(gt_completed)
print(f'Number of matches: {mask_matched_1.sum()}')
df_unmatched = df_json[mask_not_null & ~mask_matched_1]
print(f'Number of unmatched entries: {len(df_unmatched)}')
print(f"Unique unmatched entries: {len(df_unmatched['CompensationOffice1'].unique().tolist())}")
percentage = len(df_unmatched) / len(mask_not_null) * 100
print(f"Percentage of unmatched entries: {percentage:.2f}%")

Number of matches: 1628175
Number of unmatched entries: 197771
Unique unmatched entries: 27325
Percentage of unmatched entries: 10.40%

In [197]:
df_unmatched['CompensationOffice1'].value_counts().head(30)

CompensationOffice1
Landesamt für die Wiedergutmachung                                       14641
Bayerische Kartei                                                         9925
Regierungsbezirksamt für Wiedergutmachung und verwaltete Vermögen         7261
Bundeskartei                                                              4884
Bezirksamt für Wiedergutmachung                                           4130
HNG                                                                       3402
Regierungsbezirksamt für Wiedergutmachung und kontrollierte Vermögen      3354
Bayerisches Landesarchiv                                                  2585
Regierungsbezirks-Amt für Wiedergutmachung und kontrollierte Vermögen     2557
Bezirksamt für Wiedergutmachung 65 Mainz                                  1304
Bayerisches Landesamt für Verfolgtenfragen                                1291
Kreissonderhilfsausschuss                                                 1101
Barburg                                                                    987
Kreissozialamt                                                             958
Baarburg                                                                   950
Bundesminister der Finanzen                                                904
Entschädigungsbehörde                                                      863
Hamburg 1                                                                  840
Bundesamt                                                                  834
König                                                                      825
Bayerisches Landesamt für Vertriebene                                      815
Reg.-Präsident / Präsident des Verw.-Bezirks                               752
KSHA                                                                       750
Der Herr Regierungspräsident in Detmold                                    745
Kreissozialhilfsausschuss                                                  712
Landesentschädigungsamt                                                    602
Landesamt für Wiedergutmachung                                             586
Bundesamt für Vertriebene                                                  560
Landesamt für Vertriebene                                                  541
Kön                                                                        526
Name: count, dtype: int64

# Matching based on Levenshtein Distance

In [198]:
#  return the minimum distance and the best match up to a threshold of half the length of the cleaned name
def get_min_distance_dynamic_normalized(name):
    name_clean = normalize(name)
    threshold = len(name_clean) // 2
    
    min_dist = float('inf')
    best_match = None
    for office in gt_completed:
        office_clean = normalize(office)
        d = distance(name_clean, office_clean)
        if d == 0:
            return 0, office
        if d < min_dist:
            min_dist = d
            best_match = office
    if min_dist <= threshold:
        return min_dist, best_match
    return np.nan, None

results = df_unmatched['CompensationOffice1'].apply(get_min_distance_dynamic_normalized)

lev_matches = pd.DataFrame({
    'CompensationOffice1': df_unmatched['CompensationOffice1'],
    'MatchedOffice': results.apply(lambda x: x[1]),
    'MatchDistance': results.apply(lambda x: x[0])
})

In [199]:
#print the matches with a distance of 1 and 2
df_matches_2 = lev_matches[lev_matches['MatchDistance'].isin([1, 2])]
df_matches_2.sample(25)

,CompensationOffice1,MatchedOffice,MatchDistance
61649,Landesentschädigungsamt,blandesentschaedigungsamt,1.0
847978,Bezirksamt für Wiedergutmachung 65 Mainz,bezirksamtfuerwiedergutmachungmainz,2.0
1284021,Bezirksamt für Wiedergutmachung NEUSTADT c. d....,bezirksamtfuerwiedergutmachungneustadtadweinstr,1.0
1390786,Landesamt für die Wiedergutmachung Stuttgart-S.,landesamtfuerdiewiedergutmachungstuttgart,1.0
1639743,Regierungsbezirksamt für Wiedergutmachung und ...,regierungsbezirksamtfuerwiedergutmachungundver...,1.0
1684729,Regierungsamt Arnberg (Westf.),regierungsamtarnsbergwestf,1.0
1345837,Bezirksamt für Wiedergutmachung 55 TRIER,bezirksamtfuerwiedergutmachungtrier,2.0
1617700,Kön,koeln,1.0
1226362,Bezirksamt für Wiedergutmachung Koblinz,bezirksamtfuerwiedergutmachungkoblenz,1.0
363102,Sarbrüken,saarbruecken,2.0
1762356,Der Innennminister des Landes Nordrhein-Westfa...,derinnenministerdeslandesnordrheinwestfalenabt...,1.0
173306,Köl,koeln,1.0
984903,Bezirksamt für Wiedergutmachung 65 Mainz,bezirksamtfuerwiedergutmachungmainz,2.0
529000,Bezirksamt für Wiedergutmachung Kobl. lenz,bezirksamtfuerwiedergutmachungkoblenz,1.0
1332533,Regierungsbezirksamt für Wiedergutmachung und ...,regierungsbezirksamtfuerwiedergutmachungundver...,1.0
1023152,Kön,koeln,1.0
389301,Hamburg 1,hamburg,1.0
148450,Bezirksamt für Wiedergutmachung 65 Mainz,bezirksamtfuerwiedergutmachungmainz,2.0
729593,NS-Härtedefonds - Hessen,nshaertefondshessen,2.0
894490,Freie und Hansestadt Hamburg Sozialbehörde Amt...,freieundhansestadthamburgsozialbehoerdeamtfuer...,1.0
124019,Nundesministerium der Finanzen,bundesministeriumderfinanzen,1.0
235809,Freie und Hansestadt Hamburg Sozialbehörde Ant...,freieundhansestadthamburgsozialbehoerdeamtfuer...,1.0
1530828,Der Inneminsister des Landes Nordrhein-Westfalen,derinnenministerdeslandesnordrheinwestfalen,2.0
1599124,"Freie und Hansestadt Hamburg, Sozialbehörde, A...",freieundhansestadthamburgsozialbehoerdeamtfuer...,1.0
786137,Landesentschädigungsam Saarbrücken,landesentschaedigungsamtsaarbruecken,1.0

In [200]:
#print the counts of the match distances of 1 and 2
df_matches_2['MatchDistance'].value_counts()
print(f"Number of matches with distance 1 or 2: {len(df_matches_2)}")
print(f"Number of unmatched entries after adding the close matches: {len(df_unmatched) - len(df_matches_2)}")

Number of matches with distance 1 or 2: 27826
Number of unmatched entries after adding the close matches: 169945

In [201]:
#remove the matches with distance 1 and 2 from the unmatched dataframe
df_unmatched_filtered = df_unmatched[~df_unmatched['CompensationOffice1'].isin(lev_matches[lev_matches['MatchDistance'].isin([1, 2])]['CompensationOffice1'])]
df_unmatched_filtered['CompensationOffice1'].value_counts().iloc[30:40]

CompensationOffice1
Amt für Wiedergutmachung des Landes Rheinland-Pfalz                470
Regierung Arnsberg (Wf.)                                           459
Doppelmeldung                                                      449
Amt für Wiedergutmachung Stadt Bonn                                447
Bundesamt für Wiedergutmachung                                     439
Niedersachsen-Präsident / Präsident des Verwaltungsgerichtshofs    437
Regierung Köln                                                     421
Bundesarchiv                                                       408
Reg.-Präsidium Hildesheim                                          396
Entscheidungsbehörde Köln                                          396
Name: count, dtype: int64

In [202]:
#print the top 200 unmatched entries
v_sum = 0

for n, v in df_unmatched_filtered['CompensationOffice1'].value_counts().iloc[:200].to_dict().items():
    print(f"{n}: {v}")
    v_sum += v

print(f"Total count of the top 200 unmatched entries: {v_sum}")

Landesamt für die Wiedergutmachung: 14641
Bayerische Kartei: 9925
Regierungsbezirksamt für Wiedergutmachung und verwaltete Vermögen: 7261
Bundeskartei: 4884
Bezirksamt für Wiedergutmachung: 4130
HNG: 3402
Regierungsbezirksamt für Wiedergutmachung und kontrollierte Vermögen: 3354
Bayerisches Landesarchiv: 2585
Regierungsbezirks-Amt für Wiedergutmachung und kontrollierte Vermögen: 2557
Bayerisches Landesamt für Verfolgtenfragen: 1291
Kreissonderhilfsausschuss: 1101
Kreissozialamt: 958
Bundesminister der Finanzen: 904
Entschädigungsbehörde: 863
Bundesamt: 834
König: 825
Bayerisches Landesamt für Vertriebene: 815
Reg.-Präsident / Präsident des Verw.-Bezirks: 752
KSHA: 750
Der Herr Regierungspräsident in Detmold: 745
Kreissozialhilfsausschuss: 712
Landesamt für Wiedergutmachung: 586
Bundesamt für Vertriebene: 560
Landesamt für Vertriebene: 541
Bayerisches Landesamt für Verfolgtenentschädigung: 521
Landesentschädigungsamt München 2, Arcisstraße 11: 501
Oberfinanzdirektion Niedersachsen Landesweite Bezüge- und Versorgungsstelle - Wiedergutmachung -: 483
Oberfinanzdirektion: Bundesvermögensabteilung: 478
Köln, Riehler Pl.2, 5000 Köln 1: 477
Amt für Wiedergutmachung und kontrollierte Vermögen: 470
Amt für Wiedergutmachung des Landes Rheinland-Pfalz: 470
Regierung Arnsberg (Wf.): 459
Doppelmeldung: 449
Amt für Wiedergutmachung Stadt Bonn: 447
Bundesamt für Wiedergutmachung: 439
Niedersachsen-Präsident / Präsident des Verwaltungsgerichtshofs: 437
Regierung Köln: 421
Bundesarchiv: 408
Reg.-Präsidium Hildesheim: 396
Entscheidungsbehörde Köln: 396
Erfurt: 386
Regierungsbezirksamt für Wiedergutmachung und verwaltete Vermögen Neustadt/W.: 381
Regierung Arnsberg: 375
An Bundeskartei: 371
Bayerisches Landesamt für Verfolgungsgeschädigte: 370
Niedersächsisches Landesverwaltungsamt - Wiedergutmachung: 365
BHF: 346
BEG: 340
Reg.-Präsident / Präsident des Verw.-Bezirks Braunschweig: 324
Bayerisches Hauptstaatsarchiv: 321
Landesentschädigungsamt München: 312
Reg.-Präsident / Präsident des Verw.-Bezirks Oldenburg: 309
Freie Hansestadt Bremen - Landesamt für Wiedergutmachung: 307
Freie Hansestadt Bremen: 307
Magistrat der Stadt Bremen: 306
Der Regierungspräsidium Düsseldorf: 297
Montabaur: 291
Regierungsbezirksamt für Wiedergutmachung und verwaltete Vermögen Neustadt/w.: 291
Reg.-Präsident / Präsident des Verwaltungsbezirks Hannover: 289
Regierungspräsidium Arnsberg: 285
Niedersächsisches Landesamt für Bezüge und Versorgung - Wiedergutmachung: 272
BMF: 269
Oberfinanzdirektion Rostock: 269
Niedersachsen-Präsident / Präsident des Verw.-Bezirks: 268
K81: 268
Frankfurt/M.: 267
K81n: 267
Regierungsamt Aachen (Westf.): 262
Regierungspräsidium Münster: 260
Ansbach: 257
Niedersachsen-Präsident / Präsident des Verwaltungsbezirks Lüneburg: 255
Niedersachsen-Präsident / Präsident des Verwaltungsbezirks: 251
Regierungsbezirksamt für Wiedergutmachung und kontrolliertes Vermögen: 248
Sondervermögens-u. Bauverwaltung: 242
Bayerisches Landesamt: 241
Regierung Ansbach (Würt.): 240
Regierungsbezirk für Wiedergutmachung und verwaltete Vermögen Neustadt a.d. Weinstr.: 238
Aurich/Ostfriesland: 235
Regionalverwaltungsbehörde für Wiedergutmachung und verwaltete Vermögen Koblenz: 229
Entschädigungsbüro Köln: 227
Magistrat der Stadt Bremenhaven: 224
Amt für Wiedergutmachung des Landes Rheinland/Pfalz: 222
VB3: 218
Kreissonderhilfsausschuss Hannover: 215
Bundesfinanzdirektion West: 214
Bayerisches Verfolgtenamt: 209
KSHA Hannover-Land: 206
Landeszentrale für die Vergütung von Opfern des Nationalsozialismus: 206
Regierungsbezirk Köln: 206
KSH: 205
Köln, Riehler Pl. 2, 5000 Köln 1: 204
Regierungsbezirk Arnsberg (Westf.): 203
Oberfinanzdirektion Erfurt: 201
Regierungsbezirk Trier: 197
Niedersächsisches Landesamt für Beziege und Versorgung - Wiedergutmachung: 197
Regierungsbezirk für Wiedergutmachung und kontrollierte Vermögen: 196
Niedersächsisches Ministerium des Innern: 193
Regierungsbezirk Neustadt a.d. Weinstr.: 192
Härtedefonds - Hessen: 187
Watenstedt-Salzgitter: 185
Landesbeauftragte für die Wiedergutmachung, Stuttgart: 185
Niedersachsen - Präsident des Verwaltungsbezirks Hannover: 183
Der Regierungspräsidialamt Düsseldorf: 182
Pirmasens: 181
Bayerisches Landeszentrum für die Opfer des Nationalsozialismus: 181
Regierungsbezirkskammer für Wiedergutmachung und verwaltete Vermögen Koblenz: 181
Kaiserslautern: 178
Niedersachsen Reg.-Präsident / Präsident des Verw.-Bezirks Hannover: 175
Bayerisches Landesamt für die Opfer des Nationalsozialismus: 173
Braunburg: 171
BfA Berlin: 168
Regierungspräsident - Dezernat f. Wiedergutmachung - Detmold: 166
Regierungsbezirksamt für Wiedergutmachung und verwaltete Vermögens: 166
Höherer Kommissar der Vereinten Nationen für Flüchtlinge: 166
Regierung Aachen (Westf.): 165
Niedersachsen-Präsident / Präsident des Verw.-Bezirks Hannover: 164
Regierung Ansbach (Welf.): 164
Kreissonderhilfsschübe: 163
Oberfinanzdirektion Cottbus: 162
EG: 160
Der Niedersächsische Minister des Innern: 159
Niedersachsen - Präsident / Präsident des Verwaltungsbezirks: 158
Kreisonderhilfsausschuss: 157
Regierungsbezirk für Wiedergutmachung und verwaltete Vermögen: 156
Freie und Hansestadt Hamburg, Amt für Wiedergutmachung: 156
Ministerium für Arbeit, Gesundheit und Soziales des Landes Schleswig-Holstein Entschädigungsbehörde: 155
Oberfinanzdirektion Berlin: 153
Burgdorf: 152
Wiedergutmachung: 151
Neustadt a.d. Weinstr.: 149
Regierungsbezirksamt für Wiedergutmachung: 147
Bezirksamt von Koblenz für Wiedergutmachung TRIER: 143
Nürnberg: 142
Niedersachsen-Präsident / Präsident des Verwaltungsbezirks Osnabrück: 141
Der Innensenator des Landes Nordrhein-Westfalen: 141
Niedersachsen-Präsident: 140
Bayerisches Verwaltungsamt: 137
Der Regierungspräsident: 137
Tr.: 137
KSHA Celle-Stadt: 137
Die Ministerin für Arbeit, Soziales Jugend und Gesundheit des Landes Schleswig-Holstein Entschädigungsbehörde: 136
Lüneburg-Stadt: 135
Kreissozialhilfsausschuss Hannover: 133
Bezirksamt für Wiedergutmachung München: 133
Regierungsbezirks-Amt für Wiedergutmachung und kontrolliertes Vermögen: 128
Regierung Ansbach (Württ.): 126
Bayerisches Landesamt für Wiedergutmachung: 125
Kreissozialamt Braunschweig-Stadt: 124
KSHA Osterode/H.: 124
Hessen Neu: 123
Bekannt: 123
Reg.-Präsident / Präsident des Verw.-Bezirks Lüneburg: 122
Köln, Riehlstr. Pl.2, 5000 Köln 1: 122
Kreissozialhilfsausschuss Braunschweig-Stadt: 121
Regionalverwaltungsbehörde für Wiedergutmachung und verwaltete Vermögen Mainz: 120
KSHA Braunschweig: 119
Statistisches Landesamt Nordrhein-Westfalen, Düsseldorf 1, Postfach 1105: 119
Regierungsbezirk München: 117
Bundesverwaltungsamt: 117
Oberfinanzdirektion Chemnitz: 117
Der Oberkreisdirektor -Amt für Wiedergutmachung- in Herford: 116
Regierungsbezirk Mainz für Wiedergutmachung und verwaltete Vermögen: 116
Der Bundesminister der Finanzen: 116
KSHA München: 114
Aurich i.Ostfriesl.: 114
Freie Hansestadt Bremen, Der Senator für Arbeit, Landesamt für Wiedergutmachung: 113
Regionalverwaltungsamt für Wiedergutmachung und verwaltete Vermögen Mainz: 112
Landesamt für die wiedergutmachung: 111
Regionalverwaltungsamt für Wiedergutmachung und verwaltete Vermögen Koblenz: 111
BMF - VB4: 109
Regierung Düsseldorf: 108
K61n: 108
Braunschweig-Stadt: 106
Bayerisches Landesamt für Verfolgten: 106
Der Innensenator des Landes Nordrhein-Westfalen Abteilung V: 106
Bayerische Landesentschädigungs- und Staatschuldenverwaltung: 106
Stadt Hameln: 104
Oberfinanzdirektion Koblenz: 104
Bebra: 104
Landesstelle für die Wiedergutmachung: 103
Freie und Hansestadt Hamburg Sozialbehörde Amt für Wiedergutmachung Hamburg 1, Alstädter Straße 8 (Springenhoof): 102
KSHA Oldenburg: 101
Freie und Hansestadt Hamburg Sozialbehörde Amt für Wiedergutmachung Hamburg 1, Alstädter Straße 8 (Springenhorf): 101
K81m: 101
Bayerisches Landesamt für Verfolgte des Nationalsozialismus: 100
Regierungsbezirk für Wiedergutmachung und verwaltete Vermögen Mainz: 98
Freie und Hansestadt Hamburg Sozialbehörde Amt für Wiedergutmachung Hamburg 1, Alsterdorfer Straße 8 (Sprinkenhof): 98
Reg.-Präsident des Verw.-Bezirks Hannover: 97
Amt Regierungsbezirksamt für Wiedergutmachung und kontrollierte Vermögen: 97
Regierungsbezirk Koblenz: 97
Niedersachsen Reg.-Präsident Hannover: 96
Landesamt für Finanzen Landesentschädigungsamt: 96
Amt für Wiedergutmachung des Selbstkantkreises Geilenkirchen-Heinsberg und Regierungspräsident Aachen: 95
Freie und Hansestadt Hamburg Sozialbehörde Amt für Wiedergutmachung Hamburg 1, Alsterstraße 8 (Springenhoof): 95
Bay: 94
Landesentschädigungsamt München 2: 94
Nienburg-Weser: 94
KSHA Göttingen: 93
Suchkartei für Bez. Reg.: 93
Haftbescheid: 93
Total count of the top 200 unmatched entries: 100934

In [203]:
list_further_corrections = ['Oberfinanzdirektion Rostock', 'Niedersächsisches Landesamt für Bezüge und Versorgung - Wiedergutmachung',
                        'Regierungspräsidium Arnsberg', 'Reg.-Präsident / Präsident des Verwaltungsbezirks Hannover', 
                        'Regierungsbezirksamt für Wiedergutmachung und verwaltete Vermögen Neustadt/w.', 'Montabaur', 
                        'Der Regierungspräsidium Düsseldorf', 'Magistrat der Stadt Bremen', 'Freie Hansestadt Bremen', 
                        'Freie Hansestadt Bremen - Landesamt für Wiedergutmachung', 'Reg.-Präsident / Präsident des Verw.-Bezirks Oldenburg', 
                        'Landesentschädigungsamt München', 'Bayerisches Hauptstaatsarchiv', 'Reg.-Präsident / Präsident des Verw.-Bezirks Braunschweig', 
                        'Niedersächsisches Landesverwaltungsamt - Wiedergutmachung', 'Bayerisches Landesamt für Verfolgungsgeschädigte', 
                        'Regierung Arnsberg', 'Regierungsbezirksamt für Wiedergutmachung und verwaltete Vermögen Neustadt/W.', 'Erfurt', 
                        'Entscheidungsbehörde Köln', 'Reg.-Präsidium Hildesheim', 'Bundesarchiv', 'Regierung Köln', 
                        'Niedersachsen-Präsident / Präsident des Verwaltungsgerichtshofs', 'Amt für Wiedergutmachung Stadt Bonn', 
                        'Regierung Arnsberg (Wf.)', 'Amt für Wiedergutmachung des Landes Rheinland-Pfalz', 
                        'Köln, Riehler Pl.2, 5000 Köln 1', 'Oberfinanzdirektion Niedersachsen Landesweite Bezüge- und Versorgungsstelle - Wiedergutmachung -', 
                        'Landesentschädigungsamt München 2, Arcisstraße 11', 'Bayerisches Landesamt für Verfolgtenentschädigung', 
                        'Bundesamt für Vertriebene', 'Der Herr Regierungspräsident in Detmold', 'Bayerisches Landesamt für Vertriebene', 
                        'Bayerisches Landesarchiv', 'Bayerisches Landesamt für Verfolgtenfragen', 'Bundesminister der Finanzen',
                        'Niedersachsen-Präsident / Präsident des Verw.-Bezirks', 'Frankfurt/M.', 'Regierungsamt Aachen (Westf.)', 
                        'Regierungspräsidium Münster', 'Ansbach', 'Niedersachsen-Präsident / Präsident des Verwaltungsbezirks Lüneburg',
                        'Regierung Ansbach (Würt.)', 'Regierungsbezirk für Wiedergutmachung und verwaltete Vermögen Neustadt a.d. Weinstr.',
                        'Aurich/Ostfriesland', 'Regionalverwaltungsbehörde für Wiedergutmachung und verwaltete Vermögen Koblenz',
                        'Entschädigungsbüro Köln', 'Magistrat der Stadt Bremenhaven', 'Amt für Wiedergutmachung des Landes Rheinland/Pfalz',
                        'Kreissonderhilfsausschuss Hannover', 'Bayerisches Verfolgtenamt', 'KSHA Hannover-Land', 'Regierungsbezirk Köln',
                        'Köln, Riehler Pl. 2, 5000 Köln 1', 'Regierungsbezirk Arnsberg (Westf.)', 'Oberfinanzdirektion Erfurt', 
                        'Regierungsbezirk Trier', '']

In [204]:
list_no_sufficient_information = ['Niedersachsen-Präsident / Präsident des Verwaltungsbezirks', 'An Bundeskartei', 
                              'Bundesamt für Wiedergutmachung', 'Amt für Wiedergutmachung und kontrollierte Vermögen', 
                              'Oberfinanzdirektion: Bundesvermögensabteilung', 'Landesamt für Vertriebene', 
                              'Landesamt für Wiedergutmachung', 'Kreissozialhilfsausschuss', 'Reg.-Präsident / Präsident des Verw.-Bezirks', 
                              'Entschädigungsbehörde', 'Kreissozialamt', 'Kreissonderhilfsausschuss', 'Regierungsbezirks-Amt für Wiedergutmachung und kontrollierte Vermögen', 
                              'Regierungsbezirksamt für Wiedergutmachung und kontrollierte Vermögen', 'Bundeskartei', 
                              'Regierungsbezirksamt für Wiedergutmachung und verwaltete Vermögen', 'Kreissozialamt', 'Bundesamt', 'Doppelmeldung', 
                              "Landesamt für die Wiedergutmachung", "Bezirksamt für Wiedergutmachung", "Kreissozialamt", "König",
                              'Regierungsbezirksamt für Wiedergutmachung und kontrolliertes Vermögen', 'Sondervermögens-u. Bauverwaltung',
                              'Bayerisches Landesamt', 'Bundesfinanzdirektion West', 'KSHA', 'KSH', 'Regierungsbezirk für Wiedergutmachung und kontrollierte Vermögen',
                              ]

In [205]:
print(len(list_no_sufficient_information))

30

In [206]:
#filtering out impossible matches and further additions to gt
for office in list_no_sufficient_information + list_further_corrections:
    if office in df_unmatched_filtered['CompensationOffice1'].values:
        df_unmatched_filtered = df_unmatched_filtered[df_unmatched_filtered['CompensationOffice1'] != office]

print(len(df_unmatched_filtered))
print(len(df_unmatched_filtered['CompensationOffice1'].unique()))

98173
24451

In [207]:
df_matches_correctable = lev_matches.dropna()
print(len(df_matches_correctable))
df_matches_impossible = lev_matches[lev_matches['MatchedOffice'].isna()]
impossible_list = df_matches_impossible['CompensationOffice1'].tolist()
print(len(impossible_list), len(set(impossible_list)))
# print the unique values in the impossible list and their counts in descending order
for office in sorted(set(impossible_list), key=impossible_list.count, reverse=True):
    count = impossible_list.count(office)
    print(f"{office}: {count}")

145672
52099 7005
Bayerische Kartei: 9925
Bundeskartei: 4884
HNG: 3402
Bayerisches Landesarchiv: 2585
Kreissozialamt: 958
Bundesamt: 834
KSHA: 750
Kreissozialhilfsausschuss: 712
Köln, Riehler Pl.2, 5000 Köln 1: 477
Doppelmeldung: 449
Bundesarchiv: 408
Erfurt: 386
An Bundeskartei: 371
BHF: 346
BEG: 340
Bayerisches Hauptstaatsarchiv: 321
Magistrat der Stadt Bremen: 306
Montabaur: 291
BMF: 269
K81: 268
K81n: 267
Frankfurt/M.: 267
Ansbach: 257
Sondervermögens-u. Bauverwaltung: 242
Bayerisches Landesamt: 241
Aurich/Ostfriesland: 235
Magistrat der Stadt Bremenhaven: 224
VB3: 218
Bayerisches Verfolgtenamt: 209
Landeszentrale für die Vergütung von Opfern des Nationalsozialismus: 206
KSH: 205
Köln, Riehler Pl. 2, 5000 Köln 1: 204
Watenstedt-Salzgitter: 185
Pirmasens: 181
Bayerisches Landeszentrum für die Opfer des Nationalsozialismus: 181
Kaiserslautern: 178
Bayerisches Landesamt für die Opfer des Nationalsozialismus: 173
Höherer Kommissar der Vereinten Nationen für Flüchtlinge: 166
Kreissonderhilfsschübe: 163
EG: 160
Der Niedersächsische Minister des Innern: 159
Burgdorf: 152
Tr.: 137
Bayerisches Verwaltungsamt: 137
Bekannt: 123
Köln, Riehlstr. Pl.2, 5000 Köln 1: 122
Bundesverwaltungsamt: 117
Aurich i.Ostfriesl.: 114
BMF - VB4: 109
K61n: 108
Bebra: 104
K81m: 101
Bayerisches Landesamt für Verfolgte des Nationalsozialismus: 100
Nienburg-Weser: 94
Bay: 94
Suchkartei für Bez. Reg.: 93
KSHA Göttingen: 93
K8In: 85
Stadt Bonn: 84
Bad Kreuznach: 80
KSHA Wilhelmshaven: 79
Neuwied: 78
Kreisaußerhelfsausschuss: 76
Doppelmeldung München: 73
Kreis Lindau: 73
He: 72
ERFURT: 71
K61: 71
Sondervermögens- u. Bauverwaltung: 71
Regierung Ansbach: 70
Bayerisches Verfolgtenzentrum: 70
Landkreis Osterholz: 69
Bundesstelle: 69
Aurich / Ostfriesland: 66
Kreissonderhilfsschul: 66
Höherer Kommissar der Vereinigten Nationen für Flüchtlinge: 65
Bayerisches: 63
DOPPELMELDUNG: 62
Frankfurt a.M.: 61
KSHA Goslar-Land: 60
KSHA Gifhorn: 60
Doppel Meldung: 58
KSHA Emden: 58
Doppelvermerk: 58
Ludwigshafen am Rhein: 57
BHT: 56
Kreisaußerhilfsausschuss: 56
KSHA Celle/Land: 54
Regierung Aachen (Wf.): 52
KSHA Winsen/Luhe: 52
Aussensenstelle Freiburg i.Br.: 51
United Restitution Office, Frankfurt/Main, Grüneburgweg 119: 51
Bayerisches Verfolgungsausschuss: 50
Hauptbescheid: 48
KSHA Soltau: 48
Bundeskartothek: 48
Sondervermögens- und Bauverwaltung: 46
Doppelmeldung Berlin: 45
Doppelmeldung Köln: 45
Frankfurt: 45
KSHA Springe: 44
Baastrup: 44
Rostock: 43
Nordhorn: 41
Sondervermögens-u. Bauerverwaltung: 41
KSHA Wittmund: 41
Kreisonderrhilfsausschuss: 41
KSHA Watenstedt-Salzgitter: 40
Braunau: 39
Bayerisches Verfolgungsamt: 39
KSHa: 39
Anstalt des Bundes: 39
K817: 38
KSHA Holzminden: 38
Doppelmeldung Stuttgart: 38
Wolfenbüttel: 38
LG: 38
Hamburg 36, Drehbahn 36IV: 37
K51n: 37
An Bundesamt: 36
Stadthaus: 36
Anspruchsberechtigter: 36
KSHA Zellerfeld: 36
Frankfurt a. M.: 36
KSHA Neustadt a.Rbge.: 35
KSHA Hild. Marb.: 35
KSHA Cloppenburg: 34
Nordden: 34
Landkreis Göttingen: 34
KSHA Northheim: 34
BHF - VB4: 34
Landesstelle für die Regelung von Schadensersatzansprüchen: 33
BHF-VB3: 33
Hauptstelle: 32
Landeszentrale für die Vergütung: 32
Hamburger Stiftung Hilfe für NS-Verfolgte: 32
München 2, Arcisstraße 11: 32
Bonn: 31
KSHA Ammerland: 31
K51: 31
BMF-VB4: 31
HNC: 30
KSHA Burgdorf: 30
Stuttgart-S, Neue Weinsteige 21: 30
Nazi Germany Compensation Office: 29
Frankfurt-Main: 29
KSHA Mepen: 29
Köln, Riehlstr. Pl. 2, 5000 Köln 1: 29
KSHA Winsen-Luhe: 28
Doppelmeldung Koblenz: 28
Kreissonderhilfsschüle: 28
Bezirksamt von Koblenz: 28
Königreich-Preußen Berlin: 28
BFD West: 28
Bundessstelle: 28
Service-Center Köln: 27
BMF-UB4: 27
Hu: 27
Frankfurt am Main: 27
Ludwigshafen a. Rh.: 27
Minister des Innern: 27
Kreissonderhilfsausschub: 26
United Restitution Office, Frankfurt/Main, Gruneburgweg 119: 26
KSHA Wesermünde: 26
KSHA Nörtheim: 26
Kreissozialhilfsschul: 26
Kreissozialhilfeausschuss: 26
KSHA Wolffenbüttel: 25
Landau/Pfalz: 25
Sondervermögens-U. Bauverwaltung: 25
Bundeszentralstelle für Verfolgte: 25
Regierung München (Wf.): 25
KSHA Uelzen: 25
Hamburger Stiftung: 25
Doppelmeier: 25
Landesbeiratstelle: 24
Hauptstaatsarchiv München: 24
Landeszentrale für die Vergütung der Opfer des Nationalsozialismus: 24
Syke: 24
KSHA Delmenhorst: 23
Schw.: 23
Landesbezirksstelle: 23
Sachverständigenstelle für Bez. Reg.: 23
Soest: 23
51: 23
Einbeck: 23
BHF-VB4: 22
Stiftung: 22
United Restitution Office: 22
Landesverwaltungsamt München: 22
Landesbeirat: 22
K8lm: 22
: 21
Aurich I. Ostfriesland: 21
Doppelmelung: 21
Doppelmayr: 21
Holm: 21
KSHC: 21
KSHA Northeim: 21
United Restitution Office, Frankfurt/M., Grünburgweg 119: 21
Landesamt für: 21
Höherer Kommissar der Vereinten Nationen für Flüchlinge: 21
KSHA Colle/Land: 21
BHF-UB4: 21
KSHA Veckta: 20
A.Z.: 20
BRD: 20
Landesarchiv München: 20
Altenkirchen Westerw.: 20
KSHA Friesland: 20
Regierung München: 20
Kn: 20
Alfeld/Leine: 20
Si.: 19
K810: 19
K8: 19
K81a: 19
DHF: 19
Dudersfeld: 19
United Restitution Office, Frankfurt: 19
K814: 19
BayHStA: 19
Köln, Riehler Pl.2, 5000 Köln: 19
Ausgl. Amt Bremen: 19
An Bundesarchiv: 19
KSHA Nordhorn: 18
United Restitution Office, Frankfurt/M., Gruneburgweg 119: 18
Bayerisches Verfolgungsausschussamt: 18
H81n: 18
Kreis Lindenau: 18
BEG-Kartei: 18
Landesamt für Kultur und Wissenschaft: 18
Bayerische Landeszentrale für die Opfer des Nationalsozialismus: 18
K61m: 18
Landeszentrale für die Opfer des Nationalsozialismus: 18
KSHA Münden: 18
Bielefeld: 18
Bundesverwaltungsamt Köln: 18
Doppelmeldung Hamburg: 18
KSHA Neustadt a. Rbge.: 17
Doppelvermerk München: 17
Aurich I.Ostfriesland: 17
81: 17
BMF - VBH: 17
Friesland: 17
Kln: 17
Bayerisches Landeszentrum für Opferberatung und Opferhilfe: 16
KSHA Ganderkesheim: 16
K 51: 16
Doppelvermerkung: 16
B.V.: 16
Landeszentrale für politische Opferhilfe: 16
Alfeld: 16
Kreissonderhilfsschule: 16
Frankfurt/Main: 16
Holz: 16
Bundeskärtei: 16
United Restitution Office, Frankfurt/M., Grüneburgweg 119: 15
United Restitution Office, Frankfurt/M.: 15
An Bundesekartei: 15
Delmenhorst: 15
Doppelvermögen: 15
KSHA Mappen: 15
Landau/Pf.: 15
Niedersachsen-Präsident / Präsident des Landes: 15
KSHA Winsen/L.: 15
BMF - VB 4: 15
Landesamt: 15
K812: 15
51n: 15
Gifhorn: 15
Stadtverwaltung Stadthagen: 15
Kreissonderhilfsschüf: 15
K8m: 15
Kreisonderhelfsausschuss: 15
Ländeszentrale für die Opfer des Nationalsozialismus: 15
KSHA Melle: 15
Higher Commissioner of the United Nations for Refugees: 14
Bundeskammer: 14
BHF- VB4: 14
Köln, Riehler Pl.2: 14
Bundesländer: 14
Bayer. Landeszentrale: 14
KSHA Diepholz: 14
Aurich i.Ostfriesland: 14
Regierung Bamberg: 14
Ve: 14
Kreissonderbehelfsausschuss: 14
AfW Aachen-Stadt: 13
Landesverwaltungsamt München II: 13
KSHA Aschendorf/Ems: 13
Wiedergutmachung und verwaltete Vermögen: 13
KSHA Alfeld: 13
Landesbeiratssstelle: 13
Fallingbostel: 13
Landesarchiv Muenchen: 13
K 81: 13
Gerichtsurteil: 13
Wehrmacht: 13
Aurich i. Ostfriesl.: 13
Hohes Kommissariat der Vereinten Nationen für Flüchtlinge: 13
Doppel Meldung München: 13
Deutsches Zentrales Stelle: 12
Sondervermögens-u. Baubewaltung: 12
Landkreis Grafschaft Lippe: 12
Landeszentrale für politische Opferentschädigung: 12
KSHA Schaußburg-Lippe: 12
R81n: 12
Doppel Meldung Stuttgart: 12
Bayerisches Archiv für Sozialgeschichte: 12
KSHA Stadt Hameln: 12
Bayisches Landesarchiv: 12
KSHA Verden: 12
KSHA f.d. Reg. Bez. Hildesheim: 12
Köln, Reichler Pl.2, 5000 Köln 1: 12
Kreisonderschutzbehörde: 12
KSHA Wolfsenbüttel: 12
K816: 12
Braunfels: 12
KSM: 11
Haltestelle: 11
Bayerisches Verfolgten: 11
KSHA Brake: 11
Bayerisches Landesamt für Verfolgtenaufwandsentschädigung: 11
Sondervermögens-Bauverwaltung: 11
Weimar: 11
Aurich / Ostfriesl.: 11
DOPPELMELDUNG Berlin: 11
Bavarian Compensation Office: 11
Aussensenstelle Freiburg: 11
Doppelmeidung: 11
Regional Office for Compensation and Administration of Assets, Mainz: 11
Landkreis Grafschaft Goya: 11
Landesamt für Vertriebene, Flüchtlinge und Kriegsgeschädigte: 11
We: 11
Sondervermögens-u. Bäuerwaltung: 11
KSHA Schauburg-Lippe: 11
DOPPELMELDUNG München: 11
Bayerisches Landeszentrale: 11
Doppelvermeldung: 10
Landesbeauftragte: 10
KSHA Cologne/Land: 10
Ko: 10
KSHA Hamm: 10
KSHA Minden: 10
DOPPELMELDUNG Köln: 10
BZK: 10
Kai: 10
K51m: 10
Burgdorf (Hann.): 10
Aussenstelle Freiburg i.Br.: 10
Bundesverwaltungsamt in Köln: 10
KSHA Celle-Land: 10
Bundesarchive: 10
KSHA Bremervörde: 10
R8ln: 10
K818: 10
Schwerin: 10
Kreissonderhilfesauschuss: 10
An Bundeseskartei: 10
Regionalverwaltungsgericht Koblenz: 10
Wiedergutmachung, Stuttgart: 10
K6: 10
KSHA Götttingen: 10
Bayer. Landesarchiv: 10
Köln, Riehler Pl. 2: 10
Regierung Hessen: 10
Der hessische Landtag: 10
Doppelmedlung: 10
Regionalverwaltungsbehörde für Wien: 10
BHF - VB3: 10
Wittlage: 10
Regional Office for Compensation and Administration of Assets, Neustadt a.d. Weinstr.: 10
Regierung München (MfV): 9
Düsseldorfer Regierungspräsidium: 9
KSHA Wittlage: 9
KSHA Gelle/Land: 9
Bundes: 9
Doppelmelung München: 9
61n: 9
KSHA Hameln-Pyrmont: 9
Landesjustizverwaltung: 9
Beg: 9
Bundes-Verw.-Amt: 9
Kreissonderhilfsschutz: 9
Wittmund: 9
Regierung Münster: 9
Landesamt für die Rückstellung: 9
Aussensenstelle Freiburg/Br.: 9
Braun: 9
Ankunftskartei: 9
Holzminden: 9
Aussensestelle Freiburg i.Br.: 9
Sachkartei für Bez. Reg.: 9
KSHB: 9
K: 9
Krois Lindau: 9
Doppelmedung: 9
Heimat: 9
Sen. f. Fin: 9
Bayerisches Verfolgtenarchiv: 9
Sondervermögens- u. Bauerverwaltung: 9
KSHA Nürnberg: 9
DM 500: 9
Bayerisches Kartei: 9
Bezirksamt: 9
Kreisonderhilfsausschub: 8
Bundesarchiv Berlin-Lichterfelde: 8
Bayerisches Verwaltungsgericht: 8
Doppelmeldung Kiel: 8
Haftbeschädigte: 8
Kreisaußerhelfsausschub: 8
KSHA Linggen: 8
Köln, Riehler Pl. 2, 5000 Köln: 8
BVA: 8
KSHA Norden: 8
A.D.I.V.A. Bureau de Restitution: 8
Kreisondeserhifsausschuss: 8
Aurich I.Ostfriesl.: 8
K811: 8
Öl: 8
Landesamt für die Regelung von Vermögensangelegenheiten: 8
Landesheiratstelle: 8
Königlich-Preußische: 8
KBl: 8
Bay. Landesarchiv: 8
Völker: 8
KSHA Köln/Land: 8
KBlm: 8
LG Frankfurt: 8
Ministerium des Innern: 8
Schwabach: 8
Noin: 8
K81nt: 8
Regional Office for Compensation and Administration of Assets, Koblenz: 8
Aurich /Ostfriesland: 8
61: 8
Landesbeirksstelle: 8
Hauptescheide: 8
K815: 8
Bayerisches Zentralarchiv: 8
K31n: 8
United Restitution Office, Frankfurt/Main, Grünburgweg 119: 8
Bayerisches Landeszentrale für die Opfer des Nationalsozialismus: 8
KSHA Einbeck: 8
Leipzig: 8
Bauverwaltung: 8
Doppelmeilung: 8
Regionalverwaltungsgericht Trier: 7
KOM: 7
Regierung Pommern: 7
Doppelmeldung Mainz: 7
Landesamt für die Verfolgten des Nationalsozialismus: 7
Bundeskartell: 7
Bund: 7
United Restitution Office, Frankfurt/M. Grünburgweg 119: 7
Landesamt für die Rückstellung von Opfern des Nationalsozialismus: 7
81n: 7
KSH Nord: 7
KSHC Cuxhaven: 7
Bln: 7
Kreissozialhilfsschulung: 7
Kreisverwaltung - Amt f. Wiedergutmachung - Höxter/Weser: 7
Leer/Ostfriesl.: 7
An der Bundeskartei: 7
Bundeskarte: 7
Landesarchiv Münster: 7
St. H.: 7
Uel: 7
Wiener Landesgericht: 7
Bayerisches Archiv für Zeitgeschichte: 7
BayHauptstelle: 7
Landsgericht München I: 7
K61a: 7
Südliches Zentralstelle: 7
Kreis Linden: 7
Doppelmeldeamt: 7
KSHA Fallingbostel: 7
K31: 7
DOPPELMELDUNG Stuttgart: 7
Regionalverwaltungsgericht München I: 7
Bayerisches Landesamt für Jugend und Verwahrlosungsschutz: 7
Doppelvermögensbehörde: 7
An Bundeeskartei: 7
Bezirksamt Koblenz: 7
Paris: 7
Landesbeirat Stuttgart: 7
Staatsministerium für Innerdeutsche Beziehungen: 7
Doppelvermögens-u. Bauverwaltung: 7
Stadtverwaltung: 7
KSHA Zellerafeld: 7
Köln, Riehlstr. Pl.2, 5000 Köln.1: 7
Kreisondertshilfsausschuss: 7
Allianz: 7
Ausgl.Amt Bremen: 7
Sondervermögens- und Baufondsverwaltung: 6
Hund. Verw. Amt: 6
KSHC Celle/Land: 6
BAfT: 6
Bundesstelle Köln: 6
Staatsanwalt Köln: 6
Landeszentrale: 6
Hauptbeschwerde: 6
Regionalverwaltungsbehörde für Wien und Niederösterreich: 6
Bayer. Landesamt: 6
Ravensburger Kartei: 6
EfrA: 6
Birkenfeld: 6
KAI: 6
Regierung: 6
K819: 6
Landesamt für Verbraucherschutz und Lebensmittelsicherheit: 6
Landau, Pf.: 6
Hauptbesoldung: 6
Sen. f. Fin.: 6
Efurt: 6
A.f.W. Rhein. Pfalz: 6
KSH Hamm: 6
Höherer Kommissar der Vereinigten Nationen für Flüchlinge: 6
BayHaupt: 6
Kreissonderhilfsschuss: 6
Kreisverwaltung Paderborn: 6
Tr. 11: 6
Rheinland: 6
Hauptzuständige Behörde: 6
Sachverständigenstelle für BZK: 6
Karlsruhe Aussenstelle Freiburg i.Br.: 6
Kreissozialhilfesausschuss: 6
Landkreis Oschersleben: 6
Niedersächsische Ersatzbehörde: 6
Hamburg 36, Drehbahn 37IV: 6
Landesjustizverwaltung München: 6
Bayerisches Archiv: 6
Landsgericht München II: 6
Kreissonderhilfsschüfe: 6
Aurich/Ostfriesl.: 6
HHG: 6
K&In: 6
VORGANG an Köln: 6
Bundesarchiv Koblenz: 6
Landesrentenbehörde: 6
KSHA Meppe: 6
OLDB: 6
Haftbescheinigung: 6
Tr. Bayerisches Landesarchiv: 6
Vergütungsausschuss: 6
A: 6
Nazi Victims Compensation Office: 6
Kreisonderrhilfsausschub: 6
Bureau de Restitution: 6
HJ: 6
Anstalt des Bundes Oldenburg: 6
KSHA Hammeln-Pyrmont: 6
Schreiber: 6
Staatsanwalt Hamburg: 6
Landesjustizverwaltung, Stuttgart: 6
BHF - VB 4: 6
Doppelmeidung München: 6
KSHa Celle/Land: 6
Bundes'kartei: 6
KSHA Darmenber/Elbe: 6
Ausland: 6
Emden: 6
Norden: 6
BMF- VB4: 6
BZA: 5
ES/A: 5
Kreisaußerhelfsausschuß: 5
H81m: 5
Hauptstaatsarchiv: 5
KdF: 5
Reg.-Träger Münster: 5
Magistrat der Stadt Braunschweig: 5
Süddeutsche: 5
Bay. Landesamt: 5
Karlsruhe, Außenstelle Freiburg i.Br.: 5
Bundesverwaltungsamt - Abteilung II: 5
K510: 5
Dannenberg/Elbe: 5
Köln (Brüssel): 5
Landeszentrale - Registrierung: 5
KSHA Vehta: 5
Kreisonderhlfasschul: 5
Ni/La: 5
Härtefonds: 5
Bayerisches Landesamt für Akten und Archivwesen: 5
Dr. Müller: 5
R8In: 5
Ausg. Amt Bremen: 5
KSHA Rottenburg/H.: 5
Landesbeamtenschaft: 5
Landkreis Isarloh: 5
Kreissozialhilfsschule Peine: 5
Königreich-Preuß Berlin: 5
ö1: 5
London: 5
X8In: 5
Regionalverwaltungsbehörde: 5
United Restitution Office, Frankfurt/M, Grünburgweg 119: 5
Tr. Landeszentrale für die Vergütung von Opfern des Nationalsozialismus: 5
K5: 5
H8In: 5
Doppelmeldung Karlsruhe: 5
W81n: 5
Sondervermögens-u. Bautverwaltung: 5
Landau Pf.: 5
Höherer Kommissar der Vereinigten Nationen für Deutschland: 5
K610: 5
Ga: 5
Südliches Zentralbüro: 5
KSHA Winsen - Luhe: 5
Köln, Riehler, Pl.2, 5000 Köln 1: 5
Faulenstraße 69, 28195 Bremen: 5
BFA: 5
Bayerische Landeszentrale: 5
Fu.: 5
In: 5
AfW Mettmann RP Düsseldorf: 5
K 8 In: 5
Landesamt für Vertriebenenwesen Köln: 5
Regierung Posen: 5
BHF-VR4: 5
Regionalverwaltungsgericht München: 5
Landeszentrale für politische Opferfürsorge: 5
Stadtverwaltung Stadthaus: 5
Bayerisches Verfolgungsarchiv: 5
Sozialgericht Berlin: 5
Bayerisches Verfolgungsgesamt: 5
Kreissozialhilfsschule Braunschweig-Stadt: 5
Bayer. Landesjustizverwaltung: 5
Sondervermögens- und Bauerverwaltung: 5
Landesentschädigungsstelle für die Bundesrepublik Deutschland: 5
Bayerisches Verfolgungssamt: 5
Doppelung: 5
An Bundeskartellamt: 5
Schreibtisch: 5
Doppelvermerkung Berlin: 5
Nazi Germany: 5
Rinteln: 5
An Bundeseskartei Hannover: 5
Deutsches Versicherungsamt: 5
Higher Commissioner for Refugees of the United Nations: 5
Wolm: 5
Higher Commissioner of the Allied Powers for Refugees: 5
Landkreis Osierholz: 5
United Restitution Office, Frankfurt/Main: 5
Aussenstelle Freiburg: 5
Wiedergutmachung Mainz: 5
United Restitution Office, Frankfurt am Main, Grünburgweg 119: 5
Fu: 5
An Bundeskammer: 5
Bekanntmachung: 5
Komm: 5
H8m: 5
Köln, Riehl Pl.2, 5000 Köln 1: 5
Landgericht München: 5
An Bundes'kartei: 5
Zentralstelle für NS-Opfer: 5
Doppel Meldung Köln: 5
Bayerisches L.E.A.: 5
Bay. Kartei: 5
Kreissozialhilfsschulze: 4
Breslau, Gutenbergstr. 18: 4
BVAmt: 4
Köln, Riehler Pl.2, 5000 Köln 4: 4
BMF-VT4: 4
Ausgl.AmtBremen: 4
K51a: 4
Doppelmaßung: 4
Bundeszentrale für die Opfer des Nationalsozialismus: 4
Kreissozialamt Landkreis Grafschaft Lippe: 4
Karlsruhe Außenstelle Freiburg i.Br.: 4
Rhd.-Pfalz: 4
Finanzamt: 4
K8 In: 4
KSHA Rinteln: 4
BPA: 4
Hauptbeschädigte: 4
Niedersachsen-Präsident / Landesarchiv Hannover: 4
Regional Office for Compensation and Administration of Seized Assets, Koblenz: 4
Bundeszentralstelle für Opfer des Nationalsozialismus: 4
Hdn: 4
Doppelmeilung Berlin: 4
Baden-Württemberg: 4
Aurich, Ostfriesland: 4
Landsmannschaft der Verfolgten des Nationalsozialismus: 4
Sondervermögens-u. Beauftragung: 4
Kann: 4
Senatsentscheid: 4
KSHA Solttau: 4
München 2, Arcistraße 11: 4
Tr. Samt: 4
Kreissozialhilfsschule Goslar-Stadt: 4
Karlruhe Aussenstelle Freiburg i.Br.: 4
Lindau: 4
Dudorf: 4
An Bundeskärtei: 4
KSHA Nienburg/Weser: 4
Südwest: 4
Kreissozialamt Landkreis Grafschaft Hoya: 4
Wattenscheid-Salzgitter: 4
Bekirksamt: 4
H8lm: 4
Regierung Hamburg: 4
Doppelmeierung: 4
Altenkirchen, Westerw.: 4
Hohner Kommissar der Vereinten Nationen für Flüchtlinge: 4
Bayerisches Versäumnisamt: 4
K6lm: 4
RA. United Restitution Office, Frankfurt/Main: 4
Reichsverwaltungsamt: 4
Bayerisches Landesamt für Vertriebene und Flüchtlinge: 4
Kreis Linz: 4
Hauptverwaltungsamt: 4
DSHF: 4
KO: 4
Landesverwaltungsamt Bayern: 4
Kreisonderschutz: 4
BHT-VB3: 4
An Bundesakartei: 4
Tr. Landesarchiv München: 4
Vorgang an Koblenz: 4
Kreissozialamt des Landkreises Göttingen: 4
Bayerische Landesstelle: 4
Deutsches Zentrum für die Opfer des Nationalsozialismus: 4
Kd: 4
Kreisonderholfasschuf: 4
K618: 4
BMF/IVB4: 4
Efrat: 4
An Bundesländer: 4
Sudkartei für Bez. Reg.: 4
Altenkirchen Westerwald: 4
Wolffenbüttel: 4
Niedersachsen-Präsident / Reg.-Präsident: 4
H8ln: 4
Sachbearbeitung BZK Reg.: 4
Feststellungsbescheid in Stuttgart: 4
Bund. Verw. Amt: 4
Staatsanwaltschaft Hamm: 4
Regional Office for Compensation and Administration of Assets: 4
Krois Linder: 4
Anstalt des Bundes für die Verwaltung von Vermögensverzeichnissen: 4
DOPPELUNG: 4
Güteverfahren: 4
Bayerisches Staatsarchiv: 4
Tr. des Verfolgten: 4
Auschwitz: 4
Landesentschädigungsbehörde für die Bundesrepublik Deutschland: 4
unbekannt: 4
Miltam Israel Office: 4
Nienburg/Weser: 4
Neuried: 4
Regierung Hessen (Wf.): 4
Honer Kommissar der Vereinten Nationen für Flüchtlinge: 4
KSHA d. Reg. Bez. Hildesheim: 4
Kreisonderhlfasschuf: 4
Köln, Riehler Pl. 2, 5000 Köln 41: 4
Kreissozialamt Landkreis Grafschaft Goya: 4
Claims Conference: 4
Deutscher: 4
Einst. Behörde Köln: 4
United Restitution Office, Frankfurt am Main, Gruneburgweg 119: 4
Schw. Landesamt: 4
Der Niedersächsische Minister des Innern Hannover: 4
KreisaußerordentlicherHilfsausschuss: 4
Israel: 4
Doppelmeldung nicht erforderlich, Akte wurde von Bayern überstellt.: 4
Kreissozialhilfsschule Osnabrück-Stadt: 4
Haupt: 4
BMT: 4
Deutschland: 4
LVA Dörf: 4
Bayerisches Verfolgtenmuseum: 4
Bayerisches Landesamt für staatsbürgerliche Angelegenheiten: 4
Landesbeauftragte für die Opfer des Nationalsozialismus: 4
Kreis Nordhorn: 4
Landeszentrale für die Vergütung nationalsozialistischer Opfer: 4
Kurzstelle: 4
Neuendettelsau: 4
Koblenz - BV-Abteilung: 3
Bundesverwaltungsgericht: 3
Stadtverwaltung Bielefeld: 3
Nds. Minister des Innern: 3
Magistrat der Stadt München: 3
Doppelverteilung: 3
Doppelmeßlung: 3
Kreissozialamt Blankenburg (Brit. Zone) Braunschweig: 3
Aurich I. Ostfriesl.: 3
Bureau De Restitution: 3
HNO: 3
Dortmunder: 3
RA. United Restitution Office, Frankfurt/M.: 3
O. Staatsanw. Köln: 3
Kalm: 3
Köln, Riehlker Pl. 2, 5000 Köln 1: 3
N81m: 3
Bundeskartotek: 3
Higher Commissioner for Refugees: 3
Köln, Reichler Pl. 2, 5000 Köln 1: 3
Ausg.Amt Bremen: 3
Südwestdeutsche: 3
Doppelvermögens: 3
Hohes Kommisariat der Vereinigten Nationen für Flüchtlinge: 3
Hauptzuständigkeit: 3
LG Bochum: 3
HAn: 3
oln: 3
K61d: 3
United Restitution Office, Frankfurt/M, Gruneburgweg 119: 3
Schauemburg-Lippe: 3
Landkreis Goslar: 3
Kurierstelle: 3
BMFT: 3
K 5 In: 3
Landesamt für Verfolgungsgeschädigte: 3
Fuß: 3
Bundeskriegsverwaltung: 3
KSB: 3
Bezirksamt München: 3
KSHA Landkreis Lüneburg: 3
R.A. Adam: 3
51m: 3
Doppelmelung Berlin: 3
Der Reg.-Präs. Detmold Dez.56: 3
KSHA Hamein-Pyrmont: 3
Kreissozialhilfsschule Gifhorn: 3
EK: 3
K&L: 3
Xolm: 3
Wartensleben-Salzgitter: 3
X81n: 3
Doppelmeilung München: 3
Shanghai-Gruppe: 3
Kreisverwaltung -Amt f. Wiedergutmachung- Höxter /Weser: 3

In [208]:
print(f"Max MatchDistance: {lev_matches['MatchDistance'].max()}")

Max MatchDistance: 58.0

In [209]:
total = len(lev_matches)-len(df_matches_impossible)
max_dist = int(lev_matches['MatchDistance'].max()) + 1
for i in range(1, max_dist):
    count = (lev_matches['MatchDistance'] == i).sum()
    pct = count / total * 100    
    print(f'MatchDistance = {i}: {count} ({pct:.2f}%)')

MatchDistance = 1: 17610 (12.09%)
MatchDistance = 2: 10216 (7.01%)
MatchDistance = 3: 9283 (6.37%)
MatchDistance = 4: 7249 (4.98%)
MatchDistance = 5: 25033 (17.18%)
MatchDistance = 6: 7157 (4.91%)
MatchDistance = 7: 5696 (3.91%)
MatchDistance = 8: 23344 (16.03%)
MatchDistance = 9: 5215 (3.58%)
MatchDistance = 10: 3719 (2.55%)
MatchDistance = 11: 5334 (3.66%)
MatchDistance = 12: 2539 (1.74%)
MatchDistance = 13: 3634 (2.49%)
MatchDistance = 14: 3022 (2.07%)
MatchDistance = 15: 2023 (1.39%)
MatchDistance = 16: 2193 (1.51%)
MatchDistance = 17: 2679 (1.84%)
MatchDistance = 18: 2706 (1.86%)
MatchDistance = 19: 1229 (0.84%)
MatchDistance = 20: 1014 (0.70%)
MatchDistance = 21: 1700 (1.17%)
MatchDistance = 22: 362 (0.25%)
MatchDistance = 23: 375 (0.26%)
MatchDistance = 24: 360 (0.25%)
MatchDistance = 25: 477 (0.33%)
MatchDistance = 26: 168 (0.12%)
MatchDistance = 27: 105 (0.07%)
MatchDistance = 28: 294 (0.20%)
MatchDistance = 29: 202 (0.14%)
MatchDistance = 30: 113 (0.08%)
MatchDistance = 31: 55 (0.04%)
MatchDistance = 32: 170 (0.12%)
MatchDistance = 33: 62 (0.04%)
MatchDistance = 34: 65 (0.04%)
MatchDistance = 35: 61 (0.04%)
MatchDistance = 36: 43 (0.03%)
MatchDistance = 37: 17 (0.01%)
MatchDistance = 38: 12 (0.01%)
MatchDistance = 39: 8 (0.01%)
MatchDistance = 40: 14 (0.01%)
MatchDistance = 41: 13 (0.01%)
MatchDistance = 42: 15 (0.01%)
MatchDistance = 43: 12 (0.01%)
MatchDistance = 44: 3 (0.00%)
MatchDistance = 45: 2 (0.00%)
MatchDistance = 46: 3 (0.00%)
MatchDistance = 47: 2 (0.00%)
MatchDistance = 48: 4 (0.00%)
MatchDistance = 49: 21 (0.01%)
MatchDistance = 50: 11 (0.01%)
MatchDistance = 51: 7 (0.00%)
MatchDistance = 52: 8 (0.01%)
MatchDistance = 53: 6 (0.00%)
MatchDistance = 54: 3 (0.00%)
MatchDistance = 55: 0 (0.00%)
MatchDistance = 56: 0 (0.00%)
MatchDistance = 57: 2 (0.00%)
MatchDistance = 58: 2 (0.00%)

In [210]:
df_nomatches = lev_matches[(lev_matches['MatchDistance'] > 0) | (lev_matches['MatchDistance'].isna())]

df_nomatches.sort_values('MatchDistance', ascending=True).to_excel('compensation_office_nomatches.xlsx', index=False)

In [211]:
# build sets of all unique tokens in the ground truth and the extracted office names

def normalize(s):
    if not isinstance(s, str):
        return ""
    s = s.lower()
    replacements = {
        "ä": "ae", "ö": "oe", "ü": "ue", "ß": "ss"
    }
    for k, v in replacements.items():
        s = s.replace(k, v)
    s = unicodedata.normalize("NFKD", s)
    s = re.sub(r'[^a-zA-Z\s]', '', s)
    s = re.sub(r'\s+', ' ', s).strip()
    return s

normalized_csv_token_gt = [normalize(office) for office in gt]
normalized_csv_token_corrections = [normalize(office) for office in list_corrections]
normalized_csv_token_further_corrections = [normalize(office) for office in list_further_corrections]
normalized_json_token_list = [normalize(office) for office in df_unmatched_filtered['CompensationOffice1'].tolist()]
normalized_csv_token_list = normalized_csv_token_gt + normalized_csv_token_corrections + normalized_csv_token_further_corrections

def office_token_set(series):
    tokens = set()
    for name in series:
        tokens.update(token for token in re.findall(r"\b\w+\b", name, flags=re.UNICODE)
            if not token.isdigit())
    return tokens

csv_tokens = office_token_set(normalized_csv_token_list)
json_tokens = office_token_set(normalized_json_token_list)

print(f"csv_tokens: {len(csv_tokens)}")
print(f"json_tokens: {len(json_tokens)}")

csv_tokens: 382
json_tokens: 10502

In [212]:
# map the tokens of the extracted office names to the closest equivalent in the ground truth tokens up to a maximal 
# edit distance of half of each token's length
json_to_csv_closest_map = {}
for json_token in json_tokens:
    if json_token in csv_tokens:
        continue
    
    max_distance = len(json_token) // 2
    best_match = None
    best_dist = float('inf')
    
    for csv_token in csv_tokens:
        if len(csv_token) >= 3:
            if abs(len(csv_token) - len(json_token)) > max_distance:
                continue
            dist = distance(json_token, csv_token)
            if dist <= max_distance and dist < best_dist:
                best_dist = dist
                best_match = csv_token
    
    if best_match is not None:
        json_to_csv_closest_map.setdefault(best_dist, []).append((json_token, best_match))

json_to_csv_closest_map = {
    k: sorted(v, key=lambda x: len(x[0]))
    for k, v in sorted(json_to_csv_closest_map.items())
}

print({k: len(v) for k, v in json_to_csv_closest_map.items()})
json_to_csv_closest_map

{1: 761, 2: 1133, 3: 1259, 4: 1047, 5: 821, 6: 634, 7: 386, 8: 310, 9: 222, 10: 139, 11: 76, 12: 38, 13: 23, 14: 12, 15: 11, 16: 5, 17: 3, 18: 1, 20: 3, 21: 1, 22: 1, 23: 1}

{1: [('rg', 'reg'),
  ('st', 'str'),
  ('ud', 'und'),
  ('re', 'reg'),
  ('ba', 'bad'),
  ('dr', 'der'),
  ('mn', 'min'),
  ('br', 'ibr'),
  ('et', 'etc'),
  ('da', 'das'),
  ('bd', 'bad'),
  ('de', 'die'),
  ('rb', 'lrb'),
  ('eg', 'reg'),
  ('ir', 'ibr'),
  ('di', 'die'),
  ('tr', 'str'),
  ('ne', 'neu'),
  ('es', 'des'),
  ('od', 'ofd'),
  ('lr', 'lrb'),
  ('fd', 'ofd'),
  ('as', 'das'),
  ('sr', 'str'),
  ('mi', 'min'),
  ('ib', 'ibr'),
  ('mt', 'amt'),
  ('of', 'ofd'),
  ('ges', 'des'),
  ('qfd', 'ofd'),
  ('mst', 'ist'),
  ('bes', 'des'),
  ('ung', 'und'),
  ('ksa', 'ksha'),
  ('lro', 'lrb'),
  ('cas', 'das'),
  ('win', 'fin'),
  ('dhe', 'die'),
  ('end', 'und'),
  ('ost', 'ist'),
  ('art', 'abt'),
  ('kst', 'ist'),
  ('efd', 'ofd'),
  ('sta', 'str'),
  ('rea', 'reg'),
  ('dep', 'dez'),
  ('stg', 'str'),
  ('lra', 'lrb'),
  ('ksh', 'ksha'),
  ('dem', 'dez'),
  ('fur', 'fuer'),
  ('beg', 'reg'),
  ('lfd', 'ofd'),
  ('ord', 'ofd'),
  ('mii', 'min'),
  ('ofr', 'ofd'),
  ('dfd', 'ofd'),
  ('nec', 'neu'),
  ('deu', 'neu'),
  ('mid', 'min'),
  ('ber', 'der'),
  ('def', 'dez'),
  ('xin', 'fin'),
  ('ofb', 'ofd'),
  ('mit', 'min'),
  ('ami', 'amt'),
  ('sth', 'str'),
  ('uni', 'und'),
  ('ofg', 'ofd'),
  ('rig', 'reg'),
  ('sin', 'fin'),
  ('new', 'neu'),
  ('hes', 'hess'),
  ('wes', 'des'),
  ('dor', 'der'),
  ('baw', 'bad'),
  ('off', 'ofd'),
  ('hst', 'ist'),
  ('abh', 'abt'),
  ('lad', 'bad'),
  ('brd', 'bad'),
  ('ovd', 'ofd'),
  ('dfr', 'der'),
  ('lre', 'lrb'),
  ('ddr', 'der'),
  ('wie', 'die'),
  ('doz', 'dez'),
  ('ras', 'das'),
  ('kin', 'fin'),
  ('ast', 'abt'),
  ('xes', 'des'),
  ('dad', 'bad'),
  ('stf', 'str'),
  ('bah', 'bad'),
  ('bez', 'dez'),
  ('ver', 'der'),
  ('bmt', 'amt'),
  ('neg', 'reg'),
  ('bam', 'bad'),
  ('wtr', 'str'),
  ('mad', 'bad'),
  ('rog', 'reg'),
  ('ger', 'der'),
  ('lbb', 'lrb'),
  ('deg', 'reg'),
  ('den', 'dez'),
  ('dos', 'das'),
  ('weg', 'reg'),
  ('baf', 'bad'),
  ('oft', 'ofd'),
  ('sha', 'ksha'),
  ('opd', 'ofd'),
  ('lab', 'lrb'),
  ('kad', 'bad'),
  ('keg', 'reg'),
  ('ubt', 'abt'),
  ('rep', 'reg'),
  ('isr', 'ist'),
  ('bav', 'bad'),
  ('det', 'dez'),
  ('din', 'fin'),
  ('rbg', 'reg'),
  ('and', 'und'),
  ('dme', 'die'),
  ('her', 'herr'),
  ('ofs', 'ofd'),
  ('wst', 'ist'),
  ('okd', 'ofd'),
  ('rin', 'fin'),
  ('oed', 'ofd'),
  ('ojd', 'ofd'),
  ('stv', 'str'),
  ('ofo', 'ofd'),
  ('dei', 'dez'),
  ('res', 'reg'),
  ('alt', 'abt'),
  ('stm', 'str'),
  ('ofj', 'ofd'),
  ('pas', 'das'),
  ('hmt', 'amt'),
  ('bie', 'die'),
  ('pin', 'fin'),
  ('bay', 'bad'),
  ('bfd', 'bad'),
  ('dar', 'das'),
  ('vin', 'fin'),
  ('ant', 'abt'),
  ('drs', 'das'),
  ('rey', 'reg'),
  ('bau', 'bad'),
  ('abg', 'abt'),
  ('rad', 'bad'),
  ('dat', 'das'),
  ('hin', 'fin'),
  ('ksho', 'ksha'),
  ('stad', 'stade'),
  ('mess', 'hess'),
  ('palz', 'pfalz'),
  ('kshc', 'ksha'),
  ('wuer', 'fuer'),
  ('west', 'westf'),
  ('mink', 'min'),
  ('tuer', 'fuer'),
  ('amts', 'amt'),
  ('pres', 'praes'),
  ('brak', 'brake'),
  ('eamt', 'amt'),
  ('bona', 'bonn'),
  ('kein', 'keine'),
  ('lecr', 'leer'),
  ('bund', 'und'),
  ('bist', 'ist'),
  ('kshb', 'ksha'),
  ('regv', 'reg'),
  ('baud', 'bad'),
  ('pltz', 'platz'),
  ('herz', 'herr'),
  ('neve', 'neue'),
  ('dezf', 'dez'),
  ('main', 'mainz'),
  ('bsha', 'ksha'),
  ('pflz', 'pfalz'),
  ('inst', 'ist'),
  ('wesf', 'westf'),
  ('neua', 'neu'),
  ('koel', 'kiel'),
  ('trer', 'trier'),
  ('kshm', 'ksha'),
  ('fink', 'fin'),
  ('seer', 'leer'),
  ('kshd', 'ksha'),
  ('bamt', 'amt'),
  ('ampt', 'amt'),
  ('mark', 'markt'),
  ('hund', 'und'),
  ('plaz', 'platz'),
  ('vamt', 'amt'),
  ('maiz', 'mainz'),
  ('breg', 'reg'),
  ('trie', 'trier'),
  ('dess', 'hess'),
  ('tier', 'trier'),
  ('amft', 'amt'),
  ('kshs', 'ksha'),
  ('amth', 'amt'),
  ('aemt', 'amt'),
  ('samt', 'amt'),
  ('koln', 'koeln'),
  ('wist', 'ist'),
  ('huss', 'hess'),
  ('stdt', 'stadt'),
  ('ksia', 'ksha'),
  ('kshv', 'ksha'),
  ('oder', 'der'),
  ('buer', 'fuer'),
  ('ostr', 'str'),
  ('manz', 'mainz'),
  ('kaha', 'ksha'),
  ('neus', 'neu'),
  ('fund', 'und'),
  ('bohn', 'bonn'),
  ('oftd', 'ofd'),
  ('dhdt', 'adhdt'),
  ('amnt', 'amt'),
  ('state', 'stade'),
  ('wesff', 'westf'),
  ('trher', 'trier'),
  ('weste', 'westf'),
  ('pratz', 'platz'),
  ('triel', 'trier'),
  ('meinz', 'mainz'),
  ('ptalz', 'pfalz'),
  ('yelle', 'celle'),
  ('fayer', 'bayer'),
  ('kshaw', 'ksha'),
  ('essen', 'hessen'),
  ('buyer', 'bayer'),
  ('piatz', 'platz'),
  ('bunde', 'bundes'),
  ('ksham', 'ksha'),
  ('mahnz', 'mainz'),
  ('kshao', 'ksha'),
  ('maine', 'mainz'),
  ('westp', 'westf'),
  ('kshae', 'ksha'),
  ('mains', 'mainz'),
  ('lands', 'landes'),
  ('kshag', 'ksha'),
  ('maink', 'mainz'),
  ('wcstf', 'westf'),
  ('trien', 'trier'),
  ('efurt', 'erfurt'),
  ('kshax', 'ksha'),
  ('herrn', 'herr'),
  ('triar', 'trier'),
  ('plitz', 'platz'),
  ('kshah', 'ksha'),
  ('trler', 'trier'),
  ('praef', 'praes'),
  ('boenn', 'bonn'),
  ('glatz', 'platz'),
  ('bayes', 'bayer'),
  ('weltf', 'westf'),
  ('hoess', 'hess'),
  ('mayer', 'bayer'),
  ('boyer', 'bayer'),
  ('westw', 'westf'),
  ('staat', 'stadt'),
  ('neuer', 'neue'),
  ('platt', 'platz'),
  ('colle', 'celle'),
  ('plaiz', 'platz'),
  ('koelz', 'koeln'),
  ('neuen', 'neue'),
  ('kshan', 'ksha'),
  ('blatz', 'platz'),
  ('melle', 'celle'),
  ('wuerf', 'wuert'),
  ('wuerm', 'wuert'),
  ('tries', 'trier'),
  ('neues', 'neue'),
  ('westu', 'westf'),
  ('kshaf', 'ksha'),
  ('freib', 'freie'),
  ('ksaha', 'ksha'),
  ('bayers', 'bayern'),
  ('triern', 'trier'),
  ('grafsh', 'grafsch'),
  ('koelnn', 'koeln'),
  ('wuertt', 'wuert'),
  ('iplatz', 'platz'),
  ('menden', 'minden'),
  ('brakel', 'brake'),
  ('iwestf', 'westf'),
  ('plaatz', 'platz'),
  ('plaetz', 'platz'),
  ('rheinl', 'rhein'),
  ('arburg', 'warburg'),
  ('minder', 'minden'),
  ('maintz', 'mainz'),
  ('linden', 'minden'),
  ('staedt', 'stadt'),
  ('amburg', 'hamburg'),
  ('rpfalz', 'pfalz'),
  ('beglin', 'berlin'),
  ('strass', 'strasse'),
  ('bumdes', 'bundes'),
  ('lindau', 'landau'),
  ('berger', 'buerger'),
  ('fragen', 'frauen'),
  ('einstr', 'weinstr'),
  ('landos', 'landes'),
  ('astadt', 'stadt'),
  ('munden', 'minden'),
  ('koelny', 'koeln'),
  ('bremer', 'bremen'),
  ('aremen', 'bremen'),
  ('hremen', 'bremen'),
  ('neuied', 'neuwied'),
  ('sozial', 'soziale'),
  ('oblenz', 'koblenz'),
  ('jenner', 'jenaer'),
  ('innere', 'innern'),
  ('weinst', 'weinstr'),
  ('tremen', 'bremen'),
  ('bracke', 'brake'),
  ('auvich', 'aurich'),
  ('gerlin', 'berlin'),
  ('weinsr', 'weinstr'),
  ('weimstr', 'weinstr'),
  ('beziege', 'bezuege'),
  ('rishler', 'riehler'),
  ('bayerns', 'bayern'),
  ('neumark', 'neumarkt'),
  ('cattbus', 'cottbus'),
  ('bremmen', 'bremen'),
  ('detmola', 'detmold'),
  ('betmold', 'detmold'),
  ('goeslar', 'goslar'),
  ('hanover', 'hannover'),
  ('barburg', 'warburg'),
  ('koblens', 'koblenz'),
  ('neuried', 'neuwied'),
  ('kassels', 'kassel'),
  ('reiburg', 'freiburg'),
  ('koblinz', 'koblenz'),
  ('harburg', 'warburg'),
  ('kobleuz', 'koblenz'),
  ('bremens', 'bremen'),
  ('arnberg', 'arnsberg'),
  ('munster', 'muenster'),
  ('kassell', 'kassel'),
  ('auriach', 'aurich'),
  ('richler', 'riehler'),
  ('munchen', 'muenchen'),
  ('rastock', 'rostock'),
  ('frauend', 'frauen'),
  ('koblanz', 'koblenz'),
  ('homburg', 'hamburg'),
  ('noblenz', 'koblenz'),
  ('bundesk', 'bundes'),
  ('landesk', 'landes'),
  ('weinsfr', 'weinstr'),
  ('goslari', 'goslar'),
  ('marburg', 'warburg'),
  ('sociale', 'soziale'),
  ('gratsch', 'grafsch'),
  ('sarburg', 'warburg'),
  ('neusadt', 'neustadt'),
  ('rnsberg', 'arnsberg'),
  ('kasselb', 'kassel'),
  ('weisstr', 'weinstr'),
  ('laendes', 'landes'),
  ('wernstr', 'weinstr'),
  ('berlins', 'berlin'),
  ('dinnern', 'innern'),
  ('graisch', 'grafsch'),
  ('finanzer', 'finanzen'),
  ('baarburg', 'saarburg'),
  ('neussadt', 'neustadt'),
  ('neuwiedw', 'neuwied'),
  ('oldeburg', 'oldenburg'),
  ('meustadt', 'neustadt'),
  ('prnsberg', 'arnsberg'),
  ('aunsberg', 'arnsberg'),
  ('freiberg', 'freiburg'),
  ('desernat', 'dezernat'),
  ('grafisch', 'grafsch'),
  ('arnsherg', 'arnsberg'),
  ('arnsoerg', 'arnsberg'),
  ('arosberg', 'arnsberg'),
  ('vkoblenz', 'koblenz'),
  ('finanzan', 'finanzen'),
  ('searburg', 'saarburg'),
  ('vermoege', 'vermoegen'),
  ('arnoberg', 'arnsberg'),
  ('finanzon', 'finanzen'),
  ('andesamt', 'landesamt'),
  ('mannover', 'hannover'),
  ('arneberg', 'arnsberg'),
  ('koblensz', 'koblenz'),
  ('koblentz', 'koblenz'),
  ('nenstadt', 'neustadt'),
  ('neuwiedt', 'neuwied'),
  ('weinsstr', 'weinstr'),
  ('aensberg', 'arnsberg'),
  ('graftsch', 'grafsch'),
  ('karlruhe', 'karlsruhe'),
  ('wartburg', 'warburg'),
  ('arnswerg', 'arnsberg'),
  ('armsberg', 'arnsberg'),
  ('karsruhe', 'karlsruhe'),
  ('lezernat', 'dezernat'),
  ('riehlner', 'riehler'),
  ('helstedt', 'helmstedt'),
  ('riehlker', 'riehler'),
  ('degernat', 'dezernat'),
  ('arnaberg', 'arnsberg'),
  ('chamnitz', 'chemnitz'),
  ('osterode', 'osterodeh'),
  ('bielfeld', 'bielefeld'),
  ('darstadt', 'darmstadt'),
  ('frnsberg', 'arnsberg'),
  ('beustadt', 'neustadt'),
  ('kalsruhe', 'karlsruhe'),
  ('oltenburg', 'oldenburg'),
  ('detzernat', 'dezernat'),
  ('aernsberg', 'arnsberg'),
  ('aegierung', 'regierung'),
  ('bezirksam', 'bezirksamt'),
  ('ministers', 'minister'),
  ('nordboden', 'nordbaden'),
  ('arnssberg', 'arnsberg'),
  ('farnsberg', 'arnsberg'),
  ('behoerden', 'behoerde'),
  ('manistrat', 'magistrat'),
  ('neustadtv', 'neustadtw'),
  ('rogierung', 'regierung'),
  ('hannoverl', 'hannover'),
  ('vormoegen', 'vermoegen'),
  ('mdweinstr', 'adweinstr'),
  ('harnsberg', 'arnsberg'),
  ('vbehoerde', 'behoerde'),
  ('ibreisgau', 'breisgau'),
  ('veraltete', 'verwaltete'),
  ('cldenburg', 'oldenburg'),
  ('hiesbaden', 'wiesbaden'),
  ('maristrat', 'magistrat'),
  ('schauburg', 'schaumburg'),
  ('verwaltet', 'verwaltete'),
  ('neustadtb', 'neustadtw'),
  ('meustadtw', 'neustadtw'),
  ('wienbaden', 'wiesbaden'),
  ('derzernat', 'dezernat'),
  ('behoerdet', 'behoerde'),
  ('niesbaden', 'wiesbaden'),
  ('weinsteig', 'weinsteige'),
  ('stuttgard', 'stuttgart'),
  ('hannovera', 'hannover'),
  ('ahrnsberg', 'arnsberg'),
  ('arnstberg', 'arnsberg'),
  ('franzfurt', 'frankfurt'),
  ('hessische', 'hessisches'),
  ('nordbuden', 'nordbaden'),
  ('bayersche', 'bayerische'),
  ('arnnsberg', 'arnsberg'),
  ('tdezernat', 'dezernat'),
  ('president', 'praesident'),
  ('karlshuhe', 'karlsruhe'),
  ('arnswberg', 'arnsberg'),
  ('muenchens', 'muenchen'),
  ('vermoeger', 'vermoegen'),
  ('regierang', 'regierung'),
  ('bezirkamt', 'bezirksamt'),
  ('finanzsen', 'finanzen'),
  ('ebehoerde', 'behoerde'),
  ('toebingen', 'tuebingen'),
  ('finanzzen', 'finanzen'),
  ('spinkenhof', 'sprinkenhof'),
  ('mayerische', 'bayerische'),
  ('vorwaltete', 'verwaltete'),
  ('bildesheim', 'hildesheim'),
  ('pflzberlin', 'pfalzberlin'),
  ('landesamts', 'landesamt'),
  ('karlsruher', 'karlsruhe'),
  ('verfolgter', 'verfolgte'),
  ('landsesamt', 'landesamt'),
  ('sildesheim', 'hildesheim'),
  ('landeesamt', 'landesamt'),
  ('verwaltets', 'verwaltete'),
  ('laendesamt', 'landesamt'),
  ('vermoegens', 'vermoegen'),
  ('frankfurtn', 'frankfurtm'),
  ('karlshruhe', 'karlsruhe'),
  ('bayrisches', 'bayerisches'),
  ('braesident', 'praesident'),
  ('ministerie', 'ministerin'),
  ('bazirksamt', 'bezirksamt'),
  ('bayesische', 'bayerische'),
  ('bayedische', 'bayerische'),
  ('bexirksamt', 'bezirksamt'),
  ('sayerische', 'bayerische'),
  ('verfolgten', 'verfolgte'),
  ('bundesamts', 'bundesamt'),
  ('dezirksamt', 'bezirksamt'),
  ('osterodehz', 'osterodeh'),
  ('vrwbezirks', 'verwbezirks'),
  ('lezirksamt', 'bezirksamt'),
  ('praesidenc', 'praesident'),
  ('neustadtwv', 'neustadtw'),
  ('rabteilung', 'abteilung'),
  ('verwbeirks', 'verwbezirks'),
  ('bayetische', 'bayerische'),
  ('verwalteta', 'verwaltete'),
  ('bekirksamt', 'bezirksamt'),
  ('palzberlin', 'pfalzberlin'),
  ('dusseldorf', 'duesseldorf'),
  ('verfolgtes', 'verfolgte'),
  ('neustadtew', 'neustadtw'),
  ('praesidenz', 'praesident'),
  ('kaerlsruhe', 'karlsruhe'),
  ('helmsstedt', 'helmstedt'),
  ('alstaedter', 'altstaedter'),
  ('verwalteto', 'verwaltete'),
  ('karlsruhes', 'karlsruhe'),
  ('payerische', 'bayerische'),
  ('freiburgdr', 'freiburgbr'),
  ('hikdesheim', 'hildesheim'),
  ('hussisches', 'hessisches'),
  ('regierungs', 'regierung'),
  ('gildesheim', 'hildesheim'),
  ('bayersches', 'bayerisches'),
  ('desseldorf', 'duesseldorf'),
  ('vewbezirks', 'verwbezirks'),
  ('bayerischer', 'bayerische'),
  ('bayerischen', 'bayerische'),
  ('vorwbezirks', 'verwbezirks'),
  ('bezirksamts', 'bezirksamt'),
  ('frankfurtmp', 'frankfurtm'),
  ('sarbruecken', 'saarbruecken'),
  ('springenhof', 'sprinkenhof'),
  ('sprenkenhof', 'sprinkenhof'),
  ('schnaumburg', 'schaumburg'),
  ('schauumburg', 'schaumburg'),
  ('gpraesident', 'praesident'),
  ('auerstrasse', 'auestrasse'),
  ('versbezirks', 'verwbezirks'),
  ('ministerien', 'ministerin'),
  ('nayerisches', 'bayerisches'),
  ('varwbezirks', 'verwbezirks'),
  ('verwaltetes', 'verwaltete'),
  ('schauemburg', 'schaumburg'),
  ('schlaumburg', 'schaumburg'),
  ('frankfurtma', 'frankfurtm'),
  ('weilstrasse', 'weinstrasse'),
  ('frankfurtam', 'frankfurtm'),
  ('bayernsches', 'bayerisches'),
  ('beezirksamt', 'bezirksamt'),
  ('osnaubrueck', 'osnabrueck'),
  ('payerisches', 'bayerisches'),
  ('benzirksamt', 'bezirksamt'),
  ('spraesident', 'praesident'),
  ('verwalteter', 'verwaltete'),
  ('werwbezirks', 'verwbezirks'),
  ('rayerisches', 'bayerisches'),
  ('xpraesident', 'praesident'),
  ('bezirkssamt', 'bezirksamt'),
  ('osanabrueck', 'osnabrueck'),
  ('muesseldorf', 'duesseldorf'),
  ('verwaltgete', 'verwaltete'),
  ('obezirksamt', 'bezirksamt'),
  ('yerwbezirks', 'verwbezirks'),
  ('hildesheimm', 'hildesheim'),
  ('vermbezirks', 'verwbezirks'),
  ('schaeumburg', 'schaumburg'),
  ('noerdlicher', 'noerdliche'),
  ('merwbezirks', 'verwbezirks'),
  ('verwbekirks', 'verwbezirks'),
  ('verwbezirke', 'verwbezirks'),
  ('bayernische', 'bayerische'),
  ('zustaendige', 'zustaendig'),
  ('verwalteten', 'verwaltete'),
  ('arcistrasse', 'arcisstrasse'),
  ('rpfalzberlin', 'pfalzberlin'),
  ('nshaetefonds', 'nshaertefonds'),
  ('kontrolliert', 'kontrollierte'),
  ('dlandkreises', 'landkreises'),
  ('verwxbezirks', 'verwbezirks'),
  ('regpraesidet', 'regpraesident'),
  ('regpresident', 'regpraesident'),
  ('nshaertfonds', 'nshaertefonds'),
  ('hannoverlind', 'hannoverland'),
  ('verwbezirksm', 'verwbezirks'),
  ('ministeriums', 'ministerium'),
  ('verwbezirksk', 'verwbezirks'),
  ('verwbezirkes', 'verwbezirks'),
  ('verwbezirksx', 'verwbezirks'),
  ('regpraesidnt', 'regpraesident'),
  ('bremenohaven', 'bremenhaven'),
  ('meisestrasse', 'meiserstrasse'),
  ('regprasident', 'regpraesident'),
  ('weinsstrasse', 'weinstrasse'),
  ('vertriebenen', 'vertriebene'),
  ('bayernisches', 'bayerisches'),
  ('verswbezirks', 'verwbezirks'),
  ('regpraesidenz', 'regpraesident'),
  ('bundesarchivs', 'bundesarchiv'),
  ('aussensstelle', 'aussenstelle'),
  ('bundesarchive', 'bundesarchiv'),
  ('rheindorfersr', 'rheindorferstr'),
  ('landesarchivs', 'landesarchiv'),
  ('rogierungsamt', 'regierungsamt'),
  ('zentralkartei', 'centralkartei'),
  ('baundesarchiv', 'bundesarchiv'),
  ('ausssenstelle', 'aussenstelle'),
  ('begpraesident', 'regpraesident'),
  ('rugpraesident', 'regpraesident'),
  ('refpraesidium', 'regpraesidium'),
  ('bahnhoofplatz', 'bahnhofplatz'),
  ('begierungsamt', 'regierungsamt'),
  ('landesarchive', 'landesarchiv'),
  ('verfolgtenamts', 'verfolgtenamt'),
  ('regierungsaemt', 'regierungsamt'),
  ('kontrolliertes', 'kontrollierte'),
  ('kheinlandpfalz', 'rheinlandpfalz'),
  ('regpraesidient', 'regpraesident'),
  ('staufenbergstr', 'stauffenbergstr'),
  ('kontrollierter', 'kontrollierte'),
  ('meisserstrasse', 'meiserstrasse'),
  ('regpraesidenta', 'regpraesident'),
  ('innernminister', 'innenminister'),
  ('rheindorfersstr', 'rheindorferstr'),
  ('pelfkantkreises', 'selfkantkreises'),
  ('wedergutmachung', 'wiedergutmachung'),
  ('iedergutmachung', 'wiedergutmachung'),
  ('hegierungsbezirk', 'regierungsbezirk'),
  ('staatministerium', 'staatsministerium'),
  ('regierungsdezirk', 'regierungsbezirk'),
  ('wienergutmachung', 'wiedergutmachung'),
  ('ragierungsbezirk', 'regierungsbezirk'),
  ('kegierungsbezirk', 'regierungsbezirk'),
  ('goetttingenstadt', 'goettingenstadt'),
  ('wiadergutmachung', 'wiedergutmachung'),
  ('rogierungsbezirk', 'regierungsbezirk'),
  ('regierungsbesirk', 'regierungsbezirk'),
  ('goettlingenstadt', 'goettingenstadt'),
  ('versorgungstelle', 'versorgungsstelle'),
  ('niedersaechsische', 'niedersaechsisches'),
  ('pundesministerium', 'bundesministerium'),
  ('aurichstfriesland', 'aurichostfriesland'),
  ('verwaltungsbezirk', 'verwaltungsbezirks'),
  ('mundesministerium', 'bundesministerium'),
  ('wiedergutmachungs', 'wiedergutmachung'),
  ('rundesministerium', 'bundesministerium'),
  ('fwiedergutmachung', 'wiedergutmachung'),
  ('nundesministerium', 'bundesministerium'),
  ('regierungsbezirks', 'regierungsbezirk'),
  ('wiedergutmachtung', 'wiedergutmachung'),
  ('hundesministerium', 'bundesministerium'),
  ('zentralregistatur', 'zentralregistratur'),
  ('bundesministeriums', 'bundesministerium'),
  ('staatsministeriums', 'staatsministerium'),
  ('aurichoatfriesland', 'aurichostfriesland'),
  ('verwaltungsbezirke', 'verwaltungsbezirks'),
  ('nordrheinwestfales', 'nordrheinwestfalen'),
  ('justizministeriums', 'justizministerium'),
  ('niedersaechsischer', 'niedersaechsisches'),
  ('oberstaedtdirektor', 'oberstadtdirektor'),
  ('niedersaechsischen', 'niedersaechsisches'),
  ('landesbeirksstelle', 'landesbezirksstelle'),
  ('vermogensverwaltung', 'vermoegensverwaltung'),
  ('regerungspraesident', 'regierungspraesident'),
  ('egierungspraesident', 'regierungspraesident'),
  ('regierungspraesidet', 'regierungspraesident'),
  ('landesbozirksstelle', 'landesbezirksstelle'),
  ('regierungsprasidium', 'regierungspraesidium'),
  ('landeshezirksstelle', 'landesbezirksstelle'),
  ('verwaltungsbezirksm', 'verwaltungsbezirks'),
  ('entschaedigungssamt', 'entschaedigungsamt'),
  ('regierungsbezirksam', 'regierungsbezirksamt'),
  ('verwaltungsbezirkes', 'verwaltungsbezirks'),
  ('regierungsbezirkamt', 'regierungsbezirksamt'),
  ('landsverwaltungsamt', 'landesverwaltungsamt'),
  ('verwaltungsbezirksx', 'verwaltungsbezirks'),
  ('regierungbezirksamt', 'regierungsbezirksamt'),
  ('wiedergutmachungamt', 'wiedergutmachungsamt'),
  ('ragierungsbezirksamt', 'regierungsbezirksamt'),
  ('begierungspraesident', 'regierungspraesident'),
  ('regierungspraefident', 'regierungspraesident'),
  ('landesentschaedigung', 'landesentschaedigungs'),
  ('regierungsbezirkspmt', 'regierungsbezirksamt'),
  ('rogierungspraesidium', 'regierungspraesidium'),
  ('regierungsbesirksamt', 'regierungsbezirksamt'),
  ('rogierungsbezirksamt', 'regierungsbezirksamt'),
  ('negierungspraesident', 'regierungspraesident'),
  ('regierungsdezirksamt', 'regierungsbezirksamt'),
  ('hegierungsbezirksamt', 'regierungsbezirksamt'),
  ('kegierungsbezirksamt', 'regierungsbezirksamt'),
  ('negierungsbezirksamt', 'regierungsbezirksamt'),
  ('regierungsbezirksnmt', 'regierungsbezirksamt'),
  ('regierungsbezirksoamt', 'regierungsbezirksamt'),
  ('regierungspraesidient', 'regierungspraesident'),
  ('regierungsbezirkscamt', 'regierungsbezirksamt'),
  ('regierungsbezirkskamt', 'regierungsbezirksamt'),
  ('landesverwaltungsamts', 'landesverwaltungsamt'),
  ('regierungsbezirksamtx', 'regierungsbezirksamt'),
  ('regierungsbezirksamti', 'regierungsbezirksamt'),
  ('regierungsbezirksammt', 'regierungsbezirksamt'),
  ('wiedergutmachungssamt', 'wiedergutmachungsamt'),
  ('wiedergutmachungsaamt', 'wiedergutmachungsamt'),
  ('regierungsbezirksamts', 'regierungsbezirksamt'),
  ('regierungsbezirksgamt', 'regierungsbezirksamt'),
  ('laendesverwaltungsamt', 'landesverwaltungsamt'),
  ('raegierungsbezirksamt', 'regierungsbezirksamt'),
  ('regierungspraesidente', 'regierungspraesident'),

In [213]:
tokens_to_replace = []
tokens_to_replace.extend(json_to_csv_closest_map[1])
tokens_to_replace.extend(json_to_csv_closest_map[2])
tokens_to_replace.extend(json_to_csv_closest_map[3])
tokens_to_replace.remove(('main', 'mainz'))
tokens_to_replace.remove(('essen', 'hessen'))

In [214]:
unique_distance1_token_map = {
    json_token: csv_candidates
    for json_token, csv_candidates in tokens_to_replace
}

def replace_unique_distance1_tokens(text):
    text = "" if pd.isna(text) else str(text)
    return re.sub(
        r"\b\w+\b",
        lambda match: unique_distance1_token_map.get(match.group(0).lower(), match.group(0)),
        text,
        flags=re.UNICODE
    )

df_unmatched_filtered['CompensationOffice_token_swap'] = df_unmatched_filtered['CompensationOffice1'].apply(normalize).apply(replace_unique_distance1_tokens)

print(f"Unique token replacements available: {len(unique_distance1_token_map)}")

results = df_unmatched_filtered['CompensationOffice_token_swap'].apply(get_min_distance_dynamic_normalized)
df_matches_token_swap = pd.DataFrame({
    'CompensationOffice1': df_unmatched_filtered['CompensationOffice1'],
    'MatchedOffice': results.apply(lambda x: x[1]),
    'MatchDistance': results.apply(lambda x: x[0])
})

df_matches_token_swap.head(20)

Unique token replacements available: 3151

,CompensationOffice1,MatchedOffice,MatchDistance
7,Amt für Wiedergutmachung des Selbstkantkreises...,amtfuerwiedergutmachungdesselfkantkreisesgeile...,9.0
51,Kreisaußerhelfsausschübe,NaN,NaN
55,Der Innernister des Landes Nordrhein-Westfalen...,derinnenministerdeslandesnordrheinwestfalenabt...,6.0
72,Kreissonderhilfsschübe Peine,kreissonderhilfsausschussdelmenhorst,14.0
84,Regierungsbezirksamt für Wiedergutmachung und ...,regierungsbezirksamtfuerwiedergutmachungundver...,13.0
108,Bayerische Kartei,NaN,NaN
111,Entschädigungsamt,entschaedigungsamtberlin,6.0
113,Kreissonderhilfsausschuss Springe,kreissonderhilfsausschussdelmenhorst,10.0
115,Der Regierungspräsident - Dez. 14 - in Detmold,derregierungspraesidentindetmold,7.0
122,Bayerische Kartei,NaN,NaN
145,Landesentschädigungsausschuss,blandesentschaedigungsamt,9.0
190,Bayerisches Landesamt für digungssam,bayerischeslandesentschaedigungsamt,11.0
192,Regierungsbezirkamt für Wiedergutmachung,saarburgbezirksamtfuerwiedergutmachung,10.0
222,Regierungsbezirksamt für Wiedergutmachung und ...,regierungsbezirksamtfuerwiedergutmachungundver...,16.0
255,Bayerische Kartei,NaN,NaN
279,Kreissozialhilfsausschuss des Landkreises Gött...,kreissonderhilfsausschussdeslandkreisesgrafsch...,16.0
302,Regierungsbezirkstelle für Wiedergutmachung un...,regierungsbezirksamtfuerwiedergutmachungundver...,13.0
312,"United Restitution Office, Frankfurt/Main, Grü...",NaN,NaN
332,Kreissozialhilfsausschuss Land Hadeln,kreissonderhilfsausschussdelmenhorst,15.0
343,Entscheidungsbehörde,entschaedigungsbehoerdekoeln,8.0

In [215]:
df_matches_token_swap[df_matches_token_swap['MatchDistance'] == 0]

        CompensationOffice1     MatchedOffice  MatchDistance
3519         Oldenburg/Old.         oldenburg            0.0
15458              Augsburg          arnsberg            0.0
20453     Begirussregierung  bezirksregierung            0.0
20946      Bekirskregierung  bezirksregierung            0.0
29889            Güldesheim        hildesheim            0.0
...                     ...               ...            ...
1885167          BfA-Berlin            berlin            0.0
1886447            Brauburg          freiburg            0.0
1888409          BFA-Berlin            berlin            0.0
1894003           Secerburg          saarburg            0.0
1900241              Dachau            aachen            0.0

[537 rows x 3 columns]

In [216]:
df_matches_token_swap[df_matches_token_swap['MatchDistance'].isin([1, 2])]

,CompensationOffice1,MatchedOffice,MatchDistance
1680,BayHues,bayern,1.0
3753,Regierung Arnswerg (Welf.),regierungarnsbergwestf,2.0
3920,Regierung Arnberg (Welf.),regierungarnsbergwestf,2.0
4507,Bayerisches Landesentschädigungsgesamt,bayerischeslandesentschaedigungsamt,1.0
7022,Regierungsamt Arnsherg (Welf.),regierungsamtarnsbergwestf,2.0
...,...,...,...
1895020,R.Pfz.-Berlin,rhpfalzberlin,2.0
1896680,Regierung Prensborg (Westf.),regierungarnsbergwestf,2.0
1896688,Bundesentschädigungssamt,blandesentschaedigungsamt,1.0
1897298,Regierung Finnsberg (Welf.),regierungarnsbergwestf,2.0
1898588,Regierung Arnswerg (Welf.),regierungarnsbergwestf,2.0

In [217]:
df_matches_token_swap[df_matches_token_swap['MatchDistance'].isin([1, 2])]

,CompensationOffice1,MatchedOffice,MatchDistance
1680,BayHues,bayern,1.0
3753,Regierung Arnswerg (Welf.),regierungarnsbergwestf,2.0
3920,Regierung Arnberg (Welf.),regierungarnsbergwestf,2.0
4507,Bayerisches Landesentschädigungsgesamt,bayerischeslandesentschaedigungsamt,1.0
7022,Regierungsamt Arnsherg (Welf.),regierungsamtarnsbergwestf,2.0
...,...,...,...
1895020,R.Pfz.-Berlin,rhpfalzberlin,2.0
1896680,Regierung Prensborg (Westf.),regierungarnsbergwestf,2.0
1896688,Bundesentschädigungssamt,blandesentschaedigungsamt,1.0
1897298,Regierung Finnsberg (Welf.),regierungarnsbergwestf,2.0
1898588,Regierung Arnswerg (Welf.),regierungarnsbergwestf,2.0