In [3]:
import pandas as pd
from Levenshtein import distance
import numpy as np
import re
import unicodedata

In [4]:
#read the Compensation Office csv file into a dataframe
df_csv = pd.read_excel('/home/Benha/Projects/Arbeit/FIZ/compensation-office-analysis/data_new/2025_06_03_Liste der Entschädigungsämter mit Adressen, Varianten, Normalisierungen und Archiven.xlsx')
df_csv.sample(20)

,Layout class,Filename,Bundesland,Transkription Compensation Office,Normalisierung Compensation Office1,Normalisierung Compensation Office2,Zuständiges Archiv,Zuständiges Archiv - GND-Nummer,Unnamed: 8
350,offizielle Bezeichnungen und Adressen,NaN,Bayern,Landesamt für Finanzen – Dienststelle München ...,NaN,NaN,Bayerisches Hauptstaatsarchiv,2005486-5,NaN
46,BY-HB-Frühe Phase,1998_09_22_1_0,Bremen,Landesamt für Wiedergutmachung\nBremen\n-Entsc...,"Landesamt für Wiedergutmachung Bremen, Entschä...",NaN,Staatsarchiv Bremen,2022524-6,NaN
44,BY-eigener-Typ (abweichend 1),1905_01_04_110_0,Bayern,Bayerisches\nLandesentschädigungsamt\nMünchen ...,Bayerisches Landesentschädigungsamt München,NaN,Bayerisches Hauptstaatsarchiv,2005486-5,NaN
45,BY-HB-Frühe Phase,1907_09_13_8_0,Bremen,Amt\nfür Wiedergutmachung\nBremen,Amt für Wiedergutmachung Bremen,NaN,Staatsarchiv Bremen,2022524-6,NaN
88,HH-NI-NRW-SH-Hauptphase,1882_10_18_19_0,Nordrhein-Westfalen,Der Oberkreisdirektor \n- Amt für Wiedergutmac...,"Der Oberkreisdirektor, Amt für Wiedergutmachun...",NaN,Landesarchiv Nordrhein-Westfalen,10094504-1,NaN
9,ABC-Karten,1908_05_06_16_0,Niedersachsen,Kreissonderhilfsausschuß\nLeer/Ostfrld.,Kreissonderhilfsausschuss Leer/Ostfriesland,NaN,Niedersächsisches Landesarchiv,6510041-4,NaN
148,NRW-LRB,1914_00_00_177_0,Nordrhein-Westfalen,Bezirksregierung,Bezirksregierung,NaN,Landesarchiv Nordrhein-Westfalen,10094504-1,NaN
431,Tabellen-Typ (abweichend),1956_10_05_1_0,Bund,"Oberfinanzdirektion Köln: Riehler Platz 2, 506...",Oberfinanzdirektion Köln,NaN,Bundesarchiv (Koblenz),39454-3,bis 2021 (Adresse)
372,RLP-Frühe-Phase,1903_01_07_73_0,Rheinland-Pfalz,Amt\nfür Wiedergutmachung\nund kontrollierte V...,Amt \nfür Wiedergutmachung und kontrollierte V...,NaN,Landesarchivverwaltung Rheinland-Pfalz,2029741-5,NaN
142,NRW-Frühe-Phase,1902_03_15_10_0,Nordrhein-Westfalen,Nordrhein-Westfalen,Nordrhein-Westfalen,NaN,Landesarchiv Nordrhein-Westfalen,10094504-1,NaN
174,offizielle Bezeichnungen und Adressen,NaN,Schleswig-Holstein,"Ministerium für Soziales, Gesundheit, Jugend, ...",NaN,NaN,Landesarchiv Schleswig-Holstein,2017048-8,NaN
212,offizielle Bezeichnungen und Adressen,NaN,Rheinland-Pfalz,Bezirksamt für Wiedergutmachung Koblenz,NaN,NaN,Amt für Wiedergutmachung Saarburg,1354917804,NaN
264,offizielle Bezeichnungen und Adressen,NaN,Nordrhein-Westfalen,Regierungspräsident Arnsberg,NaN,NaN,Landesarchiv Nordrhein-Westfalen,10094504-1,NaN
356,offizielle Bezeichnungen und Adressen,NaN,Baden-Württemberg,Landesamt für die Wiedergutmachung Baden-Württ...,NaN,NaN,Landesarchiv Baden-Württemberg,10107080-9,NaN
354,offizielle Bezeichnungen und Adressen,NaN,Baden-Württemberg,Justizministerium Abt. IV Wiedergutmachung\nLa...,NaN,NaN,Landesarchiv Baden-Württemberg,10107080-9,NaN
315,offizielle Bezeichnungen und Adressen,NaN,Hamburg,"Behörde für Arbeit, Gesunheit und Soziales - ...",NaN,NaN,Staatsarchiv (Hamburg),2022556-8,NaN
94,HH-NI-NRW-SH-Hauptphase,1852_05_07_1_0,Nordrhein-Westfalen,Der Regierungspräsident in Detmold,Der Regierungspräsident Detmold,NaN,Landesarchiv Nordrhein-Westfalen,10094504-1,NaN
275,offizielle Bezeichnungen und Adressen,NaN,Niedersachsen,Der Regierungspräsident in Hannover,NaN,NaN,Niedersächsisches Landesarchiv,6510041-4,NaN
33,BW-Hauptphase,1921_08_15_107_0,Baden-Württemberg,Landesamt für die Wiedergutmachung\nBaden-Würt...,Landesamt für die Wiedergutmachung Baden-Württ...,NaN,Landesarchiv Baden-Württemberg,10107080-9,NaN
414,Tabellen-Typ,1949_09_11_1_0,Nordrhein-Westfalen,Landesrentenbehörde\nNordrhein-Westfalen,Landesrentenbehörde Nordrhein-Westfalen,NaN,Landesarchiv Nordrhein-Westfalen,10094504-1,NaN

In [5]:
#creaae a list of unique compensation offices from the csv file
gt = df_csv['Transkription Compensation Office '].unique().tolist()
print("Number of unique compensation offices: ", len(gt))

Number of unique compensation offices:  428

In [6]:
#read the sliced extracted data jsonl file into a dataframe
df_json = pd.read_json('compoff_extracted.jsonl', lines=True)
df_json.sample(20)

,CompensationOffice1,BZKNr,filename
572243,Hannover,61162,1928_12_16_54_0.jpg
187526,NIEDERSACHSEN,223 490 d,1922_01_29_62_0.jpg
1078256,NaN,220 087,1888_04_07_19_0.jpg
1647189,Entschädigungsamt Berlin,74 798,1913_06_19_31_0.jpg
358976,Hamburg,28683,1918_06_12_43_0.jpg
1059858,Köln,651 276,1880_12_01_15_0.jpg
560759,Entschädigungsamt Berlin,305 958,1928_01_08_42_0.jpg
407028,Bayerisches Landesentschädigungsamt,12232,1891_09_27_15_0.jpg
1310014,Entschädigungsamt Berlin,17 105,1877_07_22_5_0.jpg
1697876,Der Regierungspräsident Düsseldorf,198 959,1919_12_26_2_0.jpg
313360,Arnsberg,58 646 a,1920_05_29_51_0.jpg
968860,NaN,83022/VII/24990,1883_06_05_27_0.jpg
568809,Entschädigungsamt Berlin,4 121,1928_08_25_22_0.jpg
1155952,Bezirksamt für Wiedergutmachung MAINZ,277 384,1914_03_13_103_0.jpg
1685849,Bezirksamt für Wiedergutmachung TRIER,809 369,1919_01_30_56_0.jpg
1134383,Landesentschädigungsamt Schleswig-Holstein in ...,W. 659,1886_06_29_25_0.jpg
823445,Freie und Hansestadt Hamburg Sozialbehörde Amt...,080423,1923_04_08_79_0.jpg
548597,Reg.-Präsident Hildesheim,232 835,1915_04_10_14_0.jpg
581912,Köln,431 286,1926_09_29_63_0.jpg
1260394,Saarburg,470301,1935_09_29_11_0.jpg

In [7]:
#create a dataframe with the entries that have a non-null value in the CompensationOffice1 column
print("Number of cards: ",len(df_json))
mask_not_null = df_json['CompensationOffice1'].notna()
print(f'Number of non-null entries: {mask_not_null.sum()}')

Number of cards:  1901284
Number of non-null entries: 1825946

In [46]:
#create a function to normalise the compensation office names by removing punctuation and whitespace, converting to lowercase and replacing umlauts with their equivalent

#def normalise(word):
#    return re.sub(r'\s+', ' ', str(word)).strip().lower()
def normalize(s):
    if not isinstance(s, str):
        return ""
    
    s = s.lower()

    # Normalize umlauts and ß
    replacements = {
        "ä": "ae", "ö": "oe", "ü": "ue", "ß": "ss"
    }
    for k, v in replacements.items():
        s = s.replace(k, v)
    
    # Normalize unicode (just in case)
    s = unicodedata.normalize("NFKD", s)
    
    # Remove punctuation and whitespace
    s = re.sub(r'[\W_]+', '', s)
        
    return s

gt_normalized = [normalize(office) for office in gt]

In [9]:
#create a mask for the entries in the json dataframe that match any of the normalized compensation office names in the gt list
mask_matched_0 = df_json['CompensationOffice1'].apply(normalize).isin(gt_normalized)
print(f'Number of matches: {mask_matched_0.sum()}')

df_unmatched = df_json[mask_not_null & ~mask_matched_0]
print(f'Number of unmatched entries: {len(df_unmatched)}')

Number of matches: 1494694
Number of unmatched entries: 331252

In [10]:
#print the unique values in the CompensationOffice1 column of the unmatched dataframe and their counts
print(len(df_unmatched['CompensationOffice1'].unique().tolist()))
df_unmatched['CompensationOffice1'].value_counts()

27629

CompensationOffice1
Bezirksamt für Wiedergutmachung Köln                                   32785
Hess. Staatsministerium                                                29978
Freie und Hansestadt Hamburg Sozialbehörde Amt für Wiedergutmachung    16429
Landesamt für die Wiedergutmachung                                     14641
Hansestadt Hamburg, Sozialbehörde, Amt für Wiedergutmachung            11836
                                                                       ...
Regierung Aachen (Welt.)                                                   1
Regierungspräsident Arasberg                                               1
Kreisssonderhilfsausschuss des Landkreises Garsch. Schlaumburg             1
Bayerisches Landesamt für den Regierungsbezirk München                     1
Reg.-Präsident /Präsident des Vereinsbezirks Hannover                      1
Name: count, Length: 27629, dtype: int64

In [51]:
#create a list of manually corrected compensation office names that are not in the gt list but are in the json dataframe and normalise them
list_corrections = ["Bezirksamt für Wiedergutmachung Köln", "Hess. Staatsministerium", "Freie und Hansestadt Hamburg Sozialbehörde Amt für Wiedergutmachung", "Hansestadt Hamburg, Sozialbehörde, Amt für Wiedergutmachung", 
                    "Der Innenminister des Landes Nordrhein-Westfalen", "Landesamt für die Wiedergutmachung Baden-Württemberg", "Oberfinanzdirektion Niedersachsen", "Statistisches Landesamt Nordrhein-Westfalen" , "Oberfinanzdirektion Niedersachsen"
                    , "Rhein. Pfalz - Berlin", "Regierungsbezirksamt für Wiedergutmachung und verwaltete Vermögen Köln", "Aachen", "Landesbeirat für die Wiedergutmachung, Stuttgart", "Freiburg i.Br.", "Hamburg, Sozialbehörde, Amt für Wiedergutmachung",
                    "Freie und Hansestadt Hamburg", "Regierungsbezirk Mainz", "Hessisches Ministerium für Jugend, Familie und Gesundheit" , "Reg.-Präsident / Präsident des Verw.-Bezirks Hannover", "Amt für Wiedergutmachung des Landes Rheinland/Pfalz in Berlin Hauptabteilung II",
                    "Schleswig-Holstein in Kiel", "Kreissozialamt Hannover", "Reg.-Präsident Hannover", "Amt für Wiedergutmachung Rheinland-Pfalz" , "Saarburg Bezirksamt für Wiedergutmachung", "Freie und Hansestadt Hamburg, Arbeits- und Sozialbehörde, Amt für Wiedergutmachung",
                    "Niedersachsen-Präsident / Präsident des Verwaltungsbezirks Hannover", "Regierungsbezirksamt für Wiedergutmachung und verwaltete Vermögen Neustadt a. d. Weinstraße", "KSHA Hannover", "Regierungsbezirk für Wiedergutmachung und verwaltete Vermögen Trier",
                    "Oberfinanzdirektion Magdeburg", "Regierungsbezirkskammer für Wiedergutmachung und verwaltete Vermögen Mainz","Regierungsamt Arnsberg (Westf.)", "Regierungsbezirkskammer für Wiedergutmachung und verwaltete Vermögen Mainz",
                    "Regierungsbezirksamt für Wiedergutmachung und verwaltete Vermögen München", "Landesamt für die Wiedergutmachung Baden-Württemberg Stuttgart", 'Oberfinanzdirektion Rostock', 'Niedersächsisches Landesamt für Bezüge und Versorgung - Wiedergutmachung',
                        'Regierungspräsidium Arnsberg', 'Reg.-Präsident / Präsident des Verwaltungsbezirks Hannover', 
                        'Regierungsbezirksamt für Wiedergutmachung und verwaltete Vermögen Neustadt/w.', 'Montabaur', 
                        'Der Regierungspräsidium Düsseldorf', 'Magistrat der Stadt Bremen', 'Freie Hansestadt Bremen', 
                        'Freie Hansestadt Bremen - Landesamt für Wiedergutmachung', 'Reg.-Präsident / Präsident des Verw.-Bezirks Oldenburg', 
                        'Landesentschädigungsamt München', 'Bayerisches Hauptstaatsarchiv', 'Reg.-Präsident / Präsident des Verw.-Bezirks Braunschweig', 
                        'Niedersächsisches Landesverwaltungsamt - Wiedergutmachung', 'Bayerisches Landesamt für Verfolgungsgeschädigte', 
                        'Regierung Arnsberg', 'Regierungsbezirksamt für Wiedergutmachung und verwaltete Vermögen Neustadt/W.', 'Erfurt', 
                        'Entscheidungsbehörde Köln', 'Reg.-Präsidium Hildesheim', 'Bundesarchiv', 'Regierung Köln', 
                        'Niedersachsen-Präsident / Präsident des Verwaltungsgerichtshofs', 'Amt für Wiedergutmachung Stadt Bonn', 
                        'Regierung Arnsberg (Wf.)', 'Amt für Wiedergutmachung des Landes Rheinland-Pfalz', 
                        'Köln, Riehler Pl.2, 5000 Köln 1', 'Oberfinanzdirektion Niedersachsen Landesweite Bezüge- und Versorgungsstelle - Wiedergutmachung -', 
                        'Landesentschädigungsamt München 2, Arcisstraße 11', 'Bayerisches Landesamt für Verfolgtenentschädigung', 
                        'Bundesamt für Vertriebene', 'Der Herr Regierungspräsident in Detmold', 'Bayerisches Landesamt für Vertriebene', 
                        'Bayerisches Landesarchiv', 'Bayerisches Landesamt für Verfolgtenfragen', 'Bundesminister der Finanzen',
                        'Niedersachsen-Präsident / Präsident des Verw.-Bezirks', 'Frankfurt/M.', 'Regierungsamt Aachen (Westf.)', 
                        'Regierungspräsidium Münster', 'Ansbach', 'Niedersachsen-Präsident / Präsident des Verwaltungsbezirks Lüneburg',
                        'Regierung Ansbach (Würt.)', 'Regierungsbezirk für Wiedergutmachung und verwaltete Vermögen Neustadt a.d. Weinstr.',
                        'Aurich/Ostfriesland', 'Regionalverwaltungsbehörde für Wiedergutmachung und verwaltete Vermögen Koblenz',
                        'Entschädigungsbüro Köln', 'Magistrat der Stadt Bremenhaven', 'Amt für Wiedergutmachung des Landes Rheinland/Pfalz',
                        'Kreissonderhilfsausschuss Hannover', 'Bayerisches Verfolgtenamt', 'KSHA Hannover-Land', 'Regierungsbezirk Köln',
                        'Köln, Riehler Pl. 2, 5000 Köln 1', 'Regierungsbezirk Arnsberg (Westf.)', 'Oberfinanzdirektion Erfurt', 
                        'Regierungsbezirk Trier']

list_corrections_normalized = [normalize(office) for office in list_corrections]
gt_completed = gt_normalized + list_corrections_normalized
df_json['CompensationOffice1'] = df_json['CompensationOffice1'].str.replace("Bayrische", "Bayerische")
mask_matched_1 = df_json['CompensationOffice1'].apply(normalize).isin(gt_completed)
print(f'Number of matches: {mask_matched_1.sum()}')
df_unmatched = df_json[mask_not_null & ~mask_matched_1]
print(f'Number of unmatched entries: {len(df_unmatched)}')
print(f"Unique unmatched entries: {len(df_unmatched['CompensationOffice1'].unique().tolist())}")
percentage = len(df_unmatched) / len(mask_not_null) * 100
print(f"Percentage of unmatched entries: {percentage:.2f}%")

Number of matches: 1652394
Number of unmatched entries: 173552
Unique unmatched entries: 27154
Percentage of unmatched entries: 9.13%

In [52]:
df_unmatched['CompensationOffice1'].value_counts().head(30)

CompensationOffice1
Landesamt für die Wiedergutmachung                                                                14641
Bayerische Kartei                                                                                  9925
Regierungsbezirksamt für Wiedergutmachung und verwaltete Vermögen                                  7261
Bundeskartei                                                                                       4884
Bezirksamt für Wiedergutmachung                                                                    4130
HNG                                                                                                3402
Regierungsbezirksamt für Wiedergutmachung und kontrollierte Vermögen                               3354
Regierungsbezirks-Amt für Wiedergutmachung und kontrollierte Vermögen                              2557
Bezirksamt für Wiedergutmachung 65 Mainz                                                           1304
Kreissonderhilfsausschuss                                                                          1101
Barburg                                                                                             987
Kreissozialamt                                                                                      958
Baarburg                                                                                            950
Entschädigungsbehörde                                                                               863
Hamburg 1                                                                                           840
Bundesamt                                                                                           834
König                                                                                               825
Reg.-Präsident / Präsident des Verw.-Bezirks                                                        752
KSHA                                                                                                750
Kreissozialhilfsausschuss                                                                           712
Landesentschädigungsamt                                                                             602
Landesamt für Wiedergutmachung                                                                      586
Landesamt für Vertriebene                                                                           541
Kön                                                                                                 526
Regierung Arnsberg (Welf.)                                                                          497
Freie und Hansestadt Hamburg, Sozialbehörde, Ant für Wiedergutmachung, Hamburg 36, Drehbahn 54      489
Oberfinanzdirektion: Bundesvermögensabteilung                                                       478
Amt für Wiedergutmachung und kontrollierte Vermögen                                                 470
Sarburg                                                                                             463
Doppelmeldung                                                                                       449
Name: count, dtype: int64

# Matching based on Levenshtein Distance

In [13]:
#  return the minimum distance and the best match up to a threshold of half the length of the cleaned name
def get_min_distance_dynamic_normalized(name):
    name_clean = normalize(name)
    threshold = len(name_clean) // 2
    
    min_dist = float('inf')
    best_match = None
    for office in gt_completed:
        office_clean = normalize(office)
        d = distance(name_clean, office_clean)
        if d == 0:
            return 0, office
        if d < min_dist:
            min_dist = d
            best_match = office
    if min_dist <= threshold:
        return min_dist, best_match
    return np.nan, None

results = df_unmatched['CompensationOffice1'].apply(get_min_distance_dynamic_normalized)

lev_matches = pd.DataFrame({
    'CompensationOffice1': df_unmatched['CompensationOffice1'],
    'MatchedOffice': results.apply(lambda x: x[1]),
    'MatchDistance': results.apply(lambda x: x[0])
})

In [14]:
#print the matches with a distance of 1 and 2
df_matches_2 = lev_matches[lev_matches['MatchDistance'].isin([1, 2])]
df_matches_2.sample(25)

,CompensationOffice1,MatchedOffice,MatchDistance
1391041,Barburg,hamburg,2.0
8222,Regierung Arnswerg (Weltf.),regierungarnsbergwestf,2.0
955510,Bay. Landesentschädigungsamt,blandesentschaedigungsamt,2.0
329511,Regierungsbezirkssamt für Wiedergutmachung und...,regierungsbezirksamtfuerwiedergutmachungundver...,1.0
915047,Sarburg,saarburg,1.0
817984,Regierung Arnsberg (Welf.),regierungarnsbergwestf,2.0
1215648,"Landesamt für die Wiedergutmachung, Töbingen",landesamtfuerdiewiedergutmachungtuebingen,1.0
1341185,Bezirksamt für Wiedergutmachung K o b I e n z,bezirksamtfuerwiedergutmachungkoblenz,1.0
653640,Bezirksamt für Wiedergutmachung 65 Mainz,bezirksamtfuerwiedergutmachungmainz,2.0
937193,Freie und Hansestadt Hamburg Sozialbehörde Amp...,freieundhansestadthamburgsozialbehoerdeamtfuer...,1.0
845253,Baarburg,saarburg,1.0
1311557,Hamburg 1,hamburg,1.0
1793762,Bezirksamt für Wiedergutmachung 65 Mainz,bezirksamtfuerwiedergutmachungmainz,2.0
1367715,Sarburg,saarburg,1.0
1221487,Landesentschädigungsamt,blandesentschaedigungsamt,1.0
33049,Regierungsbezirksamt für Wiedergutmachung und ...,regierungsbezirksamtfuerwiedergutmachungundver...,1.0
610905,Bekirksregierung,bezirksregierung,1.0
851085,Koln,koeln,1.0
665856,Freie und Hansestadt Hamburg Arbeit- und Sozia...,freieundhansestadthamburgarbeitsundsozialbehoe...,1.0
1157454,Der Innern Minister des Landes Nordrhein-Westf...,derinnenministerdeslandesnordrheinwestfalenabt...,1.0
1036856,Entschädigungsamt Bremenhaven,entschaedigungsamtbremerhaven,1.0
856614,Amt für Wiedergutmachung des Landes Rheinland/...,amtfuerwiedergutmachungdeslandesrheinlandpfalz...,2.0
60503,Regierung Arnsberg (Weltf.),regierungarnsbergwestf,1.0
1307703,Regierungsbezirkamt für Wiedergutmachung und v...,regierungsbezirksamtfuerwiedergutmachungundver...,1.0
1878040,LR8 NW,lrbnw,1.0

In [15]:
#print the counts of the match distances of 1 and 2
df_matches_2['MatchDistance'].value_counts()
print(f"Number of matches with distance 1 or 2: {len(df_matches_2)}")
print(f"Number of unmatched entries after adding the close matches: {len(df_unmatched) - len(df_matches_2)}")

Number of matches with distance 1 or 2: 27826
Number of unmatched entries after adding the close matches: 169945

In [16]:
#remove the matches with distance 1 and 2 from the unmatched dataframe
df_unmatched_filtered = df_unmatched[~df_unmatched['CompensationOffice1'].isin(lev_matches[lev_matches['MatchDistance'].isin([1, 2])]['CompensationOffice1'])]
df_unmatched_filtered['CompensationOffice1'].value_counts().iloc[30:40]

CompensationOffice1
Amt für Wiedergutmachung des Landes Rheinland-Pfalz                470
Regierung Arnsberg (Wf.)                                           459
Doppelmeldung                                                      449
Amt für Wiedergutmachung Stadt Bonn                                447
Bundesamt für Wiedergutmachung                                     439
Niedersachsen-Präsident / Präsident des Verwaltungsgerichtshofs    437
Regierung Köln                                                     421
Bundesarchiv                                                       408
Reg.-Präsidium Hildesheim                                          396
Entscheidungsbehörde Köln                                          396
Name: count, dtype: int64

In [17]:
#print the top 200 unmatched entries
v_sum = 0

for n, v in df_unmatched_filtered['CompensationOffice1'].value_counts().iloc[:200].to_dict().items():
    print(f"{n}: {v}")
    v_sum += v

print(f"Total count of the top 200 unmatched entries: {v_sum}")

Landesamt für die Wiedergutmachung: 14641
Bayerische Kartei: 9925
Regierungsbezirksamt für Wiedergutmachung und verwaltete Vermögen: 7261
Bundeskartei: 4884
Bezirksamt für Wiedergutmachung: 4130
HNG: 3402
Regierungsbezirksamt für Wiedergutmachung und kontrollierte Vermögen: 3354
Bayerisches Landesarchiv: 2585
Regierungsbezirks-Amt für Wiedergutmachung und kontrollierte Vermögen: 2557
Bayerisches Landesamt für Verfolgtenfragen: 1291
Kreissonderhilfsausschuss: 1101
Kreissozialamt: 958
Bundesminister der Finanzen: 904
Entschädigungsbehörde: 863
Bundesamt: 834
König: 825
Bayerisches Landesamt für Vertriebene: 815
Reg.-Präsident / Präsident des Verw.-Bezirks: 752
KSHA: 750
Der Herr Regierungspräsident in Detmold: 745
Kreissozialhilfsausschuss: 712
Landesamt für Wiedergutmachung: 586
Bundesamt für Vertriebene: 560
Landesamt für Vertriebene: 541
Bayerisches Landesamt für Verfolgtenentschädigung: 521
Landesentschädigungsamt München 2, Arcisstraße 11: 501
Oberfinanzdirektion Niedersachsen Landesweite Bezüge- und Versorgungsstelle - Wiedergutmachung -: 483
Oberfinanzdirektion: Bundesvermögensabteilung: 478
Köln, Riehler Pl.2, 5000 Köln 1: 477
Amt für Wiedergutmachung und kontrollierte Vermögen: 470
Amt für Wiedergutmachung des Landes Rheinland-Pfalz: 470
Regierung Arnsberg (Wf.): 459
Doppelmeldung: 449
Amt für Wiedergutmachung Stadt Bonn: 447
Bundesamt für Wiedergutmachung: 439
Niedersachsen-Präsident / Präsident des Verwaltungsgerichtshofs: 437
Regierung Köln: 421
Bundesarchiv: 408
Reg.-Präsidium Hildesheim: 396
Entscheidungsbehörde Köln: 396
Erfurt: 386
Regierungsbezirksamt für Wiedergutmachung und verwaltete Vermögen Neustadt/W.: 381
Regierung Arnsberg: 375
An Bundeskartei: 371
Bayerisches Landesamt für Verfolgungsgeschädigte: 370
Niedersächsisches Landesverwaltungsamt - Wiedergutmachung: 365
BHF: 346
BEG: 340
Reg.-Präsident / Präsident des Verw.-Bezirks Braunschweig: 324
Bayerisches Hauptstaatsarchiv: 321
Landesentschädigungsamt München: 312
Reg.-Präsident / Präsident des Verw.-Bezirks Oldenburg: 309
Freie Hansestadt Bremen - Landesamt für Wiedergutmachung: 307
Freie Hansestadt Bremen: 307
Magistrat der Stadt Bremen: 306
Der Regierungspräsidium Düsseldorf: 297
Montabaur: 291
Regierungsbezirksamt für Wiedergutmachung und verwaltete Vermögen Neustadt/w.: 291
Reg.-Präsident / Präsident des Verwaltungsbezirks Hannover: 289
Regierungspräsidium Arnsberg: 285
Niedersächsisches Landesamt für Bezüge und Versorgung - Wiedergutmachung: 272
BMF: 269
Oberfinanzdirektion Rostock: 269
Niedersachsen-Präsident / Präsident des Verw.-Bezirks: 268
K81: 268
Frankfurt/M.: 267
K81n: 267
Regierungsamt Aachen (Westf.): 262
Regierungspräsidium Münster: 260
Ansbach: 257
Niedersachsen-Präsident / Präsident des Verwaltungsbezirks Lüneburg: 255
Niedersachsen-Präsident / Präsident des Verwaltungsbezirks: 251
Regierungsbezirksamt für Wiedergutmachung und kontrolliertes Vermögen: 248
Sondervermögens-u. Bauverwaltung: 242
Bayerisches Landesamt: 241
Regierung Ansbach (Würt.): 240
Regierungsbezirk für Wiedergutmachung und verwaltete Vermögen Neustadt a.d. Weinstr.: 238
Aurich/Ostfriesland: 235
Regionalverwaltungsbehörde für Wiedergutmachung und verwaltete Vermögen Koblenz: 229
Entschädigungsbüro Köln: 227
Magistrat der Stadt Bremenhaven: 224
Amt für Wiedergutmachung des Landes Rheinland/Pfalz: 222
VB3: 218
Kreissonderhilfsausschuss Hannover: 215
Bundesfinanzdirektion West: 214
Bayerisches Verfolgtenamt: 209
KSHA Hannover-Land: 206
Landeszentrale für die Vergütung von Opfern des Nationalsozialismus: 206
Regierungsbezirk Köln: 206
KSH: 205
Köln, Riehler Pl. 2, 5000 Köln 1: 204
Regierungsbezirk Arnsberg (Westf.): 203
Oberfinanzdirektion Erfurt: 201
Regierungsbezirk Trier: 197
Niedersächsisches Landesamt für Beziege und Versorgung - Wiedergutmachung: 197
Regierungsbezirk für Wiedergutmachung und kontrollierte Vermögen: 196
Niedersächsisches Ministerium des Innern: 193
Regierungsbezirk Neustadt a.d. Weinstr.: 192
Härtedefonds - Hessen: 187
Watenstedt-Salzgitter: 185
Landesbeauftragte für die Wiedergutmachung, Stuttgart: 185
Niedersachsen - Präsident des Verwaltungsbezirks Hannover: 183
Der Regierungspräsidialamt Düsseldorf: 182
Pirmasens: 181
Bayerisches Landeszentrum für die Opfer des Nationalsozialismus: 181
Regierungsbezirkskammer für Wiedergutmachung und verwaltete Vermögen Koblenz: 181
Kaiserslautern: 178
Niedersachsen Reg.-Präsident / Präsident des Verw.-Bezirks Hannover: 175
Bayerisches Landesamt für die Opfer des Nationalsozialismus: 173
Braunburg: 171
BfA Berlin: 168
Regierungspräsident - Dezernat f. Wiedergutmachung - Detmold: 166
Regierungsbezirksamt für Wiedergutmachung und verwaltete Vermögens: 166
Höherer Kommissar der Vereinten Nationen für Flüchtlinge: 166
Regierung Aachen (Westf.): 165
Niedersachsen-Präsident / Präsident des Verw.-Bezirks Hannover: 164
Regierung Ansbach (Welf.): 164
Kreissonderhilfsschübe: 163
Oberfinanzdirektion Cottbus: 162
EG: 160
Der Niedersächsische Minister des Innern: 159
Niedersachsen - Präsident / Präsident des Verwaltungsbezirks: 158
Kreisonderhilfsausschuss: 157
Regierungsbezirk für Wiedergutmachung und verwaltete Vermögen: 156
Freie und Hansestadt Hamburg, Amt für Wiedergutmachung: 156
Ministerium für Arbeit, Gesundheit und Soziales des Landes Schleswig-Holstein Entschädigungsbehörde: 155
Oberfinanzdirektion Berlin: 153
Burgdorf: 152
Wiedergutmachung: 151
Neustadt a.d. Weinstr.: 149
Regierungsbezirksamt für Wiedergutmachung: 147
Bezirksamt von Koblenz für Wiedergutmachung TRIER: 143
Nürnberg: 142
Niedersachsen-Präsident / Präsident des Verwaltungsbezirks Osnabrück: 141
Der Innensenator des Landes Nordrhein-Westfalen: 141
Niedersachsen-Präsident: 140
Bayerisches Verwaltungsamt: 137
Der Regierungspräsident: 137
Tr.: 137
KSHA Celle-Stadt: 137
Die Ministerin für Arbeit, Soziales Jugend und Gesundheit des Landes Schleswig-Holstein Entschädigungsbehörde: 136
Lüneburg-Stadt: 135
Kreissozialhilfsausschuss Hannover: 133
Bezirksamt für Wiedergutmachung München: 133
Regierungsbezirks-Amt für Wiedergutmachung und kontrolliertes Vermögen: 128
Regierung Ansbach (Württ.): 126
Bayerisches Landesamt für Wiedergutmachung: 125
Kreissozialamt Braunschweig-Stadt: 124
KSHA Osterode/H.: 124
Hessen Neu: 123
Bekannt: 123
Reg.-Präsident / Präsident des Verw.-Bezirks Lüneburg: 122
Köln, Riehlstr. Pl.2, 5000 Köln 1: 122
Kreissozialhilfsausschuss Braunschweig-Stadt: 121
Regionalverwaltungsbehörde für Wiedergutmachung und verwaltete Vermögen Mainz: 120
KSHA Braunschweig: 119
Statistisches Landesamt Nordrhein-Westfalen, Düsseldorf 1, Postfach 1105: 119
Regierungsbezirk München: 117
Bundesverwaltungsamt: 117
Oberfinanzdirektion Chemnitz: 117
Der Oberkreisdirektor -Amt für Wiedergutmachung- in Herford: 116
Regierungsbezirk Mainz für Wiedergutmachung und verwaltete Vermögen: 116
Der Bundesminister der Finanzen: 116
KSHA München: 114
Aurich i.Ostfriesl.: 114
Freie Hansestadt Bremen, Der Senator für Arbeit, Landesamt für Wiedergutmachung: 113
Regionalverwaltungsamt für Wiedergutmachung und verwaltete Vermögen Mainz: 112
Landesamt für die wiedergutmachung: 111
Regionalverwaltungsamt für Wiedergutmachung und verwaltete Vermögen Koblenz: 111
BMF - VB4: 109
Regierung Düsseldorf: 108
K61n: 108
Braunschweig-Stadt: 106
Bayerisches Landesamt für Verfolgten: 106
Der Innensenator des Landes Nordrhein-Westfalen Abteilung V: 106
Bayerische Landesentschädigungs- und Staatschuldenverwaltung: 106
Stadt Hameln: 104
Oberfinanzdirektion Koblenz: 104
Bebra: 104
Landesstelle für die Wiedergutmachung: 103
Freie und Hansestadt Hamburg Sozialbehörde Amt für Wiedergutmachung Hamburg 1, Alstädter Straße 8 (Springenhoof): 102
KSHA Oldenburg: 101
Freie und Hansestadt Hamburg Sozialbehörde Amt für Wiedergutmachung Hamburg 1, Alstädter Straße 8 (Springenhorf): 101
K81m: 101
Bayerisches Landesamt für Verfolgte des Nationalsozialismus: 100
Regierungsbezirk für Wiedergutmachung und verwaltete Vermögen Mainz: 98
Freie und Hansestadt Hamburg Sozialbehörde Amt für Wiedergutmachung Hamburg 1, Alsterdorfer Straße 8 (Sprinkenhof): 98
Reg.-Präsident des Verw.-Bezirks Hannover: 97
Amt Regierungsbezirksamt für Wiedergutmachung und kontrollierte Vermögen: 97
Regierungsbezirk Koblenz: 97
Niedersachsen Reg.-Präsident Hannover: 96
Landesamt für Finanzen Landesentschädigungsamt: 96
Amt für Wiedergutmachung des Selbstkantkreises Geilenkirchen-Heinsberg und Regierungspräsident Aachen: 95
Freie und Hansestadt Hamburg Sozialbehörde Amt für Wiedergutmachung Hamburg 1, Alsterstraße 8 (Springenhoof): 95
Bay: 94
Landesentschädigungsamt München 2: 94
Nienburg-Weser: 94
KSHA Göttingen: 93
Suchkartei für Bez. Reg.: 93
Haftbescheid: 93
Total count of the top 200 unmatched entries: 100934

In [19]:
list_no_sufficient_information = ['Niedersachsen-Präsident / Präsident des Verwaltungsbezirks', 'An Bundeskartei', 
                              'Bundesamt für Wiedergutmachung', 'Amt für Wiedergutmachung und kontrollierte Vermögen', 
                              'Oberfinanzdirektion: Bundesvermögensabteilung', 'Landesamt für Vertriebene', 
                              'Landesamt für Wiedergutmachung', 'Kreissozialhilfsausschuss', 'Reg.-Präsident / Präsident des Verw.-Bezirks', 
                              'Entschädigungsbehörde', 'Kreissozialamt', 'Kreissonderhilfsausschuss', 'Regierungsbezirks-Amt für Wiedergutmachung und kontrollierte Vermögen', 
                              'Regierungsbezirksamt für Wiedergutmachung und kontrollierte Vermögen', 'Bundeskartei', 
                              'Regierungsbezirksamt für Wiedergutmachung und verwaltete Vermögen', 'Kreissozialamt', 'Bundesamt', 'Doppelmeldung', 
                              "Landesamt für die Wiedergutmachung", "Bezirksamt für Wiedergutmachung", "Kreissozialamt", "König",
                              'Regierungsbezirksamt für Wiedergutmachung und kontrolliertes Vermögen', 'Sondervermögens-u. Bauverwaltung',
                              'Bayerisches Landesamt', 'Bundesfinanzdirektion West', 'KSHA', 'KSH', 'Regierungsbezirk für Wiedergutmachung und kontrollierte Vermögen',
                              ]

In [ ]:
#filtering out impossible matches and further additions to gt
for office in list_no_sufficient_information:
    if office in df_unmatched_filtered['CompensationOffice1'].values:
        df_unmatched_filtered = df_unmatched_filtered[df_unmatched_filtered['CompensationOffice1'] != office]

print(len(df_unmatched_filtered))
print(len(df_unmatched_filtered['CompensationOffice1'].unique()))

98173
24451

# Cluster remaining names based on Levenshtein Distance of 1/2

In [ ]:
# cluster the remaining unmatched entries based on their edit distance to find potential groups of similar entries that might represent the same office but with different spellings or typos
from collections import defaultdict
from rapidfuzz.distance import Levenshtein

def cluster_locations_edit_distance(locs, max_dist=2):
    # 🔹 1. Clean + normalize
    unique_names = sorted({
        name.strip() for name in locs
        if isinstance(name, str) and name.strip()
    })
    
    normalized = {name: normalize(name) for name in unique_names}
    
    # 🔹 2. Build graph (adjacency list)
    graph = defaultdict(set)
    
    for i, name_a in enumerate(unique_names):
        clean_a = normalized[name_a]
        
        for j in range(i + 1, len(unique_names)):
            name_b = unique_names[j]
            clean_b = normalized[name_b]
            
            if not clean_a or not clean_b:
                continue
            
            dist = Levenshtein.distance(clean_a, clean_b)
            
            if dist <= max_dist:
                graph[name_a].add(name_b)
                graph[name_b].add(name_a)
    
    # 🔹 3. Find connected components (DFS)
    visited = set()
    clusters = []
    
    for name in unique_names:
        if name in visited:
            continue
        
        stack = [name]
        cluster = []
        
        while stack:
            node = stack.pop()
            if node in visited:
                continue
            
            visited.add(node)
            cluster.append(node)
            
            stack.extend(graph[node])
        
        clusters.append(cluster)
    
    return clusters

clusters = cluster_locations_edit_distance(df_json['CompensationOffice1'].apply(normalize).unique().tolist(), max_dist=2)

In [58]:
# print out the found clusters

print(len(clusters))
print(len([c for c in clusters if len(c) > 1]))

for i, cluster in enumerate(clusters, 1):
    if len(cluster) > 1:
        print(f"\nCluster {i} ({len(cluster)} items):")
        for name in cluster:
            print(f"  - {name}")

13615
1892

Cluster 1 (2359 items):
  - 01
  - 55
  - ks
  - hst
  - hdi
  - kdl
  - kela
  - kalt
  - kalm
  - wblm
  - w81m
  - h81n
  - k813
  - ko11
  - k51m
  - k5d
  - ka
  - hj
  - nl
  - noy
  - nord
  - noerl
  - oel
  - ksl
  - ol
  - e
  - bme
  - bimf
  - him
  - xin
  - linz
  - kin
  - 76in
  - hin
  - h8ln
  - holz
  - koln
  - k6hn
  - k31n
  - k6ln
  - kan
  - vag
  - a
  - hh
  - bo
  - jdo
  - jdzn
  - bdln
  - hln
  - hep
  - ek
  - wes
  - w81
  - rz1
  - x61
  - k617
  - k81a
  - k13
  - 510
  - 310
  - 51a
  - hoa
  - oe
  - moel
  - aoeln
  - zoelfn
  - roeln
  - koelna
  - kola
  - koex
  - hoe
  - hoech
  - zolch
  - uolh
  - nolu
  - olm
  - jholm
  - wolm
  - wolfr
  - woln
  - wkoeln
  - awkkoeln
  - uokkoeln
  - uoykoeln
  - umwkoeln
  - amtkoeln
  - afwkoeln
  - oftkoeln
  - oftkoln
  - ofokoeln
  - qfdkoeln
  - oedkoeln
  - uoexkoeln
  - uoekkoeln
  - mokkoeln
  - olgkoeln
  - lgkoeln
  - koeln
  - moelln
  - boeln
  - roehn
  - roth
  - sth
  - sra
  - efra
  - pfa
  - bea
  - oe1
  - 511
  - k61
  - k619
  - 9919
  - k519
  - c5194
  - 514
  - m1
  - mad
  - bam
  - bass
  - uoss
  - uojn
  - moin
  - kodin
  - k8in
  - k814
  - k31m
  - k51n
  - a511
  - k51a
  - koza
  - kzg
  - ksi
  - kshd
  - ksln
  - kshs
  - knhes
  - knies
  - kiel
  - kall
  - kann
  - main
  - in
  - ri
  - raiv
  - aic
  - aach
  - aachen
  - aadher
  - aadhen
  - hachen
  - hagen
  - hadern
  - hadjen
  - aaden
  - emden
  - eggen
  - bergen
  - barmen
  - barmer
  - bayer
  - bayam
  - bosam
  - boehm
  - brem
  - b8lm
  - r81m
  - r8lm
  - kblm
  - kald
  - kglw
  - nolw
  - nfhw
  - bfh
  - sch
  - lvh
  - rv
  - k1
  - 161
  - 16515
  - 15517
  - 6517
  - ks17
  - k812
  - k51
  - kdk
  - ko
  - uol
  - usa
  - loa
  - loed
  - voel
  - wohl
  - koh
  - syh
  - si
  - 3in
  - x8in
  - mein
  - mains
  - nainz
  - mainz
  - muenz
  - muen
  - moeln
  - roln
  - voeln
  - noein
  - haein
  - h8in
  - 16in
  - 6n
  - 760
  - k6g
  - kdj
  - ksm
  - kelm
  - 20lm
  - hblm
  - hoelm
  - hoeamt
  - hoelt
  - uoeln
  - voelbn
  - voelnd
  - oeln
  - noell
  - oebl
  - oe10
  - k310
  - k3ln
  - holn
  - hoein
  - hoedn
  - hoehn
  - joehn
  - joerg
  - joeln
  - xoln
  - oen
  - roein
  - rin
  - kuin
  - klein
  - kolei
  - koi
  - k
  - al
  - llr
  - sln
  - n
  - 50
  - th
  - dhe
  - dbhf
  - bshf
  - hf
  - ght
  - hu
  - bhf
  - bv
  - rbd
  - vb3
  - vb15
  - kb1
  - k81t
  - x81nt
  - k81n
  - n81m
  - k81u
  - k811
  - 18811
  - 2811
  - 812
  - 8199
  - k819
  - a219
  - e217
  - e4017
  - e4002
  - e4272
  - 24275
  - 24224
  - 21220
  - 271225
  - 29125
  - 231221
  - 1223
  - 11222
  - 151022
  - 11020
  - a1520
  - a127
  - e123
  - 5124
  - 15324
  - 15523
  - 25623
  - 25626
  - 14626
  - 17625
  - 762n
  - b61n
  - k61u
  - k810
  - k510
  - k511
  - k81g
  - k84
  - kzl
  - uel
  - inl
  - ing
  - hno
  - kdo
  - kato
  - kattow
  - otto
  - oft
  - kat
  - kael
  - kalln
  - kln
  - koni
  - koa
  - sta
  - stadt
  - nustadt
  - neustadtw
  - neustadt
  - neuisaadt
  - neuostadt
  - novostadt
  - nordstadt
  - nenstadt
  - osnstadt
  - bonnstadt
  - kolnstadt
  - hannstadt
  - wienstadt
  - heustadt
  - neustadtm
  - neustadtar
  - neustatter
  - neustadtarbg
  - neustadtarbge
  - neustadtan
  - neustadtpk
  - neustadtadw
  - neustadtindw
  - neuigkadt
  - neuigbalt
  - neuinsadt
  - neuendadt
  - trneustadt
  - stade
  - stadtv
  - anstade
  - ga
  - gb
  - fu
  - efd
  - efrn
  - efrat
  - efrut
  - ehrt
  - kurt
  - kst
  - kdn
  - bn
  - bund
  - bonn
  - bona
  - bva
  - bil
  - viel
  - ve
  - viec
  - wied
  - oed
  - oldb
  - oln
  - nolm
  - k6lm
  - kclm
  - w8lm
  - k8lm
  - 181m
  - k816
  - e8167
  - e4166
  - e4171
  - e7411
  - e3421
  - e542
  - e425
  - e6455
  - e6446
  - e6340
  - e9390
  - e7300
  - e7208
  - e7938
  - e2838
  - e6834
  - e6891
  - e61
  - e632
  - e6383
  - e6473
  - e3873
  - e9823
  - e3573
  - e3598
  - e3488
  - e3562
  - z3552
  - e306
  - e2063
  - e2733
  - 12723
  - 13703
  - e2729
  - e2659
  - e2742
  - b2747
  - b297
  - b1296
  - b757
  - 751
  - 761n
  - k615
  - 61
  - tr1
  - troe
  - trler
  - truecr
  - troeer
  - troeier
  - trivier
  - trizer
  - frier
  - geier
  - leer
  - tier
  - trtr
  - tr11
  - triv
  - trsa
  - trsamt
  - krsamt
  - tramt
  - heamt
  - helm
  - holzm
  - molm
  - xslm
  - xxln
  - x8lm
  - k81m
  - k8lu
  - kstu
  - kst10
  - kstn
  - kn
  - h6
  - bhm
  - bmf
  - bmfiv
  - bmfub
  - bmfvtb
  - bmfvd4
  - bmfvt34
  - bmfv84
  - bhfvb4
  - bhfvb3
  - bhtvb3
  - shfvb3
  - bmfvb3
  - bmfvr4
  - bmfvb4
  - bmfvag
  - bmfvt4
  - bmfvt
  - bhfvts
  - bhfv33
  - bhfvc4
  - bhfivb4
  - bhfvbs4
  - bhfubs0
  - dshfubs0
  - bhfuby
  - bmfuby
  - bhfub
  - dhfub3
  - dmeub3
  - bmfub3
  - bmfub40
  - bmtvb40
  - bmfvb4o
  - bmftvb4
  - bmtvb4
  - bmpvb4
  - bmfvby
  - bmfvsb
  - bmfva9
  - bmfvbh
  - bhfvbh
  - bhfv84
  - dhfvb4
  - bhfvtb4
  - bhfveb3
  - bhfeb4
  - bhfubs
  - bhfuvs
  - bhfub4
  - bhfvd4
  - bhfvt54
  - bmfvts4
  - bmfvtj
  - bmfutb
  - bmfvtb4
  - bmfvis4
  - bhfvts4
  - bmfvbs4
  - bmfv34
  - bmfvds
  - dmfvb4
  - rmfvb3
  - bmtvb3
  - bmftvbh
  - bmfivb4
  - bmfvb40
  - bmfvb301
  - bmfub4
  - bmfubt
  - bmft
  - bnf
  - hng
  - hnog
  - hnc
  - hmg
  - lg
  - lgnt
  - lgd
  - gzd
  - bzk
  - baw
  - baum
  - bayem
  - bayz
  - bauk
  - bav
  - baf
  - bafoe
  - baft
  - barth
  - bartal
  - karta
  - kala
  - kda
  - k6
  - 31
  - h8
  - 3
  - 3hf
  - the
  - true
  - tr
  - tr4
  - rb
  - wbb
  - wkn
  - k8
  - k618
  - ks18
  - kstl
  - kbl
  - keln
  - koelin
  - koelling
  - kolin
  - 1koln
  - noln
  - hoeln
  - joetn
  - joeoen
  - jueden
  - doeln
  - dolm
  - dope
  - uoe
  - uro
  - uok
  - kk
  - ksh
  - kshae
  - kshag
  - kshaw
  - kshax
  - ksha
  - kshahm
  - kshaf
  - kshao
  - ksia
  - lvia
  - lvhh
  - vbh
  - jh
  - jva
  - jnf
  - dhf
  - dwmf
  - dlof
  - dshf
  - kshb
  - kshc
  - ks1
  - 401
  - 1601
  - 16
  - yv
  - we
  - wien
  - waln
  - kalu
  - kai
  - kalis
  - kreis
  - dweis
  - zweig
  - doein
  - xoin
  - k6in
  - w8in
  - 158in
  - 5in
  - m8in
  - m8lm
  - 5lm
  - xolm
  - komm
  - kem
  - hlm
  - 51m
  - bdm
  - brdd
  - bdi
  - ki
  - nic
  - nicla
  - nila
  - etla
  - epa
  - egaz
  - az
  - sw
  - sow
  - xol
  - moln
  - ukln
  - bln
  - sin
  - wid
  - kdd
  - kdst
  - oest
  - oelm
  - roelm
  - roem
  - romm
  - rmf
  - usmf
  - jmf
  - bmp
  - beg
  - eg
  - ra
  - ua
  - e4ua
  - esa
  - e81
  - 1281
  - 5282
  - 5281
  - 781
  - 7201
  - e7241
  - e7940
  - e7245
  - e7290
  - e9340
  - e2740
  - c2750
  - c2860
  - c861
  - h811
  - r81n
  - x31n
  - r61n
  - k62n
  - 61n
  - k61e
  - 61m
  - k611
  - k311
  - k610
  - k517
  - a597
  - a9
  - ig
  - icj
  - lc
  - rln
  - kaln
  - kalien
  - kglm
  - kom
  - kohl
  - kolu
  - hol
  - hoell
  - aoel
  - koei
  - kota
  - kgaa
  - k8a
  - kob
  - yon
  - loin
  - stin
  - kbin
  - k8ln
  - k81c
  - h81m
  - m81
  - k86
  - kdm
  - b8m
  - b81n
  - 561n
  - x61n
  - x81t
  - k81nt
  - k81
  - k61a
  - kaha
  - epha
  - ha
  - chr
  - bht
  - b4f
  - b748
  - 6728
  - 2727
  - 28767
  - c627
  - c4247
  - a827
  - a81n
  - 81a
  - 7819
  - x816
  - 1116
  - k1111
  - 10616
  - e9616
  - e9556
  - e975
  - e1758
  - 158
  - k5
  - kod
  - krr
  - kbm
  - jbo
  - jhoe
  - thom
  - hof
  - h8m
  - h8lm
  - 6lm
  - solm
  - 46lm
  - kxlm
  - kell
  - karl
  - koel
  - koelle
  - koelner
  - voelker
  - rpvoelker
  - voelk
  - oeld
  - noeln
  - loebn
  - lueba
  - juela
  - koela
  - oelg
  - hblg
  - rbln
  - rbnw
  - lranw
  - lnrbnw
  - erbnw
  - labnw
  - lr8nw
  - tr8nw
  - krbnw
  - lrbnw
  - lranm
  - oran
  - ofen
  - koen
  - kroten
  - troeten
  - troeler
  - trueier
  - trueher
  - trueer
  - trueby
  - trueir
  - trjetr
  - trier
  - triver
  - treves
  - traever
  - troeger
  - traeger
  - prager
  - traeier
  - trziger
  - thuer
  - thoem
  - thoess
  - hoess
  - hesse
  - messen
  - wiessen
  - giessen
  - hessen
  - hessei
  - kassei
  - kasseli7
  - kassell
  - kasse1
  - kasse
  - kassei7
  - kassel
  - jossel
  - kaiss
  - essen
  - meissen
  - hesssen
  - hesseneu
  - hessenneu
  - hessennu
  - hessendp
  - hessenda
  - wieoben
  - hoessle
  - huss
  - fuss
  - hoehr
  - sohr
  - schw
  - smw
  - dme
  - bmt
  - bvamt
  - bsmf
  - imf
  - uff
  - afw
  - bfa
  - brd
  - brand
  - ran
  - braun
  - braunau
  - baunan
  - inn
  - vin
  - poin
  - wloin
  - wstin
  - loein
  - roelin
  - voeljn
  - voeblen
  - koeblenz
  - hoblenz
  - woblenz
  - kobllenz
  - kohlenz
  - koblanz
  - koblenz
  - lgkoblenz
  - ebkoblenz
  - oedkoblenz
  - olgkoblenz
  - jcoblenz
  - jueoblenz
  - roblenz
  - blenz
  - bhlenz
  - oblenz
  - koblentz
  - noblenz
  - kolenz
  - kohloenz
  - ko3lenz
  - nobles
  - wobling
  - hoebelenz
  - voelin
  - rhein
  - heins
  - heinig
  - peine
  - kein
  - kbi
  - kb
  - ko1
  - k815
  - e810
  - e8670
  - e540
  - e5204
  - 1524
  - 1444
  - f446
  - e4496
  - 4496
  - 7406
  - 76
  - 760n
  - k6n
  - koe
  - k4m
  - rm
  - wv
  - wgs
  - kgl
  - k8n
  - han
  - hlang
  - hann
  - hannlo
  - johann
  - sthann
  - stha6b
  - sth57b
  - sth528b
  - sth521f
  - sth541k
  - sth414
  - sth3142
  - sth3172m
  - sth3177w
  - sth3100w
  - sth3180g
  - sth3150r
  - sth3153h
  - sth1539
  - sth133s
  - sth1234s
  - sth2342s
  - sth1442s
  - sth1122s
  - sth2122
  - sth2522a
  - sth2222
  - sth2882
  - sth6852
  - sth6892d
  - sth2892k
  - sth2821k
  - sth2931k
  - sth2231t
  - sth2031h
  - sth2451h
  - sth2252h
  - sth2226
  - sth1236
  - sth1216k
  - sth1016n
  - sth1006f
  - sth7016m
  - sth7096
  - sth7051
  - sth805k
  - sth2050
  - sth2051w
  - sth2078w
  - sth2571w
  - sth2710
  - sth2513
  - sth2587
  - sth2957
  - sth29560
  - sth2756
  - sth2056l
  - sth206a
  - sth2662
  - sth1612
  - sth1654
  - sth1455
  - sth2455k
  - sth2465b
  - sth265k
  - sth2699
  - sth2498
  - sth2690
  - sth2908
  - sth2408b
  - sth2108g
  - sth2708b
  - sth2703
  - sth2073
  - sth2007z
  - sth2907f
  - sth2202f
  - sth202a
  - sth2623
  - sth2620b
  - sth2922b
  - sth2967b
  - sth2679
  - sth2686
  - sth2618i
  - sth2918r
  - sth2948w
  - sth2848e
  - sth2847e
  - sth2777e
  - sth2700e
  - sth2720c
  - sth2750k
  - sth2755
  - sth2751
  - sth2745
  - sth2840
  - sth2841g
  - sth2851t
  - sth2890t
  - sth2490w
  - sth2660w
  - sth2666
  - sth2165
  - sth23145
  - sth2310l
  - sth2510v
  - sth2410r
  - sth2460
  - sth2880
  - sth2330
  - sth2391
  - sth2373
  - sth237r
  - sth3337r
  - st43327r
  - sth3327
  - sth3317b
  - sth1316b
  - sth1329b
  - sth1369r
  - sth1709r
  - sth1607r
  - sth1807h
  - sth1637b
  - sth1237
  - sth1047
  - sth1404j
  - sth1354j
  - sth1340
  - sth1540h
  - sth940h
  - sth1409
  - sth1430p
  - sth430j
  - sth149e
  - sth1491l
  - sth1799l
  - sth1779v
  - sth1790b
  - sth1390g
  - sth3340g
  - sth3244g
  - sth3204w
  - sth3205b
  - sth3085b
  - sth7075b
  - sth7061b
  - sth7073b
  - sth7079k
  - sth7085k
  - sth1485k
  - sth1465e
  - sth1459
  - sth2452
  - sth2527
  - sth6827
  - sth6667
  - sth6664
  - sth2604
  - sth2622
  - sth3322
  - sth3092
  - sth3091m
  - sth3018
  - sth701w
  - sth203w
  - sth2076
  - sth2426
  - sth240h
  - sth640
  - sth6949
  - sth604b
  - sth602s
  - sth752s
  - sth713s
  - sth2138s
  - sth238e
  - sth2392
  - sth2652
  - sth962
  - sth2642
  - sth2245
  - sth2924d
  - sth1921d
  - sth1951k
  - sth1952j
  - sth1992w
  - sth1920
  - sth1900d
  - sth1903d
  - sth6700d
  - sth1500s
  - sth1508st
  - sth1878st
  - sth1810st
  - sth1854st
  - sth1450st
  - sth1730st
  - sth1733t
  - sth1734t
  - sth1034e
  - sth1060e
  - sth1560
  - sth1656g
  - sth5656h
  - sth1666
  - sth1662h
  - sth622h
  - sth6722m
  - sth6725
  - sth6776
  - sth617k
  - sth315k
  - sth3215e
  - sth3315b
  - sth3345r
  - sth1345h
  - sth1375e
  - sth1965h
  - sth1045d
  - sth1057d
  - sth159d
  - sth1250d
  - sth15500
  - sth1050w
  - sth105r
  - sth1041
  - sth1741w
  - sth1748b
  - sth1742
  - sth2746
  - sth264f
  - sth2764z
  - sth564m
  - sth814m
  - sth714l
  - sth7105
  - sth7137
  - sth7038
  - sth2088
  - sth2048j
  - sth2008b
  - sth2308d
  - sth2889
  - sth2879w
  - sth2279b
  - sth2275m
  - sth2296m
  - sth2116m
  - sth3116g
  - sth3216h
  - sth2816h
  - sth2813l
  - sth2217l
  - sth2223l
  - sth2224r
  - sth3284r
  - sth1884r
  - sth4284
  - sth2424p
  - sth2124
  - sth1724
  - sth744
  - sth758
  - sth735g
  - sth725e
  - sth726e
  - sth716w
  - sth446w
  - sth441p
  - sth7106
  - sth3168w
  - sth3174w
  - sth3103w
  - sth3203w
  - sth3273b
  - sth4103f
  - sth3077w
  - sth3070p
  - sth73du
  - sth1704p
  - sth2159
  - sth2157b
  - sth2575
  - sth2772
  - sth2771w
  - sth2731a
  - sth2782h
  - sth782k
  - sth7080k
  - sth2976
  - sth3297p
  - sth2974m
  - sth2536
  - sth2232
  - sth2230t
  - sth2270n
  - sth1270f
  - sth2987c
  - sth987d
  - sth957e
  - sth483d
  - sth2983
  - sth2507w
  - sth2405
  - sth2715s
  - sth2054r
  - sth2113h
  - sth2016d
  - sth3011d
  - sth1869w
  - sth869m
  - sth2339w
  - sth3339w
  - sth3342w
  - sth3336p
  - sth2684i
  - sth1147w
  - sth55570
  - sth1815b
  - sth1835b
  - sth3191k
  - sth627h
  - sth661h
  - sth6681b
  - sth6680b
  - sth6670s
  - sth6695s
  - sth6650
  - sth6818
  - sth6811a
  - sth6719m
  - sth892h
  - sth993h
  - sth1562t
  - sth860st
  - sth802st
  - sth982st
  - sth2980st
  - sth2950s
  - sth2995st
  - sth2505st
  - sth608st
  - sth1620a
  - sth1621a
  - sth1527a
  - sth1911c
  - sth1919g
  - sth2592g
  - sthm54s
  - sth6991
  - sth643g
  - sth2449h
  - sth2462a
  - sth3093
  - sth1332k
  - sth2600k
  - sth2673k
  - sth1468g
  - sth1368p
  - sth3350m
  - sth1797k
  - sth3149b
  - sth4708m
  - sth885w
  - sth741sm
  - hicn
  - icin
  - kdin
  - hkoin
  - hkond
  - hhand
  - kzin
  - kzn
  - 81n
  - m81m
  - 581m
  - k818
  - 6838
  - e6832
  - e6855
  - e6894
  - e6806
  - e6476
  - e6443
  - e633
  - 1233
  - v33
  - k31
  - k514
  - k515
  - k51d
  - k616
  - k61r
  - 611
  - 317
  - a317
  - a331
  - 9931
  - 13314
  - 314
  - 51n
  - k5ln
  - k3lm
  - walm
  - klm
  - komo
  - yom
  - eywm
  - 31m
  - x81m
  - k61m
  - k81r
  - k61t
  - k61n
  - e81n
  - 81m
  - 51
  - st51
  - 1051
  - 1661
  - 1501
  - 11
  - e5
  - eph
  - wuh
  - suhl
  - sprl
  - trl
  - vrg
  - hhg
  - hdn
  - ddf
  - kdf
  - hdm
  - hp
  - bpa
  - bah
  - bafh
  - bayhj
  - bayhio
  - bayhoe
  - bayhues
  - bayhst
  - bayhsta
  - baytsc
  - bayhno
  - bayvoel
  - bayveg
  - bayg
  - bay
  - trbay
  - trias
  - trift
  - trbnw
  - lkbnw
  - laebnw
  - lbbnw
  - lbanw
  - larnw
  - l88nw
  - lronw
  - lrenw
  - crbnw
  - lrbnm
  - xa1
  - xii
  - xiii
  - x8im
  - r8in
  - w81n
  - 8ln
  - 81in
  - ruin
  - k5in
  - hain
  - hamiv
  - hiv
  - hdin
  - koin
  - kolm
  - volk
  - molik
  - holm
  - nola
  - noin
  - rcin
  - mcinz
  - mainsz
  - minsk
  - mainza
  - marinze
  - marine
  - morin2
  - maiing
  - r8ln
  - r81
  - k01
  - k614
  - 7610
  - k61d
  - k81d
  - k86g
  - k817
  - 81
  - kc
  - ho
  - ksho
  - ksaha
  - kshah
  - ksb
  - bsh
  - asoh
  - joh
  - bfp
  - bza
  - lva
  - kba
  - k8m
  - k5lm
  - 255m
  - h4lm
  - hlum
  - k5n
  - 5
  - he
  - hepc
  - kl
  - cln
  - udln
  - auln
  - rz
  - kz
  - kd
  - me
  - miel
  - km
  - kzm
  - kur
  - da
  - lax
  - lvah
  - lvit
  - k6lu
  - kowu
  - koll
  - kallm
  - k3in
  - x51n
  - m81n
  - x81n
  - 817
  - e137
  - k81f
  - kg19
  - k8145
  - 7869
  - 7602
  - boem
  - baym
  - hampr
  - hammer
  - wimmer
  - haupt
  - bayverg
  - bamberg
  - bauburg
  - braeburg
  - braarburg
  - kaarburg
  - seaarburg
  - sharburg
  - bearburg
  - barmburg
  - barburs
  - baarburgs
  - paarburg
  - marburg
  - wazburg
  - 8arburg
  - s8harburg
  - saearburg
  - seearburg
  - seeburg
  - sherburg
  - soarburg
  - searbburg
  - saarburg
  - beaarburg
  - beirburg
  - bergburg
  - beerburg
  - beeburg
  - buekeburg
  - lueneburg
  - balueneburg
  - nbalueneburg
  - bueckerburg
  - bueckeburg
  - buechelburg
  - buechelberg
  - buergburg
  - bauernburg
  - baaerburg
  - baarburg
  - bzaarburg
  - b8arburg
  - barbburg
  - barthburg
  - barburg
  - bassburg
  - bamburg
  - homburg
  - hamburg1
  - hamburger
  - hamburgaz
  - hamburg
  - kahamburg
  - 2vahamburg
  - lyahamburg
  - lvvahamburg
  - lviihamburg
  - lvfhamburg
  - hvahamburg
  - dvahamburg
  - ivahamburg
  - lvhhamburg
  - bvahamburg
  - vahamburg
  - ighamburg
  - lvghamburg
  - lvahamburg
  - nvahamburg
  - ahahamburg
  - kshahamburg
  - kshaharburg
  - lvdhamburg
  - lghamburg
  - lgheimburg
  - harburg
  - gaerburg
  - baernburg
  - bayerburg
  - berburg
  - bebraurg
  - seaburg
  - sarburg
  - sassburg
  - salzburg
  - lgsalzburg
  - saoeburg
  - garburg
  - serburg
  - seabrurg
  - searburg
  - sedanburg
  - secerburg
  - sicherburg
  - sacharburg
  - schaarburg
  - staarburg
  - sparburg
  - darburg
  - baerburg
  - bremburg
  - preiburg
  - freiburgb
  - freiburgbf
  - freiburgbsg
  - freiburgba
  - freiburgibr
  - freiburglr
  - freiburger
  - freiburg
  - rieiburg
  - rreibur
  - nienburg
  - niebuerg
  - freiberg
  - lafreiburg
  - freiburgbr
  - freiburgilbr
  - feiburgibr
  - freiburgbrsg
  - frohburgibr
  - brauburg
  - beaurburg
  - braunburg
  - boarburg
  - b8harburg
  - bharburg
  - baarbur
  - barbure
  - barbours
  - warburg
  - boorburg
  - baaerbarg
  - baselburg
  - schwarburg
  - schwaburg
  - sarbrueg
  - saarbrug
  - sarrebrug
  - sarbruegk
  - hamburgi
  - amberg
  - amnsberg
  - arnsperg
  - arnsbera
  - ainsberg
  - hrnsberg
  - hannsberg
  - landsberg
  - ansberg
  - arnsoerg
  - arnsborg
  - arnswerg
  - arnsberg
  - ambsberg
  - amtsberg
  - amtsbuero
  - arosberg
  - amsberg
  - amtberg
  - arnberg
  - starnberg
  - arnsherg
  - ahrnsberg
  - hinsberg
  - honsberg
  - ahnstberg
  - aarnsberg
  - rparnsberg
  - rparnswerg
  - regarnsberg
  - regamsberg
  - amtbery
  - ansbetra
  - ansbetrag
  - ansbetung
  - ansbetzung
  - ansbetrae
  - hannsbery
  - barbierg
  - barbier
  - 8aarbvrg
  - wuerzburg
  - lgwuerzburg
  - beeerbung
  - bemersburg
  - barbarus
  - bayern
  - bayerndt
  - bayverf
  - bayvergst
  - bafoeg
  - tham
  - ddorf
  - edorf
  - dudorf
  - doerf
  - woelf
  - goerz
  - joetz
  - goetze
  - noetv
  - 14510
  - 24310
  - 21710
  - 2101n
  - 21715
  - a1725
  - 23415
  - 21985
  - 11905
  - 2121905
  - d24910
  - d25210
  - d24914
  - c2910
  - vb30
  - e4334
  - e6364
  - b808
  - rb802
  - rb502
  - rb534
  - rb571
  - 14426
  - c4421
  - c2441
  - 14924
  - e2074
  - e8503
  - heimt
  - heimat
  - weimar
  - venmar
  - heimes
  - heeres
  - trhenn
  - via6
  - bhmf
  - schwab
  - schre
  - schrein
  - sschreien
  - sschreiber
  - sschreiben
  - schreiber
  - schreibt
  - sschreiten
  - schweiz
  - schwerin
  - soest
  - press
  - thoel
  - trzor
  - tresor
  - trluener
  - kruken
  - krausen
  - kzgusen
  - koenig
  - bkoeln
  - bvakoeln
  - ovdkoeln
  - ofdkoeln
  - ofjkoeln
  - ofgkoeln
  - oftkoel
  - oftdkoeln
  - afdrkoeln
  - hvakoeln
  - bvainkoeln
  - rpkoeln
  - ebkoeln
  - labnwbr
  - lbbnwbrd
  - labnwbrdd
  - labnwbrd
  - lranwbrd
  - lronwbrdd
  - lr8nwbrd
  - lranwbrdd
  - lronwbrd
  - tr8nwbrd
  - tranwbrd
  - lrenwbrdd
  - lranwbrdol
  - labnwbrdol
  - koelnarh
  - koelnlv
  - koelnlva
  - b2748
  - b2706
  - 3hft
  - lahav
  - k2100
  - c5182
  - buerg
  - wuert
  - puett
  - buero
  - kreisso
  - kreisisr
  - kreisusa
  - freib
  - paris
  - kshaosn
  - kshabonn
  - kshahann
  - kshahannst
  - kshahamm
  - kshhamm
  - kshahammp
  - kshahamry
  - kshahamm80
  - kshahanau
  - bschahann
  - kshatei
  - doppel
  - koeppel
  - hfs18
  - he618
  - portal
  - bachem
  - hachim
  - hachur
  - haecher
  - hoechler
  - bmtub4
  - bhfub3
  - bmfivbf
  - bhfvt34
  - bhfvt840
  - bhfvt84
  - bhfvr4
  - bhfvt4
  - dshfvb3
  - trassamt
  - traensamt
  - targensamt
  - fritz
  - d12720
  - e7309
  - c3362
  - 5425
  - e2186
  - abend
  - anbund
  - anbunde
  - anbundes
  - bundes
  - landes
  - linden
  - london
  - lingen
  - lueingen
  - jubingen

In [62]:
matched_normalized = set(df_matches_2['CompensationOffice1'].apply(normalize).unique().tolist())
gt_normalized = set(normalize(x) for x in gt_completed if isinstance(x, str))
known = gt_normalized | matched_normalized

names_to_drop = set()
for cluster in clusters[1:]:  # skip cluster 0
    cluster_set = set(cluster)  # already normalized (you passed normalize().unique() in)
    
    # Check if any member is a known/matched entry
    if cluster_set & known:
        # Drop all members that are NOT in the known set
        names_to_drop.update(cluster_set - known)

# Filter df_unmatched_filtered
mask = ~df_unmatched_filtered['CompensationOffice1'].apply(normalize).isin(names_to_drop)
df_unmatched_filtered = df_unmatched_filtered[mask].reset_index(drop=True)



print(len(df_unmatched_filtered))
print(len(df_unmatched_filtered['CompensationOffice1'].unique()))

89736
22319

In [ ]:
#TODO: how can we decide which entries to keep and which to drop in the remaining clusters?

# Clustering Placenames

In [63]:
from scipy.spatial.distance import squareform
from scipy.cluster.hierarchy import linkage, fcluster
from flair.data import Sentence
from flair.models import SequenceTagger
import matplotlib.pyplot as plt
from scipy.cluster.hierarchy import dendrogram

In [64]:
# function to predict the location entities from a list of compensation office names using the flair NER model for German
def predict_loc_ners(name_list):
    tagger = SequenceTagger.load("flair/ner-german")
    predictions = []
    for office_name in name_list:
        office_text = str(office_name).strip()
        if not office_text:
            continue

        sentence = Sentence(office_text)
        tagger.predict(sentence)

        for span in sentence.get_spans('ner'):
            if span.get_label('ner').value == 'LOC':
                predictions.append(span.text)
    return predictions

In [65]:
# updated normalisation function to keep whitespaces
def normalize(s):
    if not isinstance(s, str):
        return ""
    s = s.lower()
    replacements = {
        "ä": "ae", "ö": "oe", "ü": "ue", "ß": "ss"
    }
    for k, v in replacements.items():
        s = s.replace(k, v)
    s = unicodedata.normalize("NFKD", s)
    s = re.sub(r'[^a-zA-Z\s]', '', s)
    s = re.sub(r'\s+', ' ', s).strip()
    return s

In [66]:
# predict loc ners for the extracted compensation office names
leftover_office_names = df_unmatched_filtered['CompensationOffice1'].unique().tolist()
leftover_office_names = [normalize(name) for name in leftover_office_names if str(name).strip()]

loc_ners = sorted(set(predict_loc_ners(leftover_office_names)))
print(f'Total unique LOC entities: {len(loc_ners)}')
loc_ners

2026-04-17 09:15:56,176 SequenceTagger predicts: Dictionary with 19 tags: O, S-LOC, B-LOC, E-LOC, I-LOC, S-PER, B-PER, E-PER, I-PER, S-ORG, B-ORG, E-ORG, I-ORG, S-MISC, B-MISC, E-MISC, I-MISC, <START>, <STOP>
Total unique LOC entities: 1246

['aachen',
 'aachen rhein',
 'aegypten',
 'ahrnsberg',
 'aichach',
 'aisch',
 'ajzenberg',
 'alfeld',
 'alsterdorfer strasse',
 'alsterstr sprinkenhof',
 'altenburg',
 'altenkirchen',
 'altenkirchen westerwald',
 'altenkirchenwesterwald',
 'altonaerstr sprinkenhof',
 'altstaedter strasse',
 'amberg',
 'amden',
 'amerik',
 'ammergau',
 'ammerland',
 'amsterdam',
 'amtsberg',
 'andpfalz',
 'ankershagen',
 'ansbach',
 'ansbach muenchen',
 'ansbach wuerttemberg',
 'ansbach wuerzburg',
 'anslamtduesseldorf',
 'aoefw rhein pfalz',
 'arburg',
 'arnabera',
 'arnaberg',
 'arnach',
 'arnach muenchen',
 'arnachorg',
 'arnberg',
 'arneberg',
 'arneberg duesseldorf',
 'arneberg muenchen',
 'arnheberg',
 'arnheim',
 'arnhem',
 'arnobera',
 'arnsberg',
 'arnsberg duesseldorf',
 'arnsberg westfalen',
 'arnsbergduesseldorf',
 'arnshagen',
 'arnshausen',
 'arnshausen duesseldorf',
 'arnsherg',
 'arnshofen',
 'arnswald',
 'arnswald duesseldorf',
 'arnswald weimar',
 'arnswalde',
 'arnswalde duesseldorf',
 'arnswalde weimar',
 'arnswerg',
 'arosa',
 'aschberg',
 'aschendorf',
 'auerbach',
 'augsburg',
 'augsburg muenchen',
 'augsburgostfranken',
 'aurich',
 'aurichostfriesland',
 'auschwitz',
 'australien',
 'baaerbarg',
 'baarburg',
 'baastrup',
 'bad aibling',
 'bad godesberg',
 'bad homburg',
 'bad kreuznach',
 'baden',
 'badenbaden',
 'badenstuttgart',
 'badenwuerttemberg',
 'badenwuerttemberg karlsruhe',
 'baerburg',
 'baernburg',
 'bamberg',
 'bamberg deutschland',
 'bamberg muenchen',
 'barbburg',
 'barburg',
 'barthburg',
 'basel',
 'baselburg',
 'bassburg',
 'bauernburg',
 'bayerburg',
 'bayern',
 'bayern pfalz',
 'bayernfaiz',
 'bayernfreiburg',
 'bayernpfaelz',
 'bayernpfalz',
 'bayernpfaz',
 'bayernplatz berlin',
 'bayerns',
 'bayernstatz',
 'bayernstuttgart wuerttemberg',
 'bayertches',
 'baym',
 'bayreuth',
 'bayreuth ansbach',
 'bearingburg',
 'bedburg',
 'beeburg',
 'beeskow',
 'begbraeisdorf',
 'beirburg',
 'belsen',
 'bemersburg',
 'benin',
 'bentheim',
 'bergburg',
 'berlin',
 'berlin ansbach',
 'berlin berlin',
 'berlin charlottenburg',
 'berlin neustadt',
 'berlin saarburg',
 'berlin wilhelmsruh',
 'berlinbrandenburg',
 'berlincharlottenburg',
 'berlingsen',
 'berlinhalbz',
 'berlinhalensee',
 'berlinhamburg',
 'berlinkoeln',
 'berlinmainz',
 'berlinnrw',
 'berlinpfalz',
 'berlinpfz',
 'berlinplatz',
 'berlinpreuss',
 'berlins',
 'berlinwilmersdorf',
 'berneberg',
 'betzdorf',
 'bielefeld',
 'bielefeldstadt',
 'bielfeld',
 'bildesheim',
 'birkenfeld',
 'blankenburg',
 'bocholt',
 'bochum',
 'bodensee',
 'boeslar',
 'bonn',
 'bonn berlin',
 'bonn rheindorfstrasse',
 'bonnstadt',
 'borna',
 'braeburg',
 'brandenburg',
 'braubach',
 'braubach koblenz',
 'brauburg',
 'braunau',
 'braunburg',
 'braunfels',
 'braunmuehlweg',
 'braunschweig',
 'braunschweighannover',
 'braunschweigland',
 'braunschweigstadt',
 'bregenz',
 'breisgau',
 'bremen',
 'bremen neustadt',
 'bremenhaven',
 'bremens',
 'bremerhaven',
 'bremervoerde',
 'bremke',
 'breslau',
 'brombachaven',
 'bromberg',
 'broya',
 'bruehl',
 'bruenn',
 'bruennberg',
 'bruennhagen',
 'bruesseldorf',
 'brunsberg',
 'brunswick',
 'bstadtsteinach',
 'buchenwald',
 'budapest',
 'buechelburg',
 'bueckeburg',
 'bueckerburg',
 'bueckingen',
 'buedelsheim',
 'buedesheim',
 'buergburg',
 'bullay',
 'bundesheim',
 'bundesrepublik deutschland',
 'burgdorf',
 'burgdorfhann',
 'burgenland',
 'buxtehude',
 'bzk',
 'chemnitz',
 'chicago',
 'claenburg',
 'cloppenburg',
 'coeiholz',
 'coesfeld',
 'coeslarn',
 'cottbus',
 'cuxhaven',
 'czernowitz',
 'dachau',
 'dannenberg',
 'danzig',
 'danzigstadt',
 'darmstadt',
 'darmstadtkoblenz',
 'darmstadtstadt',
 'ddr',
 'delft',
 'delmenhorst',
 'delmenhorstoldenburg',
 'desheim',
 'desheimstadt',
 'dessau',
 'desseldorf',
 'detmold',
 'detroit',
 'detroit usa',
 'deutschland',
 'deutschlandberlin',
 'deutschlanddorf',
 'deutschlandpfalz',
 'diepholz',
 'dinslaken',
 'donau',
 'doppelmelung',
 'dortmund',
 'dotternhausen',
 'dresden',
 'dudelfstadt',
 'dudersdorf',
 'duderstadt',
 'duerenldorf',
 'duesseldorf',
 'duesseldorf aachen',
 'duesseldorf arnsberg',
 'duesseldorf berlin',
 'duesseldorf hildesheim',
 'duesseldorf huettenstrasse',
 'duesseldorf kassel',
 'duesseldorf mainz',
 'duesseldorf messkirch',
 'duesseldorf muenchen',
 'duesseldorf poststrasse',
 'duesseldorf stuttgart',
 'duesseldorf westerwald',
 'duesseldorfberlin',
 'duesseldorfhamm',
 'duesseldorfkoeln',
 'duesseldorfland',
 'duesseldorfstadt',
 'duisburg',
 'dusseldorf',
 'dwdberlin',
 'ebersbachbaden',
 'eichstaettpfalz',
 'eilenkircheneinsberg',
 'eilenkirchenheinsberg',
 'einbeck',
 'emmendingen',
 'england',
 'ennepperuhrkreises',
 'erfurt',
 'erfurt ansbach chamnitz',
 'erfurt astchemnitz',
 'eschwege',
 'ettlingen',
 'euskirchen',
 'fallingbostel',
 'faulenstrasse',
 'fellbach',
 'fernsberg',
 'flenkberg',
 'flensburg',
 'floersheim',
 'frankenburg',
 'frankf am main',
 'frankfurt',
 'frankfurt am main',
 'frankfurt am rossebertstr',
 'frankfurt gruneburgweg',
 'frankfurt hessen',
 'frankfurt main',
 'frankfurt werra',
 'frankfurt west',
 'frankfurt wiesbaden',
 'frankfurtam main',
 'frankreich',
 'franzfurt',
 'freckenhorst',
 'freiberg',
 'freiburg',
 'freiburg berlin',
 'freiburg karlsruhe',
 'freiburgbr karlstrasse',
 'freiburgbreisgau',
 'freiburgkarlsruhe',
 'freilandpfalz',
 'freising',
 'friedrichshain',
 'friesland',
 'frnakfurt hessen',
 'fuernsberg',
 'fuerstenberg',
 'fuerstenfeldbruck',
 'fuerth',
 'fulda',
 'gailburgschaumburg',
 'gailscn schnaumburg',
 'gailsh schaumburg',
 'ganderhsheim',
 'ganderkesheim',
 'gandersheim',
 'garsch',
 'geileinkirchchenheinsberg',
 'geileinkirchenheinsberg',
 'geilekirchenheinsberg',
 'geilekirchheinsberg',
 'geilenkirchen',
 'geilenkircheneinsberg',
 'geilenkirchenheinsberg',
 'geilenkirchenheinsbergund',
 'geilenkirchensheinsberg',
 'gelsenkirchen',
 'gelsenkirchenheinsberg',
 'gera',
 'gera schauburg',
 'gera schmiedeberg',
 'geraschweinfurt',
 'gerlin',
 'germany',
 'giessen',
 'giessenheim',
 'giessenkirchenheinsberg',
 'giessheim',
 'gifhorn',
 'gildesheim',
 'glatz',
 'glatz schauburg',
 'glatzschaumburg',
 'glatzschmiedeberg',
 'glatzschweidnitz',
 'glauchau schauburg',
 'goelleland',
 'goeppingen',
 'goerlitz',
 'goettingen',
 'goettingenschaumburg',
 'goettingenschmalkalden',
 'goettingenstadt',
 'goettlingen',
 'goettlingenstadt',
 'goetttingen',
 'goetttingenstadt',
 'goja syke',
 'goldstein',
 'gooya',
 'goslar',
 'goslari',
 'goslarsland',
 'goslarstadt',
 'gotha',
 'goya',
 'goya syke',
 'graetz',
 'graetz schauburg',
 'graetzsch',
 'graetzschaumburg',
 'graetzschschaumburg',
 'grafenau',
 'grafenberger allee',
 'graffchaft hoya',
 'graffloch',
 'grafschaumburg',
 'grafsh schaumburg',
 'grafshschaumburg',
 'graftsch schnaumburg',
 'graftschschaumburg',
 'graisch',
 'gratsch',
 'grevenbroich',
 'griesbach',
 'griesbachschmiedeberg',
 'griesch',
 'griesheim',
 'grossalmeroey',
 'grosschaft goya',
 'grossdeich',
 'grossherzogtum baden',
 'grosshoeft',
 'grossschaeumburg',
 'grossschauenburg',
 'grossschoenebeck',
 'grotzsch schauburg',
 'gruenberg',
 'gruenburgweg',
 'grueneburgweg',
 'gruenwald',
 'gruneburgweg',
 'grunenburgerweg',
 'grunenburgweg',
 'guedesheim',
 'gueldensheim',
 'gueldesheim',
 'guetersloh',
 'gutenbergstrasse',
 'haardt',
 'hagen',
 'haifa',
 'hailbronn',
 'hainfeld',
 'halbenreuth',
 'halbesheid',
 'haldensleben',
 'halle saale',
 'hallesaale',
 'haltenscheid',
 'hamburg',
 'hamburg adolphschoenfelderstrasse',
 'hamburg alstaedter strasse',
 'hamburg alsterdamm',
 'hamburg alsterdamm spitalhof',
 'hamburg alsterstrasse',
 'hamburg altstaedter',
 'hamburg altstaedter strasse',
 'hamburg dreschbahn',
 'hamburg sprinkenhof',
 'hamburgland',
 'hameln',
 'hamerau',
 'hamm',
 'hammelburg',
 'hammelnstadt',
 'hammstadt',
 'hammwestfalen',
 'hampelstrasse',
 'hannover',
 'hannover itzehoe',
 'hannover koblenz',
 'hannover osnabrueck',
 'hannover uelzen',
 'hannoverhannover',
 'hannoverherrenhausen',
 'hannoverkaltenkirchen',
 'hannoverkassel',
 'hannoverkoeln',
 'hannoverkreis',
 'hannoverland',
 'hannoverlangenhagen',
 'hannoverlueneburg',
 'hannovermisburg',
 'hannoverschauensee',
 'hannoverschoeneweide',
 'hannoverstadt',
 'hannstadt',
 'hanover',
 'harburg',
 'harrenberg',
 'hasstupelstrasse',
 'hauptzollamt berlin',
 'hausdorfer strasse',
 'haussdorf',
 'havel',
 'hechingen',
 'heidelberg',
 'heilbronn',
 'heimburg',
 'heineberg',
 'helmsstedt',
 'helmstedt',
 'hemmerden',
 'herford',
 'herne',
 'hessen',
 'hessen duesseldorf',
 'hessen pfalz',
 'hessenberg',
 'hessendpfaz',
 'hessenkassel',
 'hessennassau',
 'hessenpfalz',
 'hiesbaden',
 'hildesheim',
 'hildesheim berlin',
 'hildesheim lueneburg',
 'hildesheim muenchen',
 'hildesheim neustadt',
 'hildesheimmarburg',
 'hildesheimmarienburg',
 'hildesheimmarienenburg',
 'hildesheimstadt',
 'hilrathausen',
 'hinwil',
 'hirschberg',
 'hobelewitz',
 'hoblinz',
 'hochheim',
 'hoelzn',
 'hoexter',
 'hoexter detmold',
 'hoexteramt',
 'hohenlohe',
 'hohenzollern',
 'holland',
 'holzminden',
 'homburg',
 'hoxter detmold',
 'hoya',
 'hoya syke',
 'hoyerswerda',
 'illinois',
 'innsbruck',
 'isarloh',
 'ischl',
 'isenburg',
 'iserlohn',
 'islerlohn',
 'israel',
 'italien',
 'jena',
 'johannesburg',
 'kaerlsruhe',
 'kaerntenpfalz',
 'kaerntenplatz',
 'kaiserslautern',
 'kaiserstuhl',
 'kalklsruhe',
 'kallshausen',
 'kammerwaldau',
 'kanada',
 'kardrheinwestfalen',
 'karlruhe',
 'karlruhebaden',
 'karlshruhe',
 'karlsrhein',
 'karlsruhe',
 'karlsruhebaden',
 'karlsruhefreiburg',
 'karlsruhes',
 'karlsruhestuttgart',
 'karlstadt',
 'kassai',
 'kassel',
 'kassels',
 'kelheim',
 'kheinlandpfalz',
 'kiel',
 'kielburg',
 'kingston',
 'klagenfurt',
 'klopffenburg',
 'kloppeburg',
 'kloppenburg',
 'koblence',
 'koblens',
 'koblenz',
 'koblenz berlin',
 'koblenz neustadt',
 'koblenz rheinlandpfalz',
 'koblenz saarburg',
 'koblenzdarmstadt',
 'koblenzsaarburg',
 'koblenztrier',
 'koeln',
 'koeln aachen',
 'koeln ansbach',
 'koeln arnsberg',
 'koeln berlin',
 'koeln darmstadt',
 'koeln detmold',
 'koeln duesseldorf',
 'koeln hildesheim',
 'koeln huersberg',
 'koeln koenigstrasse',
 'koeln lva',
 'koeln lyon',
 'koeln muenchen',
 'koeln reichsland',
 'koeln rhein',
 'koeln rheinland',
 'koeln riehler',
 'koeln roentgenplatz',
 'koeln rudolfplatz',
 'koeln saarbruecken',
 'koeln stettin',
 'koeln sudetengau',
 'koelnarnsberg',
 'koelnduesseldorf',
 'koelner strasse',
 'koelnhamburg',
 'koelnhensberg',
 'koelnrheinland',
 'koeniglandplatz berlin',
 'koenigsberg',
 'koenigshuetteoberschlesien',
 'koenigsklostergasse',
 'koenigstein',
 'koernstrasse',
 'koetenberg',
 'kolnstadt',
 'kolomea',
 'korbethamerseburg',
 'krefeld',
 'krefelduerdingen',
 'kreisvilsbofen',
 'kreuznach',
 'krim',
 'kshalueneburgland',
 'ksharotenburg',
 'kurland',
 'laendersommi',
 'landau',
 'landau pfalz',
 'landaupfalz',
 'landesbeirksstelle',
 'landesboirkstelle',
 'landesbozirksstelle',
 'landesherikksstelle',
 'landeshezkirksstelle',
 'landesjustizvlindau',
 'landeskirchsstelle',
 'landjustizvludwigsburg',
 'landsberg',
 'landsberger strasse muenchen',
 'landshut',
 'leerostfriesland',
 'leipzig',
 'lemgo',
 'leoberschuetz',
 'lichtenau',
 'lichtenberg',
 'liegnitz',
 'limau',
 'limburg',
 'lindau',
 'linden',
 'lindenau',
 'lingen',
 'linnich',
 'linz',
 'lippe',
 'lohr main',
 'london',
 'lorrain',
 'los angeles',
 'ludwigburg',
 'ludwigsburg',
 'ludwigshafen',
 'ludwigshafen am rhein',
 'ludwigshurg',
 'ludwigslust',
 'luebbecke',
 'luebeck',
 'luedenscheid',
 'luedwigsburg',
 'lueneburg',
 'lueneburg karlsruhe',
 'lueneburgland',
 'lueneburgstadt',
 'luettich',
 'luxemburg',
 'lvahamburg',
 'lvaoldenburg',
 'lvghamburg',
 'lvhhamburg',
 'lvhrheinlandpfalz',
 'lviihamburg',
 'lvvahamburg',
 'lyon',
 'magdeburg',
 'main',
 'mains',
 'mainz',
 'mainz berlin',
 'mainz koblenz',
 'mainz neustadt',
 'mainz rheinlandpfalz',
 'mainz saarburg',
 'mainzneustadt',
 'mainzrhein',
 'mannheim',
 'mannover',
 'marburg',
 'marburglahn',
 'marseille',
 'maulbronn',
 'mecklenburg',
 'meiningen',
 'meppen',
 'merseburg',
 'messkirch',
 'meuselberg',
 'miesbach',
 'minden',
 'minsk',
 'mittelbach',
 'mittelfranken',
 'mittelrhein',
 'moedling',
 'moellendorf',
 'moenchengladbach',
 'moerlen',
 'monaco',
 'montabaur',
 'mosbach',
 'moskau',
 'muelheim',
 'muelheimruhr',
 'muenchen',
 'muenchen ansbach',
 'muenchen arolserstrasse',
 'muenchen asslingstrasse',
 'muenchen auerbachstrasse',
 'muenchen duesseldorf',
 'muenchen meiserstrasse',
 'muenchen muenchen',
 'muenchen neustadt',
 'muenchen nord',
 'muenchen prinzludwigstrasse',
 'muenchen stuttgart',
 'muenchen trier',
 'muenchen wuerttemberg',
 'muenchen wuerzburg',
 'muenchenarchisstrasse',
 'muenchenarnsberg',
 'muenchengladbach',
 'muenchenheim',
 'muenchenland',
 'muenchennord',
 'muenchenpfaelz',
 'muenchhausen',
 'muenden',
 'muenster',
 'muesseldorf',
 'munster',
 'nassau rheinlandpfalz',
 'nauheim',
 'naumburg',
 'neapel',
 'neubrandenburg',
 'neuburg',
 'neudietendorf',
 'neuendettelsau',
 'neuendorf',
 'neuisenburg',
 'neumark',
 'neumarkt',
 'neuoesterreich',
 'neusadec',
 'neusadte',
 'neusidler strasse',
 'neusiedel',
 'neusiedl',
 'neuss',
 'neussadt',
 'neussalden',
 'neustadt',
 'neustadt neustadt',
 'neustadthannover',
 'neustadtkaiserslautern',
 'neustadtwesterwald',
 'neustiftgasse',
 'neuwalde',
 'neuwied',
 'new york',
 'niederlande',
 'niederoesterreich',
 'niederoesterreich neustadt',
 'niederrad',
 'niedersachsen',
 'niedersachsenbezirks',
 'niedersachsenkammer',
 'niedersachsenosnabrueck',
 'niedersachsenpraesidex',
 'niedersachsenpraesidium',
 'niedersaechs',
 'niederschlesien',
 'niederschlesien neustadt',
 'nienburg',
 'niesbaden',
 'noerdlingen',
 'noertenhardenberg',
 'noertheim',
 'nordamerika',
 'nordbaden',
 'nordbayern',
 'norddeutschland',
 'norddeutschwestfalen',
 'nordendenham',
 'nordenham',
 'nordenheim',
 'nordhamburgwestfalen',
 'nordhausen',
 'nordhausen westfalen',
 'nordhausenwestfalen',
 'nordheim',
 'nordheimwestfalen',
 'nordhorn',
 'nordlande',
 'nordrheinwestfalen',
 'nordrheinwestfalen duesseldorf',
 'nordrheinwestfales',
 'nordrwestfalen',
 'nordstadt',
 'northeim',
 'northeim wesel',
 'northheim',
 'norwegen',
 'nrw',
 'nuernberg',
 'nuernberg a d weinstrasse',
 'nuernberg a d weserstrasse',
 'nuernberg koblenz',
 'nuremberg',
 'nussdorf',
 'oberbayern',
 'oberbayernstadt',
 'oberbillingshausen',
 'oberbronn',
 'oberdenburg',
 'oberfinanzdirektion brueckenstrasse',
 'oberhausenrheinland',
 'oberholtz',
 'oberholz',
 'oberpfalz',
 'oberrode',
 'oberschleissheim',
 'obersholz',
 'oedfreiburg',
 'oesterreich',
 'oettingen',
 'offenbach',
 'oldeburg',
 'oldenburg',
 'oldenburgstadt',
 'oltenburg',
 'oranienburg',
 'oschersleben',
 'osieholtz',
 'osierhoelz',
 'osierholtz',
 'osnabrueck',
 'osnabrueckland',
 'osnabrueckstadt',
 'osnaubruck',
 'osnaubrueck',
 'osseholtz',
 'osseiholz',
 'ostalbischland',
 'osterholz',
 'osterode',
 'ostfriesland',
 'ostfrieslandaurich',
 'paderborn',
 'paltingbostal',
 'palzberlin',
 'paris',
 'parnsburg',
 'passau',
 'pfalz',
 'pfalz berlin',
 'pfalzberlin',
 'pflzberlin',
 'pforzheim',
 'pfullingen',
 'philadelphia',
 'phoenandpfalz',
 'phoenix',
 'phoenixfeliz',
 'phoenixlandfialz',
 'phoenixlandpfalz',
 'phoenlandpfalz',
 'pirmaasens',
 'pirmasens',
 'pirnsmasensrheinpfalz',
 'plauen',
 'plaz berlin',
 'pommern',
 'pommersfelden',
 'posen',
 'posenberg',
 'potsdam',
 'potsdam berlin',
 'potsdam brandenburg',
 'potsdamer str',
 'praehmberg',
 'prag',
 'prensborg',
 'prenzlau',
 'preussberg',
 'preussen',
 'preusseniplatz',
 'preussenpalast',
 'preussenpalz',
 'preussenpfaelz',
 'preussenpfalz',
 'preussenplatz',
 'preussenpolen',
 'preussenpolz',
 'preussenpommern',
 'preussenpotsdam',
 'preussens',
 'preussland',
 'preusslandpfalz',
 'preusslandpolz',
 'priesland',
 'prinzberg',
 'prinzenberg',
 'prinzludwigstrasse muenchen',
 'prinzregentenplatz berlin',
 'prnneberg',
 'pruesborg',
 'prussia',
 'prussia west',
 'pyrmont',
 'rabieningstrasse',
 'radolfzell',
 'rathaus berlin',
 'ravensburg',
 'recklinghausen',
 'redlinhausen',
 'regbraunschweig',
 'regensburg',
 'regierungsbezirksamt neustadt',
 'regionalverwaltungsamt neustadt',
 'reinickendorf pankow',
 'remagen',
 'remsberg',
 'remscheid',
 'remshalden',
 'rendsburg',
 'rennberg',
 'rensburg',
 'reutlingen',
 'rhbplzberlin',
 'rhein',
 'rhein flaezberlin',
 'rhein palast berlin',
 'rhein palz berlin',
 'rhein pfalz',
 'rhein pfalzberlin',
 'rhein pilsenberlin',
 'rhein pilszberlin',
 'rhein plaetz',
 'rheinampfalz',
 'rheinhessen',
 'rheinl pfalz',
 'rheinl pfalz neustadt',
 'rheinland',
 'rheinland foelz',
 'rheinland fulda',
 'rheinland muenchen',
 'rheinland pfalz',
 'rheinland piass',
 'rheinland westfalen',
 'rheinlande',
 'rheinlandespolen',
 'rheinlandfuerth',
 'rheinlandhamburg',
 'rheinlandhessen',
 'rheinlandholz',
 'rheinlandnr',
 'rheinlandostz',
 'rheinlandpfalz',
 'rheinlandpfalz berlin',
 'rheinlandpfalz berlin neustadt',
 'rheinlandpfalz koblenz',
 'rheinlandpfalz muenchen',
 'rheinlandpfalz neustadt',
 'rheinlandpfalz saarburg',
 'rheinlandpfalzberlin',
 'rheinlandpfalzuebernommen',
 'rheinlandplatz',
 'rheinlandpreussen',
 'rheinlandrhein',
 'rheinlandrwz',
 'rheinlandwestfalen',
 ...]

In [ ]:
#splitting up leftover names into the ones containing locs and ones that are not
leftover_office_names_with_loc = [name for name in leftover_office_names if any(loc in name for loc in loc_ners)]
leftover_office_names_without_loc = [name for name in leftover_office_names if not any(loc in name for loc in loc_ners)]

print(len(leftover_office_names))
print(f'Number of office names containing LOC entities: {len(leftover_office_names_with_loc)}')
print(f'Number of office names not containing LOC entities: {len(leftover_office_names_without_loc)}')

22319
Number of office names containing LOC entities: 14675
Number of office names not containing LOC entities: 7644

In [32]:
leftover_office_names_without_loc

['kreisausserhelfsausschuebe',
 'kreissonderhilfsschuebe peine',
 'bayerische kartei',
 'entschaedigungsamt',
 'kreissonderhilfsausschuss springe',
 'landesentschaedigungsausschuss',
 'bayerisches landesamt fuer digungssam',
 'regierungsbezirkamt fuer wiedergutmachung',
 'kreissozialhilfsausschuss land hadeln',
 'entscheidungsbehoerde',
 'bayerisches landesamt fuer verfolgte des nationalsozialismus',
 'kreisonderhilfsausschuss',
 'regierungsbezirksamt fuer wiedergutmachung',
 'wiedergutmachung und verwaltete vermoegen',
 'kreissozialhilfsschul',
 'st h',
 'stadtholm',
 'landesbehoerde von hauptregistatur',
 'schwab',
 'landesamt fuer statistik und wirtschaft',
 'landsosamt fuer wiedergutmachung und kontrollierte vermoegen',
 'kreisausserhelfsausschuss',
 'kn',
 'landesamt fuer kultur und wissenschaft',
 'hng',
 'bayerisches verwaltungsamt',
 'st h b',
 'polizeipraesidium a d',
 'kreissozialhilfsausschub peine',
 'bayhues',
 'kreissozialhilfsausschub melle',
 'bayerisches landesentschaedigungsgesetz',
 'muenchner hauptstelle',
 'der regierungspraefident',
 'bayerisches landesamt fuer jugend und verwahrlosungsschutz',
 'bayerisches hauptescheid',
 'kreissonderhilfsausschuss hild marb',
 'kreisonderbehilfsausschuss',
 'doppel meldung',
 'bayerische landesstelle',
 'syke',
 'bayerisches landesamt fuer entschaedigungen',
 'regierungsbezirksamt fuer wiedergutmachung und kontrolliertes vermoegen',
 'kreissozialamt syke',
 'bayerisches landesamt fuer den wiedergutmachung',
 'regierungsbezirk fuer wiedergutmachung und verwaltete vermoegensnachlaesse',
 'ksha darmenberelbe',
 'bay kartei',
 'kreissozialhilfsausschub',
 'sondervermoegens und bauverwaltung',
 'landesamt fuer die verwaltung der bundesregierung',
 'hess staatsministerium he darstadt',
 'kreissozialhilfesausschuss muenner',
 'darlehensanstalt',
 'wiedergutmachung',
 'kreissozialamt mepen',
 'st h b',
 'landesamt fuer vertriebenenwesen',
 'bundesstelle',
 'kreissozialhilfsausschuss melle',
 'kreissozialamt leer',
 'der regierungspraesidial',
 'kreisausserhilfsausschuess',
 'kreissozialhilfsausschuss hild marb',
 'landeszentrale fuer die opfer des nationalsozialismus',
 'landesentschaedigungsamt zentral registrator',
 'kreissonderhilfsausschue',
 'landesentschaedigungsamt des verfolgten',
 'regpraesident praesident des verw bezirks',
 '',
 'landeszentrale fuer die verguetung von opfern des nationalsozialismus',
 'kreissozialhilfsausschuss winsenl',
 'az',
 'regierungsbezirksamt fuer wiedergutmachung und verwaltete vermoegensm',
 'kreissonderhilfsausschuss syk',
 'tr bayerisches landesamt fuer verfolgtenfragen',
 'muenchner versicherungsamt',
 'neuried',
 'e',
 'regierungspraesidium fuer wiedergutmachung und verwaltung des bundes',
 'bayerisches landesentschaedigungsgesamt',
 'ko',
 'staatsministerium des innern',
 'ksha mappen',
 'st h w',
 'landesamt fuer die rueckversicherung',
 'bayerisches landesamt fuer verfolgten',
 'kreissonderhilfsschuele cellestadt',
 'ansbetretten des bundesarchivs',
 'kreisausserordentlicher hauptschutz',
 'kalt',
 'kreissozialhilfsausschuss zellmerfeld',
 'kshc cellestadt',
 'bayerische landesentschaedigungsstelle',
 'ksha brake',
 'bayerisches archiv fuer sozialgeschichte',
 'regionalverwaltungsbehoerde fuer wiedergutmachung und verwaltete vermoegensangelegenheiten',
 'a',
 'ksha celleland',
 'regierungsbezirksamt fuer wiedergutmachung und vertriebene vermoegen',
 'kz',
 'doppelvermerk',
 'regierungsbezirksamt fuer wiedergutmachung und verwaltete vermoegenswiederbeschaffung',
 'bayerisches versaeumnisamt',
 'regpraesident praesident desverwbezirks',
 'ksha melle',
 'ferner bayerische kartei',
 'landesamt fuer vertriebenenwesen koellehohe',
 'bayerische landesanstalt fuer die opfer des nationalsozialismus',
 'regierungsbezirksamt fuer wiedergutmachung und verwaltete vermoegensausuebung a d weim',
 'regierungsbezirksamt fuer wiedergutmachung fuer verwaltete vermoegens',
 'kreissonderhilfsschuefe',
 'thisches',
 'der regierungspraesident dueren',
 'kreissozialhilfsausschuss peine',
 'kreissonderhilfsschuebe',
 'regpraesident praesident des verwaltungsbezirks',
 'an das amt des hohen kommissars der vereinten nationen fuer fluechtlinge',
 'dr mueller',
 'schw',
 'an den bundeskartellamt',
 'reichsentschaedigungsausschuss fuer die wiedergutmachung und verwaltung des vermoegens',
 'kreissozialamt emden',
 'regierungsbezirksamt fuer wiedergutmachung und verwalteter vermoegen',
 'ksha emden',
 'landesamt fuer die wiedergutmachung',
 'regierungsbezirksamt fuer wiedergutmachung und verwaltetes vermoegen',
 'deichmann',
 'dudersstadt',
 'bayerisches landesamt fuer regierung und verwaltung',
 'zentralanmeldestelle',
 'baygeschad',
 'kreissoenderhilfsausschuss',
 'regierungsbezirksamt',
 'regierungsbezirkssozialamt fuer wiedergutmachung und reparationen',
 'kreissozialhilfsausschuebe peine',
 'st h h',
 'regionalstelle fuer wiedergutmachung',
 'sondervermoegensu bauverwaltung',
 'amt regierungsbezirksamt fuer wiedergutmachung und kontrollierte vermoegen',
 'ksha leer',
 'regierungsbezirkssamt fuer wiedergutmachung und verwaltete vermoegen',
 'regierungsbezirk fuer wiedergutmachung und verwaltete vermoegen',
 'wehrmacht',
 'ravorsch landesentschaedigungsamt zentralregister',
 'bayerisches landesentschaedigungsbuero',
 'st h sch',
 'kreisausserordentliche hinterbliebenenbehoerde',
 'doppelvermelung',
 'kreissonderhilfsausschuebe',
 'ho bayerisches landesamt fuer vertriebene',
 'baytches',
 'r a finderthaber',
 'regierungsbezirk fuer wiedergutmachung und verwaltung vermoegens',
 'kreisonderrilfsausschuss',
 'bayer zent komp',
 'landesamt fuer den wiederaufbau',
 'anspruchsberechtigter',
 'rath kamilla joit',
 'kreisonderschutzbehoerde',
 'landesamt fuer die verwaltung',
 'regionalverwaltungsamt fuer wiedergutmachung und verwaltete vermoegen',
 'regierungsbezirkamt fuer wiedergutmachung und kontrollierte vermoegen',
 'landeszentrale fuer politische opferhilfe',
 'bayerisches landesamt fuer verfolgtenaufsorge',
 'kreissonderbehelfsausschuss',
 'bayerisches landesamt fuer verfolgtenaufwandsentschaedigung',
 'landesanstalt fuer die regelung von folgeleistungen',
 'sondervermoegens u bauerverwaltung',
 'regierungsbezirkamt fuer wiedergutmachung und verwaltete vermoegen',
 'bayerisches versicherungsamt',
 'bayerisches landesamt fuer schaedenfolgen',
 'st h h',
 'ksha norden',
 'bayerisches landeszentrum fuer die opfer des nationalsozialismus',
 'bayerisches landesamt fuer handesensschaedigungssammt',
 'landesamt fuer wiedergutmachung entschaedigungsbehoerde',
 'regierungsbezirksamt fuer wiedergutmachung und verwaltete vermoegen ad weinstr',
 'regierungsbezirksamt fuer wiedergutmachung und verwaltete vermoegensnachlaesse',
 'stadthetm',
 'landeszentrale fuer die verguetung',
 'ksha peine',
 'e',
 'amt fuer die wiedergutmachung',
 'landesamt fuer die vermoegensverwaltung',
 'han',
 'ksha col eland',
 'kn',
 'kreisonderrhilfsausschuss braukewesermarsch',
 'kreisondeserhifsausschuss brakewesermarsch',
 'c',
 'landesentschaedigungsgesetz',
 'bay',
 'regierungsbezirkskommission fuer wiedergutmachung verwaltete vermoegensnachlaesse und wohlfahrt',
 'regierungsbezirksamt fuer wiedergutmachung und verwaltete vermoegenswiederherstellung',
 'heimat',
 'regierungsbezirksamt fuer wiedergutmachung und verwandtes vermoegen',
 'bayerisches landesamt fuer kriegsopferfuersorge und kriegsopferhilfe',
 'kn',
 'regierung fuer wiedergutmachung und verwaltete vermoegen',
 'kreissozialamt wolfsenbuettel',
 'kreissozialhilfsausschub delmen',
 'bayerisches landesentschaedigungssamt muenchner',
 'hermannjuergen',
 'bundeskaertei',
 'regionalverwaltungsamt fuer wiedergutmachung und kontrollierte vermoegen',
 'hans prof weissbrod',
 'bv',
 'kreissozialhilfsausschuss dalmnendorf',
 'amt regierungsbezirksamt fuer wiedergutmachung und kontrolliertes vermoegen',
 'bay staatsministerium',
 'sth b',
 'muenchner verfolgungsausschuss',
 'riedmeier',
 'ksha hild marb',
 'ksha wittlage',
 'kreissonderhilfsausschuss norden',
 'trag dr w boehm',
 'bundeskartothek',
 'doppelvermoegensbehoerde',
 'kreissonderhilfsausschuss emden',
 'kreissonderhilfsausschuss verden',
 'landeszentrale fuer die verguetung der opfer des nationalsozialismus',
 'kreissozialhilfeauschuss melle',
 'praesidialamt',
 'ksha winsenluhe',
 'kreissohnhilfsausschuss',
 'kreissozialamt wesermuende',
 'landesamt fuer wiedergutmachung und kontrolliertes vermoegen',
 'ksha meppe',
 'regierungsbezirksamt fuer wiedergutmachung und verwaltete vermoegens',
 'steglitzbrueggel',
 'baydisches landesarchiv',
 'regionalverwaltungsbehoerde fuer wiedergutmachung und verwaltete vermoegen',
 'entschaedigungsbehoerde andesomt fuer die wiedergutmachung',
 'ksha verden',
 'landkreis osierholz',
 'regierungsbezirksamt fuer wiedergutmachung und vormoegen',
 'kreisausserordentliche hauptschutzstelle',
 'kreissozialhilfsausschuss wittlage',
 'stin',
 'finanzamt',
 'bundeskriegs',
 'bayhsta',
 'regierungsbezirk fuer wiedergutmachung und verfolgte verbrecher',
 'st h st',
 'kshd',
 'kreissozialhilfsschule celleland',
 'defmo',
 'kreissonderhilfsausschuss winsenl',
 'der regierungspraesident',
 'anstalt des bundes',
 'landesamt fuer die opfer des nationalsozialismus',
 'koenigshausenverlag',
 'kegierungsbezirk fuer wiedergutmachung und verwaltete vermoegen',
 'bayer landesonsozialamt',
 'sth',
 'kreissonderhilfsschuele',
 'kreissonderhilfsschul',
 'regierung provinz',
 'muenchner staatsministerium',
 'landesamt fuer vertriebenenfragen',
 'bayerisches landesamt fuer die opfer des nationalsozialismus',
 'bayerisches landesamt fuer die wiedergutmachung',
 'bhf',
 'der bundesminister der finanzen',
 'suchkartei fuer bez reg',
 'entschaedigungsbehoerde aarbuerg',
 'bmf vb',
 'bmfvb',
 'dshfvb',
 'bmf',
 'holm',
 'landeszentrale fuer die verguetung nationalsozialistischer opfer',
 'suedkartei fuer bez reg',
 'm',
 'brd',
 'der regierungspraesident dueren',
 'bmf vtb',
 'bayerische landesentschaedigungs und staatschuldenverwaltung',
 'begirussregierung',
 'bmf vbh',
 'bundesregierung',
 'bht',
 'bayerisches verfolgungsausschuss',
 'bezirkskammer fuer wiedergutmachung',
 'koenigliches preussisches staatsministerium fuer wiedergutmachung',
 '',
 'k',
 'bekirskregierung',
 'bhfub',
 'vb',
 'sachverstaendigenstelle fuer befindlichkeit',
 'lab nw br',
 'bayerisches landesamt fuer verfolgtenwesen',
 'tr nw brd',
 'bayerische landesentschaedigungs und staatschuldendienstverwaltung',
 'doppelmayr',
 'bhf vb',
 'bmf vb',
 'regierungsbezirksamt fuer wiedergutmachung und verwaltungsrechtliche angelegen koblentz',
 'hf',
 'lab nw brd',
 'bhf vb',
 'bayerische landesentschaedigungs und staatschuldendeverwaltung',
 'bafoe',
 'bayerisches landesamt fuer verfolgtenaufsicht',
 'tr',
 'kreisjugendamt lauf pegn',
 'gzd',
 'bmf ii b dfr',
 'ko',
 'bundesverwaltungsamt',
 'landesamt fuer finanzen landesentschaedigungsamt',
 'hf',
 'kin',
 'bhfvb',
 'hn',
 'entschaedigungsbehoerde fuer wiedergutmachung',
 'lab nw br dol',
 'dhf',
 'bmft vb',
 'staatliche anstalt fuer geisteskrank',
 'bezirksregierung d dort',
 'kn',
 'landesbezeichnungsstelle',
 'bundesk',
 'bay amt fuer vertriebene',
 'bhfvb',
 'bmtub',
 'bayerisches landesentschaedigungsamt ustaatschuldenvollmacht landesentschaedigungsamt',
 'regierung arnethorg messl',
 'bhfvt',
 'bhfvr',
 'bekannt',
 'v b',
 'hf',
 'bmfvb',
 'antigaststelle',
 'hoeherer kommissar der verwaltung fuer fluechtlinge',
 '',
 'dbhf',
 'bmfub',
 'kn',
 'nolu',
 'bmfub',
 'doppelmeidung',
 'landesstelle fuer die wiedergutmachung',
 'maximilianaaz',
 'm',
 'bhfubs',
 'bayer landesentschaedigungsstelle',
 'regierungsbezirkskammer fuer wiedergutmachung und verwaltete vermoegens',
 'bmfvb',
 'kreisonderhelfausschuss',
 'regierungsbezirksamt fuer wiedergutmachung und verwaltete vermoegensangelegenheiten',
 'sachbearbeitung fuer bez reg',
 'beg',
 'kreisondeserhifsausschuss',
 'ra weber',
 'bundeslaender',
 'rav webar',
 'he',
 'landesamt fuer das wiedergutmachungsverfahren',
 'tr haftbescheid',
 'bmp',
 'regionalbeirat fuer wiedergutmachung und verwaltung des haertefonds',
 'bnf',
 'haftbescheid',
 'bmfiv',
 'bmfvt',
 'klm',
 'sondervermoegens u bouverwaltung',
 'landesamt fuer finanzen',
 'reparatur praesident',
 'k m',
 'bayerisches landeszentrale',
 'waln',
 'landesbeiratssstelle',
 'k',
 'lab nw br dd',
 'amt fuer wiedergutmachung von korbienz',
 'nunbestimmtes ministerium der finanzen',
 'bm',
 'regierungsbezirksamt fuer wiedergutmachung und verwaltungsvormoegen koblentz',
 'bayerische staatsregierung',
 'bayerisches landesamt fuer wiedergutmachung',
 'landesbeirat fuer die wiedergutmachung',
 'landesamt fuer vertriebene fluechtlinge und kriegsgeschaedigte',
 'rundesministerium fuer finanzen',
 'ra pfort',
 'kohlwitz',
 'bhf vb',
 'c e',
 'bundeskriegsentschaedigung',
 'sachverstaendigenstelle fuer befristete',
 'landesbeauftragte fuer die opfer des nationalsozialismus',
 'bayerische staatsministerium',
 'bfd west',
 'bayerische landesentschaedigungs und staatsschuldenverwaltung',
 'bayerisches landesamt fuer jugend und verfassungsschutz',
 'an bundesarchiv',
 'km',
 'k n',
 'nshaetefonds',
 'sachkartei fuer bez reg',
 'heeresgruppe',
 'sachkartei fuer ber reg',
 'xn',
 'bezirksamt fuer wiedergutmachung r k lag mch',
 'bayerisches landesentschaedigungsmiet',
 'reichsministerium der finanzen',
 'nevrov',
 'bhf ub',
 'ksha vehta',
 'c',
 'kc',
 'landesamt fuer vertriebenenwiedergutmachung',
 'regierungsbezirksamt fuer wiedergutmachung und vermoegensangelegenheiten',
 'an bundesamt',
 'bhf vb',
 'bayerisches landesentscheidungsamt',
 'eg',
 'bmfva',
 'amt fuer wiedergutmachung von hoeblenz',
 'der runderminister der finanzen',
 'schwaburg',
 'bayerische landesentschaedigungs und staatschuldenerverwaltung',
 'sonnenvermoegensbauverwaltung',
 'bayerisches versoehnungsamt',
 'regionalverwaltungsbezirksamt fuer wiedergutmachung und verwaltete vermoegen',
 'der regierungspraefident dueren',
 'regierungsbezirkam',
 'landsesamt fuer zentralregistratur',
 'regierungsbezirkskammer fuer wiedergutmachung und verwaltete vermoegen',
 'regionalverwaltungsbehoerde fuer wiedergutmachung und versorgung',
 'ksha bersenbrueck',
 'hendel',
 'a',
 'oberfinanzdirektion rundesvarmogensabteilung',
 'regierungsbezirk fuer wiedergutmachung und vermoegensverwaltung',
 'beg',
 'bayerisches landesamt fuer verfolgungsgeschaefte',
 'lra nw br d',
 'kegierungsbezirksoamt fuer wiedergutmachung und verwaltete vermoegen',
 'a',
 'km',
 'kln',
 'der senator fuer arbeit landesamt fuer wiedergutmachung',
 'landesamt fuer die regelung von vermoegensfragen',
 'bundesamt fuer die verwaltung des bundes',
 'nazi victims compensation office',
 'hauptbeschaedigte',
 'honer kommissar der vereinten nationen fuer fluechtlinge',
 'bebra',
 'ausland',
 'amt fuer wiedergutmachung und verwaltete vermoegens',
 'kreissonderbehilfsausschuss jever',
 'ksha celleland',
 'hauptbesold',
 'koenigshausener',
 'landesherzoglich',
 'bayerisches landesentschaedigungsspnprzaska',
 'landesbehozirkstelle fuer die im kzdienst gestorbenen',
 'ksha cellestadt',
 'regpraesident praesident des vorwbezirks',
 'regierungspraesident',
 'sonderbevollmaechtigter fuer die wiedergutmachung',
 'bay zent stelle',
 'bayisches verfolgtenzentrum',
 'k',
 'tr bayerisches landesarchiv',
 'kreissozialamt cellestadt',
 'bundfinhin',
 'wie oben',
 'regpraesident praesident des wiedergutmachungsbeauftragten',
 'barburs',
 'schw landesamt',
 'regierungsbezirksamt fuer wiedergutmachung und verwalte vermoegen',
 'landesamt fuer verfolgtenfragen',
 'doppelmedung',
 'bundesverwaltung',
 'mundesministerium der finanz',
 'bayerisches landesamt fuer schaedenfolgen der nszeit',
 'bayerisches landesamt fuer geschaedigte',
 'oberfinanzdirektion',
 'ho landeszentrale fuer die opfer des nationalsozialismus',
 'hauptbescheid',
 'regierungsbezirksamt fuer wiedergutmachung und vermoegensverluste',
 'bayerisches verfassungsamt',
 'haftbescheinigung',
 'hohes kommissariat der vereinten nationen fuer fluechtlinge',
 'regierungsbezirksaemter fuer wiedergutmachung und vertriebenenwesen',
 'kreissozialamt stadt colle',
 'sondervermoegensu bauerverwaltung',
 'neue karten fuer die erben',
 'muench staatsministerium',
 'laendeszentrale fuer die opfer des nationalsozialismus',
 'kshacelleland',
 'doppelmeidlung',
 'dr bundesminister der finanzen',
 'doppelbelung',
 'bayerische landesentschaedigungs und staatssschuldenverwaltung',
 'oberbuergermeisteramt fuer wiedergutmachung und verwaltete vermoegen',
 'uro',
 'ksha',
 'sth st',
 'landesstelle fuer die belange der verfolgten des nationalsozialismus',
 'lg',
 'landesamt fuer vertriebenen',
 'bayerisches justizministerium',
 'regierungsbezirksamt fuer wiedergutmachung und verwesjte vermoegen',
 'k n',
 'hoeherer kommissar der vereinten nationen fuer fluechtlinge',
 'kreissonderhilfsausschuefs cellestadt',
 'ksh nord',
 'hoeherer kommissar der vereinigten nationen fuer fluechtlinge',
 'efrat',
 'regierungsbezirksamt fuer wiedergutmachung und verw vermoegen',
 'regpraesident praesident des verwaltungsgerichts',
 'ksha colleland',
 'abgabe an das regierungsbezirksamt fuer wiedergutmachung',
 'km',
 'kroko linla',
 'landeszentrale fuer politische opferfuersorge',
 'regpraesidient praesident des verwbezirks',
 'regionalverwaltungsbehoerde fuer wiedergutmachung und verwaltung von vermoegenswiedergutmachungsklagen',
 'the',
 'landesjustizverwaltung',
 'oen',
 'an bundeckartei',
 'united restitution office',
 'regionalverwaltungsbehoerde fuer wiedergutmachung und vermoegensverwaltung',
 'regierungsbezirksamt fuer wiedergutmachung und verwandte vermoegensangelegenheiten',
 'bay verwaltungsamt fuer die wiedergutmachung',
 'liegende i anmerkung welf',
 'heinrichbayerisches landesamt fuer die opfer des nationalsozialismus',
 'bayerisches verfolgungsaktenamt',
 'regierungspraesidium bw',
 'landesbeauftragte',
 'kreissozialamt mepplen',
 'bayer landeszentrale',
 'oberste entschaedigungsbehoerde',
 'landesbeauftragte fuer die wiedergutmachung schaltgarten',
 'st h',
 'landesamt fuer bayerische landesarchive',
 'regionalverwaltungsbezirk fuer wiedergutmachung und verfolgte verfolgung',
 'bundesministerium der fluechtlinge',
 'bayhuches landesamt fuer verfolgten',
 'kshc',
 'higher commissioner of the allied powers for refugees',
 'lustmaenn',
 'munzeministerium der finanzen',
 'kreissozialamt celle',
 'landesbeiratstelle',
 'johanna irma erlanger geb',
 'bezirksamt fuer wiedergutmachung trl',
 'deutsche bundesrepublik',
 'fuss',
 'kreissozonderhilfssausschuss',
 'regierungsbezirksamt fuer wiedergutmachung und verwaltungsvermoegensverwaltung',
 'bayerisches landeszentrum fuer opferberatung und opferhilfe',
 'doppelmesslung',
 '',
 'bayerische versicherungsanstalt',
 'landesamt fuer kriegsopfer und kriegsversehrte',
 'kshc celleland',
 'landesamt fuer die rueckstellung',
 'hessisches staatsministerium',
 'bayerisches landesamt fuer vertriebenenfragen',
 'brigitte schmidt geb hauptert manfred goldschmidt guenter goldschmidt',
 'hauptstelle',
 'landesamt fuer den wiedergutmachung',
 'd e',
 'landeesamt fuer die wiedergutmachung tobingen',
 'regionalverwaltungsgericht fuer wiedergutmachung und verwaltete vermoegenskoerperschaften',
 'vereinten kriegsopferfuersorge',
 'beeerbung',
 'k',
 'gestapo bayerische kartei',
 'kreissonderhilfsausschuss',
 'sondervermoegens u bauverwaltung',
 'oberfinanzdirektion bundesvermoegensabteilung',
 'ksha cologneland',
 'rechtsanwaltschaft fuer wiedergutmachung',
 's schreiber',
 'kreissozialamt collelend',
 'doppelmeier',
 'doerf',
 'kroa linda',
 'si',
 'schw',
 'bundeskaissei',
 '',
 'in',
 'kreissonderhilfsausschuss celleland',
 'honer kommissar der vereinigten nationen fuer fluechlinge',
 'kreissonderhilfsausschuss cellestadt',
 'sondervermoegens und bauerverwaltung',
 '',
 'st h',
 'der regierungspraesident duereloort',
 'lezirksamt fuer wiedergutmachung',
 'regierungsbezirksamt fuer wiedergutmachung und vermoegensverwaltung',
 'bayerisches landesentschaedigungsfonds',
 'sarbrueg',

In [ ]:
# check office names without loc against names from german postcodes csv from github

german_postcodes = pd.read_csv('german-postcodes.csv', sep=';') 
valid_german_places = set(german_postcodes['Ort'].str.lower())
for name in leftover_office_names_without_loc:
    if any(re.search(rf"\b{re.escape(str(place))}\b", name) for place in valid_german_places):
        print(name)

kreissonderhilfsschuebe peine
kreissonderhilfsausschuss springe
kreissozialhilfsausschub peine
kreissozialhilfsausschub melle
syke
kreissozialamt syke
kreissozialhilfsausschuss melle
kreissozialamt leer
neuried
kalt
ksha brake
ksha melle
kreissozialhilfsausschuss peine
kreissozialamt emden
ksha emden
kreissozialhilfsausschuebe peine
ksha leer
ksha norden
ksha peine
kreissonderhilfsausschuss norden
kreissonderhilfsausschuss emden
kreissonderhilfsausschuss verden
kreissozialhilfeauschuss melle
ksha verden
holm
regierungsbezirksamt fuer wiedergutmachung und verwaltungsrechtliche angelegen koblentz
kreisjugendamt lauf pegn
regierungsbezirksamt fuer wiedergutmachung und verwaltungsvormoegen koblentz
bebra
kreissonderbehilfsausschuss jever
bay zent stelle
kreissozialamt celle
kroa linda
deutsches zentrales stelle
ksha stadt celle
kreissonderhilfsausschuss land holzen
acco rech jabotinskii
ksha springe
an bunde
kreissozialamt peine
kreisausserhilfsausschuss winsen luhe
kreissozialhilfsausschuss stadt celle
kreissozialhilfeausschuss stadt celle
kreisonderhilsausschuef peine
kreissonderhilfsausschuss peine
kreissonderhilfsausschuss winsen luhe
kreissozialhilfsschuebe peine
zentrale stelle fuer die wiedergutmachung
kreissozialamt melle
kreissozialhilfsausschuss jever
kshm melle
kreissozialamt wieden
regierung praehserg staats
hauptzustaendige stelle fuer wiedergutmachung und verwaltete vermoegenskohlen
kreissozialhilfsschule peine
kreissonderhilfsausschuss melle
kreissozialamt springe
regierung brakel mff
kreissozialhilfsschulung peine
norden
ksha brakel
kreisonderrhilfsausschuss celle land
kreissozialhilfsausschuss norden
kreissozialhilfsausschuss emden
kreissonderhilfsausschub springe
ksha brake io
springe
kreissonderhilfsschuele peine
ksha syke
brand
nt fuer die verfolgten aus dem ehemaligen reich
amt fuer wiedergutmachung essen
kshv verden
kreissonderhilfsschuele norden
kreisonderhlfasschuf peine
landkreis grafschaft hoy
kreisonderrhilfsausschuss peine
ksha winsen luhe
ksha winsen luehe
elsa pappenheim walter joachimsthal ua
ksha celle
regierung finanzabteilung welt
kreissonderhilfsausschuss leer
oed
kreissozialhilfeauschuss leer
kreissozialhilfsausschuss leer
kreissozialamt verden
kreis linsengericht
kreissozialhilfsausschuss springe
gob goldberg
amt fuer wiedergutmachung in essen
amt fuer wiedergutmachung der stadt essen
brake io
kreisausserhelfsausschuss peine
kreissozialhilfsausschuss landkreis grafschaft hoy
verden
der oberkreisdirektor dezernat fuer wiedergutmachung in brake il
hauptzustaendige stelle
kreissozialhilfsausschuesse peine
roth
kreissozialhilfsausschuss celle
regierungspraesidium prensbereich wehr
kreissonderhilfesausschuss springe
kreissonderhilfsausschuss winsen luhe
kreissonderhilfsausschuss stadt celle
regierungspraesidium wehr
kreissonderhilfsschuefe peine
lg weiden
restitutionsamt wied
kreisonderschutzbehoerde peine
hauptzustaendige stelle fuer wiedergutmachung und verwaltete vermoegen
und verwaltete vermoegen neuried ad weinstr
amt fuer wiedergutmachung stadt essen in essen
kreissonderbehilfsausschuebe peine
amt fuer wiedergutmachung in essen nach hier uebernommen
hof
bezirksamt fuer wiedergutmachung verenig koblentz
an bunde deckartei
rey frieda ruth geb ehrmann kuhlmann jnge geb ehrmann ehrmann doris renate
kreissonderhilfsausschuebe springe
kreissozialamt zell
eros linau
ksha celle
deutsches zentrales stelle fuer opfer der nationalsozialistischen verfolgung
kreissonderhilfsausschuss jever
traeger koblentz
kreissonderhilfsausschue peine
ellrich
kreissozialhilfsausschuss brake io
kreisverwaltung springe
kreissonderhilfesausschuss brake io
suhl
emden
kreissoenderhilfsausschuss brake io
kreissonderhilfsausschuss vechta
rosenthal
kreissonderhilfsausschuesse peine
kreisonderhilfsausschuss stadt celle
regierungsbezirksamt fuer wiedergutmachung und verwaltete vermoegen neudorf a d weinstr
der oberkreisdirektor dezernat fuer wiedergutmachung in brake i l
kreisonderhilfsausschuss brake ewesermarsch
hauptzustaendige stelle fuer wiedergutmachung
regierung armeekorps wehr
ksha celle hamororer
braunlage
barb burg
amt fuer wiedergutmachung essen
erlangen
kreissozialamt brake io
kreissozialhilfsschuss peine
ksha zell
norden
kreissonderhilfsausschuss dippoldiswalde
ksha peine
hauptzustaendige stelle fuer wiedergutmachung und verwaltung der kostenerstattung
bayerisches reich
aesiermann amon wehr
kreissozialhilfsschutz peine
kreissonderhilfsschule brake wesermarsch
kreissonderhlfasschub emden
landsmannschaft der im deutschen reich verfolgten juden
bayer zent stelle
oed e
rechtsanwaltskanzlei landeck muehlen
kreisonderrhilfsausschuss stadt celle
ra kerpen cremet
kreissozialamt jever
sprung
kreissonderhilfsschuebe springe
afw mettmann
bza zellendorf
kreisausserhilfsausschuss brake
ksha braunlage
kreissonderbehilfsausschuebe leer
amtsvormundschaft erkelenz
kreissonderhilfsausschuss leer ostfriesl
rey prof wunnicke
schutz landesentschaedigungsamt
kraatz
gill b rommerskirchen gilllerhoefe
kreisonderhilfsausschuesse peine
bza zeulenroda
kreisonderschutzbehoerde melle
regierung bruessel wied
kreisonderrhfsausschub emden
kreissonderhilfsschuele emden
kreissonderhilfsausschub melle
kreissonderhilfsausschuss syke
kreissonderhilfsschuefs peine
kreissozialamt celle land
kreissonderhilfsausschuebe peine
ankunft bunde
stadt essen amt fuer wiedergutmachung
ksha dippoldiswalde
ksha menden
zentrale stelle der landesjustizverwaltungen fuer die wiedergutmachung
baumgarten
kreissozialhilfsschuessel peine
kreissonderhilfesauschuss springe
neue karte fuer die erbin da der bish ast zwischen verstorben ist
kreissozialhilfsschule zell erfeld
regierungsbezirksamt fuer wiedergutmachung und verwaltete vermoegensgegenstaende a d weinstadt
neue karten fuer die erben da ast zwischen verstorben
gutach
oberfinanzdirektion erlangen
bayerische landesentschaedigungs und staats schuldenverwaltung
regierungsbezirk kaernten fuer wiedergutmachung und verwaltete vermoegen koblentz
regierungsbezirk fuer wiedergutmachung und verwaltete vermoegen traun
kreissozialhilfsausschuss leer ostfriesl
kreissozialamt brake
bay praes lindhorst
rey dr linnros
kreisonderhilfsausschuss verden
kreissozialamt winsen luhe
kreissozialhilfsausschuss wermarsch in brake
kreis melle
aegiernung pruefera wehr
koppatz
leer ostfrld
willi o ernst o gustav o
kreissozialhilfsausschub leer
kreisonderrhilfsausschuss leer
ksha emden
ksha brake i o
landessozialgericht essen
kreissohnderhilfsausschuss peine
ehrmann jlse rey ruth frieda gebehrmann dreier elise emilie geb ehrmann dreier elise emilie geb ehrmann ehrmann anna karlilme brusse hedwig hermine gebehrmann werner jrmna liselotte gebehrmann ehrmann renate doris
amt fuer wiedergutmachung halle wesff
regierung f von wang welf
kreissozialhilfsausschub stadt celle
afw essen
ksha celle stadt
hof gruenbaum
abend
regierungsbezirksamt fuer wiedergutmachung und verwaltete vermoegen kempten
amt f wiedergutmachung in essen
barth
ksha stadt celle
d roth
kreissozialamt stadt celle
kreissonderhilfsausschue springe
kreissozialhilfsausschuss landkreis oschatz
kupferberg
holm
ksha rothenburg
kreissonderhilfesausschuss peine
kreissonderhilfsausschub landkreis oschatz
ksha vechta
regierung p von wang weltf
deutsches reich
kreissozialamt leer ostfriesl
kreisausserhelfsausschuss norden
kreissonderhilfsausschuss celle stadt
kreissozialamt brakel
regierungsbezirk wehr
regierung juelich welt
ansprueche der ast bezirksamt fuer wiedergutmachung
springe
kreissonderhilfsausschuss leer osterprlcl
aur i ostfildern
strodam an lauen
kreisverwaltung schleiden wiedergutmachungssamt
kreissozialhilfssauschuss syke
ksha emden
kreissozialhilfeauschuss landkreis grafschaft hoy
ksha bad oldesloe
kreissozialhilfssauschuss peine
kreissozialamt landkreis grafschaft hoy
kreissonderhilfsschuele springe
von dem ministerium der finanzen rom
regierung anklam meckl
ksha hanau
landeszentrale und stelle fuer die wiedergutmachung
kreissonderhilfsausschuss celle
kreissonderhilfssausschuss melle
regierungsbezirkamt fuer wiedergutmachung und verwaltete vermoegen netstaedte ad wutach
roggenstein
amt fuer wiedergutmachung essen
kreisonderhilfsausschuss brake io
kreissozialamt witten
reichsentschaedigungsbehoerde fuer die im deutschen reich verfolgten juden
stolpe
kreissozialhilfeauschuss peine
landesamt fuer vermerk und schutz
kreisssonderhilfssausschuss stadt celle
kreissozialhilfsausschub verden
kreissoenderhilfsausschuss peine

In [ ]:
#predict loc ners for the gt compensation office names and the manually added names
gt_normalized = set(normalize(x) for x in gt + list_corrections if isinstance(x, str))
loc_ners_gt = sorted(set(predict_loc_ners(gt_normalized)))

loc_ners_gt = sorted(set(loc_ners_gt))
print(f'Total unique LOC entities: {len(loc_ners_gt)}')
loc_ners_gt

2026-04-17 11:27:15,798 SequenceTagger predicts: Dictionary with 19 tags: O, S-LOC, B-LOC, E-LOC, I-LOC, S-PER, B-PER, E-PER, I-PER, S-ORG, B-ORG, E-ORG, I-ORG, S-MISC, B-MISC, E-MISC, I-MISC, <START>, <STOP>
Total unique LOC entities: 126

['aachen',
 'adolfwestphalstrasse',
 'ansbach',
 'arnsberg',
 'arnsberg seibertzstrasse',
 'aurich',
 'aurichostfriesland',
 'bad kreuznach',
 'badenwuerttemberg',
 'badenwuerttemberg stuttgart',
 'bayern',
 'berlin',
 'berlin stauffenbergstrasse',
 'bielefeld',
 'bonn',
 'brauerkantstrasse',
 'braunschweig',
 'breisgau',
 'bremen',
 'bremenhaven',
 'bremerhaven',
 'bremerhaven bremerhaven',
 'brunswicker strasse',
 'chemnitz',
 'cottbus',
 'darmstadt',
 'darmstadt luisenplatz',
 'darmstadt rheinstrasse',
 'delmenhorst',
 'detmold',
 'detmold leopoldstrasse',
 'duesseldorf',
 'duesseldorf cecilienallee',
 'erfurt',
 'fehrbelliner platz',
 'fellbach',
 'frankfurt',
 'freiburg',
 'freiburg kaiserjosephstrasse',
 'friedrichebertstrasse',
 'goettingenstadt',
 'goslar',
 'grafsch schaumburg',
 'grapengiesserstrasse',
 'hamburg',
 'hamburg adolphschoenfelderstrasse',
 'hamburg altstaedter',
 'hamburg altstaedterstr sprinkenhof',
 'hamburg altstaedterstrasse',
 'hamburg barmbeker',
 'hamburg hufnerstrasse',
 'hamburg kaiserwilhelmstrasse',
 'hamburger strasse',
 'hannover',
 'hannover auestrasse',
 'hannover hannover',
 'hannoverland',
 'helmstedt',
 'hessen',
 'hildesheim',
 'hildesheim hildesheim',
 'hildesheimstadt',
 'hohenbergerstrasse',
 'jenaer strasse',
 'kaiserslautern',
 'karlsruh',
 'karlsruhe',
 'kassel',
 'kiel',
 'koblenz',
 'koblenz koblenz',
 'koeln',
 'landau',
 'landauer strasse',
 'ludwigshafen',
 'lueneburg',
 'lueneburg lueneburg',
 'magdeburg',
 'mainz',
 'mainzer strasse',
 'mariatheresiastrasse',
 'montabaur',
 'muenchen',
 'muenchen alexandrastrasse',
 'muenchen meiserstrasse',
 'muenchen prinzludwigstrasse',
 'muenster',
 'neumarkt',
 'neustadt',
 'neuwied',
 'niedersachsen',
 'nordbaden',
 'nordrheinwestfalen',
 'oldenburg',
 'osnabrueck',
 'osnabrueckstadt',
 'potsdamer strasse',
 'prinzludwigstrasse',
 'rhein',
 'rhein pfalz',
 'rheinlandpfalz',
 'rheinlandpfalz berlin',
 'rostock',
 'saarbruecken',
 'saarbruecken hochstrasse',
 'saarbruecken saarbruecken',
 'saarburg',
 'saarburg saarburg',
 'saarburgd saarburg',
 'saarland',
 'saarlandes',
 'schleswigholstein',
 'sprinkenhof',
 'stade stade',
 'stuttgart',
 'stuttgarts',
 'theodorheussstrasse',
 'theodortantzenplatz',
 'trier',
 'tuebingen',
 'tuebingen friedrichstr tuebingen',
 'warburg',
 'weinstrasse',
 'weinstrasse friedrichebertstrasse',
 'weinstrasse neustadt',
 'wiesbaden']

In [ ]:
#split up the office names containing locs into locs that are in gt and ones that are not
leftover_office_names_with_loc_ingt = [name for name in leftover_office_names_with_loc if any(loc in name for loc in loc_ners_gt)]
leftover_office_names_with_loc_notingt = [name for name in leftover_office_names_with_loc if not any(loc in name for loc in loc_ners_gt)]

print(len(leftover_office_names_with_loc))
print(len(leftover_office_names_with_loc_ingt))
print(len(leftover_office_names_with_loc_notingt))

14675
11729
2946

In [28]:
df_matches_correctable = lev_matches.dropna()
print(len(df_matches_correctable))
df_matches_impossible = lev_matches[lev_matches['MatchedOffice'].isna()]
impossible_list = df_matches_impossible['CompensationOffice1'].tolist()
print(len(impossible_list), len(set(impossible_list)))
# print the unique values in the impossible list and their counts in descending order
for office in sorted(set(impossible_list), key=impossible_list.count, reverse=True):
    count = impossible_list.count(office)
    print(f"{office}: {count}")

145672
52099 7005
Bayerische Kartei: 9925
Bundeskartei: 4884
HNG: 3402
Bayerisches Landesarchiv: 2585
Kreissozialamt: 958
Bundesamt: 834
KSHA: 750
Kreissozialhilfsausschuss: 712
Köln, Riehler Pl.2, 5000 Köln 1: 477
Doppelmeldung: 449
Bundesarchiv: 408
Erfurt: 386
An Bundeskartei: 371
BHF: 346
BEG: 340
Bayerisches Hauptstaatsarchiv: 321
Magistrat der Stadt Bremen: 306
Montabaur: 291
BMF: 269
K81: 268
Frankfurt/M.: 267
K81n: 267
Ansbach: 257
Sondervermögens-u. Bauverwaltung: 242
Bayerisches Landesamt: 241
Aurich/Ostfriesland: 235
Magistrat der Stadt Bremenhaven: 224
VB3: 218
Bayerisches Verfolgtenamt: 209
Landeszentrale für die Vergütung von Opfern des Nationalsozialismus: 206
KSH: 205
Köln, Riehler Pl. 2, 5000 Köln 1: 204
Watenstedt-Salzgitter: 185
Bayerisches Landeszentrum für die Opfer des Nationalsozialismus: 181
Pirmasens: 181
Kaiserslautern: 178
Bayerisches Landesamt für die Opfer des Nationalsozialismus: 173
Höherer Kommissar der Vereinten Nationen für Flüchtlinge: 166
Kreissonderhilfsschübe: 163
EG: 160
Der Niedersächsische Minister des Innern: 159
Burgdorf: 152
Bayerisches Verwaltungsamt: 137
Tr.: 137
Bekannt: 123
Köln, Riehlstr. Pl.2, 5000 Köln 1: 122
Bundesverwaltungsamt: 117
Aurich i.Ostfriesl.: 114
BMF - VB4: 109
K61n: 108
Bebra: 104
K81m: 101
Bayerisches Landesamt für Verfolgte des Nationalsozialismus: 100
Nienburg-Weser: 94
Bay: 94
Suchkartei für Bez. Reg.: 93
KSHA Göttingen: 93
K8In: 85
Stadt Bonn: 84
Bad Kreuznach: 80
KSHA Wilhelmshaven: 79
Neuwied: 78
Kreisaußerhelfsausschuss: 76
Kreis Lindau: 73
Doppelmeldung München: 73
He: 72
K61: 71
Sondervermögens- u. Bauverwaltung: 71
ERFURT: 71
Regierung Ansbach: 70
Bayerisches Verfolgtenzentrum: 70
Bundesstelle: 69
Landkreis Osterholz: 69
Aurich / Ostfriesland: 66
Kreissonderhilfsschul: 66
Höherer Kommissar der Vereinigten Nationen für Flüchtlinge: 65
Bayerisches: 63
DOPPELMELDUNG: 62
Frankfurt a.M.: 61
KSHA Gifhorn: 60
KSHA Goslar-Land: 60
KSHA Emden: 58
Doppel Meldung: 58
Doppelvermerk: 58
Ludwigshafen am Rhein: 57
Kreisaußerhilfsausschuss: 56
BHT: 56
KSHA Celle/Land: 54
KSHA Winsen/Luhe: 52
Regierung Aachen (Wf.): 52
United Restitution Office, Frankfurt/Main, Grüneburgweg 119: 51
Aussensenstelle Freiburg i.Br.: 51
Bayerisches Verfolgungsausschuss: 50
Bundeskartothek: 48
Hauptbescheid: 48
KSHA Soltau: 48
Sondervermögens- und Bauverwaltung: 46
Frankfurt: 45
Doppelmeldung Köln: 45
Doppelmeldung Berlin: 45
Baastrup: 44
KSHA Springe: 44
Rostock: 43
Nordhorn: 41
Kreisonderrhilfsausschuss: 41
KSHA Wittmund: 41
Sondervermögens-u. Bauerverwaltung: 41
KSHA Watenstedt-Salzgitter: 40
Bayerisches Verfolgungsamt: 39
KSHa: 39
Braunau: 39
Anstalt des Bundes: 39
KSHA Holzminden: 38
Wolfenbüttel: 38
K817: 38
Doppelmeldung Stuttgart: 38
LG: 38
K51n: 37
Hamburg 36, Drehbahn 36IV: 37
An Bundesamt: 36
Anspruchsberechtigter: 36
Frankfurt a. M.: 36
KSHA Zellerfeld: 36
Stadthaus: 36
KSHA Neustadt a.Rbge.: 35
KSHA Hild. Marb.: 35
Nordden: 34
KSHA Northheim: 34
Landkreis Göttingen: 34
KSHA Cloppenburg: 34
BHF - VB4: 34
Landesstelle für die Regelung von Schadensersatzansprüchen: 33
BHF-VB3: 33
Hauptstelle: 32
Hamburger Stiftung Hilfe für NS-Verfolgte: 32
München 2, Arcisstraße 11: 32
Landeszentrale für die Vergütung: 32
Bonn: 31
BMF-VB4: 31
K51: 31
KSHA Ammerland: 31
Stuttgart-S, Neue Weinsteige 21: 30
KSHA Burgdorf: 30
HNC: 30
Frankfurt-Main: 29
Köln, Riehlstr. Pl. 2, 5000 Köln 1: 29
Nazi Germany Compensation Office: 29
KSHA Mepen: 29
BFD West: 28
Doppelmeldung Koblenz: 28
KSHA Winsen-Luhe: 28
Bundessstelle: 28
Bezirksamt von Koblenz: 28
Königreich-Preußen Berlin: 28
Kreissonderhilfsschüle: 28
Minister des Innern: 27
Frankfurt am Main: 27
Hu: 27
Service-Center Köln: 27
BMF-UB4: 27
Ludwigshafen a. Rh.: 27
Kreissozialhilfsschul: 26
KSHA Wesermünde: 26
KSHA Nörtheim: 26
Kreissonderhilfsausschub: 26
United Restitution Office, Frankfurt/Main, Gruneburgweg 119: 26
Kreissozialhilfeausschuss: 26
Sondervermögens-U. Bauverwaltung: 25
KSHA Uelzen: 25
Bundeszentralstelle für Verfolgte: 25
Hamburger Stiftung: 25
Landau/Pfalz: 25
Regierung München (Wf.): 25
Doppelmeier: 25
KSHA Wolffenbüttel: 25
Syke: 24
Landesbeiratstelle: 24
Hauptstaatsarchiv München: 24
Landeszentrale für die Vergütung der Opfer des Nationalsozialismus: 24
51: 23
Sachverständigenstelle für Bez. Reg.: 23
Landesbezirksstelle: 23
Soest: 23
KSHA Delmenhorst: 23
Einbeck: 23
Schw.: 23
United Restitution Office: 22
Stiftung: 22
Landesverwaltungsamt München: 22
K8lm: 22
BHF-VB4: 22
Landesbeirat: 22
: 21
Aurich I. Ostfriesland: 21
Landesamt für: 21
Doppelmayr: 21
United Restitution Office, Frankfurt/M., Grünburgweg 119: 21
KSHA Northeim: 21
Holm: 21
KSHA Colle/Land: 21
Höherer Kommissar der Vereinten Nationen für Flüchlinge: 21
BHF-UB4: 21
KSHC: 21
Doppelmelung: 21
A.Z.: 20
Landesarchiv München: 20
Kn: 20
Altenkirchen Westerw.: 20
Alfeld/Leine: 20
BRD: 20
KSHA Veckta: 20
Regierung München: 20
KSHA Friesland: 20
K8: 19
Ausgl. Amt Bremen: 19
United Restitution Office, Frankfurt: 19
BayHStA: 19
Dudersfeld: 19
An Bundesarchiv: 19
K81a: 19
DHF: 19
K814: 19
Köln, Riehler Pl.2, 5000 Köln: 19
Si.: 19
K810: 19
Doppelmeldung Hamburg: 18
Kreis Lindenau: 18
United Restitution Office, Frankfurt/M., Gruneburgweg 119: 18
Bayerische Landeszentrale für die Opfer des Nationalsozialismus: 18
Bayerisches Verfolgungsausschussamt: 18
H81n: 18
KSHA Münden: 18
Landesamt für Kultur und Wissenschaft: 18
KSHA Nordhorn: 18
K61m: 18
Landeszentrale für die Opfer des Nationalsozialismus: 18
BEG-Kartei: 18
Bielefeld: 18
Bundesverwaltungsamt Köln: 18
Kln: 17
BMF - VBH: 17
Aurich I.Ostfriesland: 17
81: 17
Friesland: 17
KSHA Neustadt a. Rbge.: 17
Doppelvermerk München: 17
Frankfurt/Main: 16
Kreissonderhilfsschule: 16
Landeszentrale für politische Opferhilfe: 16
Holz: 16
Alfeld: 16
B.V.: 16
K 51: 16
KSHA Ganderkesheim: 16
Bundeskärtei: 16
Bayerisches Landeszentrum für Opferberatung und Opferhilfe: 16
Doppelvermerkung: 16
KSHA Winsen/L.: 15
Ländeszentrale für die Opfer des Nationalsozialismus: 15
Niedersachsen-Präsident / Präsident des Landes: 15
Landau/Pf.: 15
51n: 15
United Restitution Office, Frankfurt/M.: 15
United Restitution Office, Frankfurt/M., Grüneburgweg 119: 15
Doppelvermögen: 15
Delmenhorst: 15
Stadtverwaltung Stadthagen: 15
Kreisonderhelfsausschuss: 15
K812: 15
K8m: 15
Kreissonderhilfsschüf: 15
Gifhorn: 15
KSHA Melle: 15
An Bundesekartei: 15
KSHA Mappen: 15
BMF - VB 4: 15
Landesamt: 15
Bundesländer: 14
Ve: 14
Regierung Bamberg: 14
Bayer. Landeszentrale: 14
Kreissonderbehelfsausschuss: 14
Köln, Riehler Pl.2: 14
Aurich i.Ostfriesland: 14
Bundeskammer: 14
BHF- VB4: 14
KSHA Diepholz: 14
Higher Commissioner of the United Nations for Refugees: 14
Landesverwaltungsamt München II: 13
Hohes Kommissariat der Vereinten Nationen für Flüchtlinge: 13
Gerichtsurteil: 13
KSHA Aschendorf/Ems: 13
Fallingbostel: 13
Aurich i. Ostfriesl.: 13
AfW Aachen-Stadt: 13
Landesbeiratssstelle: 13
K 81: 13
Wehrmacht: 13
KSHA Alfeld: 13
Wiedergutmachung und verwaltete Vermögen: 13
Doppel Meldung München: 13
Landesarchiv Muenchen: 13
Bayerisches Archiv für Sozialgeschichte: 12
Köln, Reichler Pl.2, 5000 Köln 1: 12
KSHA Wolfsenbüttel: 12
K816: 12
KSHA Stadt Hameln: 12
Landkreis Grafschaft Lippe: 12
Braunfels: 12
R81n: 12
Bayisches Landesarchiv: 12
KSHA Schaußburg-Lippe: 12
KSHA f.d. Reg. Bez. Hildesheim: 12
Deutsches Zentrales Stelle: 12
KSHA Verden: 12
Kreisonderschutzbehörde: 12
Landeszentrale für politische Opferentschädigung: 12
Sondervermögens-u. Baubewaltung: 12
Doppel Meldung Stuttgart: 12
KSHA Brake: 11
Aurich / Ostfriesl.: 11
DOPPELMELDUNG Berlin: 11
Haltestelle: 11
We: 11
Regional Office for Compensation and Administration of Assets, Mainz: 11
Bayerisches Verfolgten: 11
Aussensenstelle Freiburg: 11
Landesamt für Vertriebene, Flüchtlinge und Kriegsgeschädigte: 11
Doppelmeidung: 11
DOPPELMELDUNG München: 11
Bayerisches Landeszentrale: 11
Sondervermögens-Bauverwaltung: 11
Sondervermögens-u. Bäuerwaltung: 11
KSM: 11
Landkreis Grafschaft Goya: 11
Bavarian Compensation Office: 11
KSHA Schauburg-Lippe: 11
Bayerisches Landesamt für Verfolgtenaufwandsentschädigung: 11
Weimar: 11
R8ln: 10
Landesbeauftragte: 10
KSHA Minden: 10
Kreissonderhilfesauschuss: 10
KSHA Götttingen: 10
Ko: 10
Regionalverwaltungsbehörde für Wien: 10
KSHA Hamm: 10
BHF - VB3: 10
Wiedergutmachung, Stuttgart: 10
Bayer. Landesarchiv: 10
Regional Office for Compensation and Administration of Assets, Neustadt a.d. Weinstr.: 10
KSHA Celle-Land: 10
Bundesverwaltungsamt in Köln: 10
Kai: 10
Köln, Riehler Pl. 2: 10
Bundesarchive: 10
An Bundeseskartei: 10
Schwerin: 10
Burgdorf (Hann.): 10
KSHA Bremervörde: 10
DOPPELMELDUNG Köln: 10
K51m: 10
Regionalverwaltungsgericht Koblenz: 10
KSHA Cologne/Land: 10
K6: 10
Aussenstelle Freiburg i.Br.: 10
Der hessische Landtag: 10
Regierung Hessen: 10
Doppelmedlung: 10
BZK: 10
Doppelvermeldung: 10
K818: 10
Wittlage: 10
Wittmund: 9
Sen. f. Fin: 9
Krois Lindau: 9
Kreissonderhilfsschutz: 9
Braun: 9
Aussensenstelle Freiburg/Br.: 9
Bundes: 9
Doppelmelung München: 9
Landesjustizverwaltung: 9
Aussensestelle Freiburg i.Br.: 9
DM 500: 9
Holzminden: 9
Düsseldorfer Regierungspräsidium: 9
Sondervermögens- u. Bauerverwaltung: 9
KSHA Hameln-Pyrmont: 9
Beg: 9
Bundes-Verw.-Amt: 9
Landesamt für die Rückstellung: 9
Regierung München (MfV): 9
Doppelmedung: 9
Bayerisches Verfolgtenarchiv: 9
KSHA Gelle/Land: 9
Sachkartei für Bez. Reg.: 9
Bayerisches Kartei: 9
Heimat: 9
KSHA Nürnberg: 9
KSHA Wittlage: 9
KSHB: 9
Ankunftskartei: 9
61n: 9
Bezirksamt: 9
Regierung Münster: 9
K: 9
Bayerisches Zentralarchiv: 8
Schwabach: 8
Leipzig: 8
Landesamt für die Regelung von Vermögensangelegenheiten: 8
LG Frankfurt: 8
K815: 8
61: 8
K81nt: 8
Aurich /Ostfriesland: 8
Kreisonderhilfsausschub: 8
K811: 8
A.D.I.V.A. Bureau de Restitution: 8
BVA: 8
Bundesarchiv Berlin-Lichterfelde: 8
Landesheiratstelle: 8
Völker: 8
Kreisaußerhelfsausschub: 8
Königlich-Preußische: 8
KBlm: 8
Haftbeschädigte: 8
Noin: 8
United Restitution Office, Frankfurt/Main, Grünburgweg 119: 8
Landesbeirksstelle: 8
Doppelmeldung Kiel: 8
KBl: 8
Bayerisches Landeszentrale für die Opfer des Nationalsozialismus: 8
KSHA Köln/Land: 8
KSHA Norden: 8
Regional Office for Compensation and Administration of Assets, Koblenz: 8
Doppelmeilung: 8
K31n: 8
Aurich I.Ostfriesl.: 8
KSHA Linggen: 8
Köln, Riehler Pl. 2, 5000 Köln: 8
Bauverwaltung: 8
Hauptescheide: 8
Öl: 8
KSHA Einbeck: 8
Kreisondeserhifsausschuss: 8
Ministerium des Innern: 8
Bay. Landesarchiv: 8
Bayerisches Verwaltungsgericht: 8
KSH Nord: 7
Regionalverwaltungsgericht München I: 7
Bayerisches Landesamt für Jugend und Verwahrlosungsschutz: 7
An Bundeeskartei: 7
Uel: 7
Staatsministerium für Innerdeutsche Beziehungen: 7
K61a: 7
Regierung Pommern: 7
Landesbeirat Stuttgart: 7
Bln: 7
Landesamt für die Verfolgten des Nationalsozialismus: 7
United Restitution Office, Frankfurt/M. Grünburgweg 119: 7
Ausgl.Amt Bremen: 7
Kreissozialhilfsschulung: 7
KOM: 7
Kreisondertshilfsausschuss: 7
Regionalverwaltungsgericht Trier: 7
Allianz: 7
Doppelvermögensbehörde: 7
St. H.: 7
Doppelmeldeamt: 7
Doppelvermögens-u. Bauverwaltung: 7
Bundeskartell: 7
Doppelmeldung Mainz: 7
Bundeskarte: 7
Köln, Riehlstr. Pl.2, 5000 Köln.1: 7
Bund: 7
Südliches Zentralstelle: 7
Landesarchiv Münster: 7
81n: 7
K31: 7
DOPPELMELDUNG Stuttgart: 7
Paris: 7
Landsgericht München I: 7
KSHA Zellerafeld: 7
Leer/Ostfriesl.: 7
Stadtverwaltung: 7
Kreisverwaltung - Amt f. Wiedergutmachung - Höxter/Weser: 7
BayHauptstelle: 7
KSHC Cuxhaven: 7
KSHA Fallingbostel: 7
An der Bundeskartei: 7
Bezirksamt Koblenz: 7
Landesamt für die Rückstellung von Opfern des Nationalsozialismus: 7
Bayerisches Archiv für Zeitgeschichte: 7
Wiener Landesgericht: 7
Kreis Linden: 7
Efurt: 6
Nazi Victims Compensation Office: 6
VORGANG an Köln: 6
Emden: 6
Sondervermögens- und Baufondsverwaltung: 6
HHG: 6
BAfT: 6
KSH Hamm: 6
EfrA: 6
Aurich/Ostfriesl.: 6
Hauptbesoldung: 6
Bundes'kartei: 6
Haftbescheinigung: 6
KAI: 6
K819: 6
Landesamt für Verbraucherschutz und Lebensmittelsicherheit: 6
Landsgericht München II: 6
Karlsruhe Aussenstelle Freiburg i.Br.: 6
KSHC Celle/Land: 6
Rheinland: 6
OLDB: 6
Bayerisches Archiv: 6
KSHA Hammeln-Pyrmont: 6
Tr. 11: 6
Landesjustizverwaltung, Stuttgart: 6
Kreisonderrhilfsausschub: 6
Kreissonderhilfsschuss: 6
Tr. Bayerisches Landesarchiv: 6
Landkreis Oschersleben: 6
Landau, Pf.: 6
Sen. f. Fin.: 6
Kreisverwaltung Paderborn: 6
Staatsanwalt Hamburg: 6
KSHa Celle/Land: 6
K&In: 6
BHF - VB 4: 6
Bureau de Restitution: 6
Ravensburger Kartei: 6
Landesjustizverwaltung München: 6
Sachverständigenstelle für BZK: 6
Ausland: 6
Schreiber: 6
HJ: 6
Doppelmeidung München: 6
Staatsanwalt Köln: 6
Bundesarchiv Koblenz: 6
Regierung: 6
Birkenfeld: 6
Norden: 6
BayHaupt: 6
Hauptzuständige Behörde: 6
Niedersächsische Ersatzbehörde: 6
Höherer Kommissar der Vereinigten Nationen für Flüchlinge: 6
Bundesstelle Köln: 6
KSHA Meppe: 6
Hamburg 36, Drehbahn 37IV: 6
Kreissozialhilfesausschuss: 6
Bayer. Landesamt: 6
A.f.W. Rhein. Pfalz: 6
Landesrentenbehörde: 6
Hauptbeschwerde: 6
BMF- VB4: 6
Anstalt des Bundes Oldenburg: 6
Kreissonderhilfsschüfe: 6
Hund. Verw. Amt: 6
Regionalverwaltungsbehörde für Wien und Niederösterreich: 6
Landeszentrale: 6
Vergütungsausschuss: 6
KSHA Darmenber/Elbe: 6
A: 6
H81m: 5
Kreissozialhilfsschule Braunschweig-Stadt: 5
Süddeutsche: 5
Wolm: 5
Landesentschädigungsstelle für die Bundesrepublik Deutschland: 5
KSHA Rottenburg/H.: 5
An Bundeskartellamt: 5
Doppel Meldung Köln: 5
Landkreis Isarloh: 5
K610: 5
In: 5
Landgericht München: 5
Rinteln: 5
London: 5
H8m: 5
Faulenstraße 69, 28195 Bremen: 5
Aussenstelle Freiburg: 5
Regionalverwaltungsgericht München: 5
Stadtverwaltung Stadthaus: 5
Bundesverwaltungsamt - Abteilung II: 5
R8In: 5
H8In: 5
Ni/La: 5
Bayer. Landesjustizverwaltung: 5
K510: 5
Landesamt für Vertriebenenwesen Köln: 5
X8In: 5
Kreisaußerhelfsausschuß: 5
Landeszentrale für politische Opferfürsorge: 5
Doppelung: 5
Höherer Kommissar der Vereinigten Nationen für Deutschland: 5
Bayerisches Verfolgungsgesamt: 5
Reg.-Träger Münster: 5
Ausg. Amt Bremen: 5
Deutsches Versicherungsamt: 5
Königreich-Preuß Berlin: 5
Regionalverwaltungsbehörde: 5
Sondervermögens-u. Bautverwaltung: 5
Landkreis Osierholz: 5
KdF: 5
Härtefonds: 5
United Restitution Office, Frankfurt/M, Grünburgweg 119: 5
An Bundeskammer: 5
AfW Mettmann RP Düsseldorf: 5
K 8 In: 5
Landesbeamtenschaft: 5
BZA: 5
Bekanntmachung: 5
Bayerisches Verfolgungssamt: 5
Landeszentrale - Registrierung: 5
Landau Pf.: 5
Schreibtisch: 5
Köln, Riehler, Pl.2, 5000 Köln 1: 5
Köln, Riehl Pl.2, 5000 Köln 1: 5
Bay. Kartei: 5
Bayerische Landeszentrale: 5
Sozialgericht Berlin: 5
Higher Commissioner of the Allied Powers for Refugees: 5
Köln (Brüssel): 5
Tr. Landeszentrale für die Vergütung von Opfern des Nationalsozialismus: 5
Kreisonderhlfasschul: 5
Fu: 5
Doppelvermerkung Berlin: 5
United Restitution Office, Frankfurt/Main: 5
K5: 5
KSHA Winsen - Luhe: 5
Higher Commissioner for Refugees of the United Nations: 5
Karlsruhe, Außenstelle Freiburg i.Br.: 5
Magistrat der Stadt Braunschweig: 5
Zentralstelle für NS-Opfer: 5
Sondervermögens- und Bauerverwaltung: 5
Doppelmeldung Karlsruhe: 5
Regierung Posen: 5
BHF-VR4: 5
W81n: 5
Bayerisches L.E.A.: 5
BFA: 5
Dr. Müller: 5
United Restitution Office, Frankfurt am Main, Grünburgweg 119: 5
Bayerisches Landesamt für Akten und Archivwesen: 5
Komm: 5
Nazi Germany: 5
Ga: 5
Fu.: 5
Südliches Zentralbüro: 5
KSHA Vehta: 5
ö1: 5
Bayerisches Verfolgungsarchiv: 5
An Bundeseskartei Hannover: 5
ES/A: 5
Wiedergutmachung Mainz: 5
An Bundes'kartei: 5
Dannenberg/Elbe: 5
Kreissozialhilfsschule Peine: 5
Bay. Landesamt: 5
Hauptstaatsarchiv: 5
Doppelmeilung Berlin: 4
KSHA Nienburg/Weser: 4
Altenkirchen Westerwald: 4
Bayerische Landesstelle: 4
DOPPELUNG: 4
BMF-VT4: 4
Tr. Samt: 4
Israel: 4
BMT: 4
Sachbearbeitung BZK Reg.: 4
Einst. Behörde Köln: 4
Kreissozialamt Landkreis Grafschaft Goya: 4
Sondervermögens-u. Beauftragung: 4
Güteverfahren: 4
Bayerisches Staatsarchiv: 4
KSHA d. Reg. Bez. Hildesheim: 4
Karlruhe Aussenstelle Freiburg i.Br.: 4
Krois Linder: 4
Honer Kommissar der Vereinten Nationen für Flüchtlinge: 4
Anstalt des Bundes für die Verwaltung von Vermögensverzeichnissen: 4
Neuendettelsau: 4
H8ln: 4
Breslau, Gutenbergstr. 18: 4
Niedersachsen-Präsident / Reg.-Präsident: 4
An Bundesländer: 4
Claims Conference: 4
Südwest: 4
Rhd.-Pfalz: 4
K8 In: 4
Kreissozialamt des Landkreises Göttingen: 4
BMF/IVB4: 4
Bayerisches Verfolgtenmuseum: 4
Feststellungsbescheid in Stuttgart: 4
Kreisonderschutz: 4
H8lm: 4
Neuried: 4
Kreisonderholfasschuf: 4
K618: 4
Regional Office for Compensation and Administration of Assets: 4
BHT-VB3: 4
Landesentschädigungsbehörde für die Bundesrepublik Deutschland: 4
Niedersachsen-Präsident / Landesarchiv Hannover: 4
Kreisonderhlfasschuf: 4
LVA Dörf: 4
Nienburg/Weser: 4
Staatsanwaltschaft Hamm: 4
BVAmt: 4
An Bundeskärtei: 4
Kreissozialhilfsschulze: 4
Auschwitz: 4
Tr. Landesarchiv München: 4
Efrat: 4
unbekannt: 4
KSHA Solttau: 4
Deutscher: 4
Finanzamt: 4
Kreissozialamt Landkreis Grafschaft Hoya: 4
K6lm: 4
München 2, Arcistraße 11: 4
Hdn: 4
Der Niedersächsische Minister des Innern Hannover: 4
Aurich, Ostfriesland: 4
RA. United Restitution Office, Frankfurt/Main: 4
Köln, Riehler Pl. 2, 5000 Köln 41: 4
Kreissozialhilfsschule Osnabrück-Stadt: 4
Karlsruhe Außenstelle Freiburg i.Br.: 4
Landesbeauftragte für die Opfer des Nationalsozialismus: 4
Landesverwaltungsamt Bayern: 4
Deutsches Zentrum für die Opfer des Nationalsozialismus: 4
Altenkirchen, Westerw.: 4
Kreis Nordhorn: 4
An Bundesakartei: 4
Kann: 4
Reichsverwaltungsamt: 4
Bundeszentralstelle für Opfer des Nationalsozialismus: 4
Regierung Hamburg: 4
Ausgl.AmtBremen: 4
Kreis Linz: 4
Regierung Hessen (Wf.): 4
Kreissozialamt Landkreis Grafschaft Lippe: 4
DSHF: 4
K51a: 4
Schw. Landesamt: 4
Doppelmeierung: 4
Deutschland: 4
Bekirksamt: 4
Dudorf: 4
Wattenscheid-Salzgitter: 4
Doppelmaßung: 4
Kd: 4
Hohner Kommissar der Vereinten Nationen für Flüchtlinge: 4
Regional Office for Compensation and Administration of Seized Assets, Koblenz: 4
Miltam Israel Office: 4
Sudkartei für Bez. Reg.: 4
Bayerisches Landesamt für Vertriebene und Flüchtlinge: 4
Lindau: 4
Doppelmeldung nicht erforderlich, Akte wurde von Bayern überstellt.: 4
Senatsentscheid: 4
KO: 4
Tr. des Verfolgten: 4
United Restitution Office, Frankfurt am Main, Gruneburgweg 119: 4
Kurzstelle: 4
Hauptbeschädigte: 4
Bund. Verw. Amt: 4
BPA: 4
Wolffenbüttel: 4
Bayerisches Landesamt für staatsbürgerliche Angelegenheiten: 4
Landsmannschaft der Verfolgten des Nationalsozialismus: 4
Kreissozialhilfsschule Goslar-Stadt: 4
Baden-Württemberg: 4
Landeszentrale für die Vergütung nationalsozialistischer Opfer: 4
Bundeszentrale für die Opfer des Nationalsozialismus: 4
KSHA Rinteln: 4
Hauptverwaltungsamt: 4
KreisaußerordentlicherHilfsausschuss: 4
Haupt: 4
Vorgang an Koblenz: 4
Köln, Riehler Pl.2, 5000 Köln 4: 4
Bayerisches Versäumnisamt: 4
K 5 In: 3
Holzm: 3
Nic.: 3
Regional Office for Compensation and Restitution of Property: 3
Bundeskartellei: 3
Aurich /Ostfriesl.: 3
Hauptzuständigkeit: 3
Bundesverw.Amt: 3
Aussensestelle Freiburg: 3
BAH: 3
Los Angeles: 3
EK: 3
Hohes Kommisariat der Vereinigten Nationen für Flüchtlinge: 3
Kreisondeserhifsausschub: 3
Zentral-Registratur: 3
Xolm: 3
Düsseldorfer Landesjustiz: 3
Gütersloh: 3
Jörg: 3
K5In: 3
An Bundeskartotek: 3
KSHA Hild. Marienb.: 3
S. SCHREIBEN: 3
Regionalamt München: 3
Doppelmeldung Trier: 3
Vehta: 3
BayHJ: 3
KSHA Wolfsenbittel: 3
LG Bochum: 3
Altenkirchen/Westerw.: 3
BZA. Zeigledorf: 3
KSHA Landkreis Lüneburg: 3
VAG: 3
Nordrhein-Westfälische Bayerische Kartei: 3
Service-Center Koeln: 3
Kreisverwaltungsreferat des Landkreises Burgdorf/Hann.: 3
HNO: 3
KSB: 3
Heilbronn: 3
K&I: 3
K&L: 3
K61d: 3
Generalzollverwaltung; Service-Center Köln: 3
Fuß: 3
Doppel meldung: 3
Kreisonderhlfasschü: 3
KSHA Cologne: 3
DME: 3
Bezirksamt Mainz: 3
Bureau de Restitution, Paris: 3
KdM: 3
An Bundeckartei: 3
Wiedergutmachung Karlsruhe: 3
O. Staatsanw. Köln: 3
KSHA Colle/Lend: 3
Doppelmeldung Bremen: 3
Sachverständigenstelle: 3
Der Reichsverwaltungsamt: 3
Rundesammlung der Finanzan: 3
Hohen Kommissar der Vereinten Nationen für Flüchtlinge: 3
Doppelvermögens: 3

In [29]:
print(f"Max MatchDistance: {lev_matches['MatchDistance'].max()}")

Max MatchDistance: 58.0

In [30]:
total = len(lev_matches)-len(df_matches_impossible)
max_dist = int(lev_matches['MatchDistance'].max()) + 1
for i in range(1, max_dist):
    count = (lev_matches['MatchDistance'] == i).sum()
    pct = count / total * 100    
    print(f'MatchDistance = {i}: {count} ({pct:.2f}%)')

MatchDistance = 1: 17610 (12.09%)
MatchDistance = 2: 10216 (7.01%)
MatchDistance = 3: 9283 (6.37%)
MatchDistance = 4: 7249 (4.98%)
MatchDistance = 5: 25033 (17.18%)
MatchDistance = 6: 7157 (4.91%)
MatchDistance = 7: 5696 (3.91%)
MatchDistance = 8: 23344 (16.03%)
MatchDistance = 9: 5215 (3.58%)
MatchDistance = 10: 3719 (2.55%)
MatchDistance = 11: 5334 (3.66%)
MatchDistance = 12: 2539 (1.74%)
MatchDistance = 13: 3634 (2.49%)
MatchDistance = 14: 3022 (2.07%)
MatchDistance = 15: 2023 (1.39%)
MatchDistance = 16: 2193 (1.51%)
MatchDistance = 17: 2679 (1.84%)
MatchDistance = 18: 2706 (1.86%)
MatchDistance = 19: 1229 (0.84%)
MatchDistance = 20: 1014 (0.70%)
MatchDistance = 21: 1700 (1.17%)
MatchDistance = 22: 362 (0.25%)
MatchDistance = 23: 375 (0.26%)
MatchDistance = 24: 360 (0.25%)
MatchDistance = 25: 477 (0.33%)
MatchDistance = 26: 168 (0.12%)
MatchDistance = 27: 105 (0.07%)
MatchDistance = 28: 294 (0.20%)
MatchDistance = 29: 202 (0.14%)
MatchDistance = 30: 113 (0.08%)
MatchDistance = 31: 55 (0.04%)
MatchDistance = 32: 170 (0.12%)
MatchDistance = 33: 62 (0.04%)
MatchDistance = 34: 65 (0.04%)
MatchDistance = 35: 61 (0.04%)
MatchDistance = 36: 43 (0.03%)
MatchDistance = 37: 17 (0.01%)
MatchDistance = 38: 12 (0.01%)
MatchDistance = 39: 8 (0.01%)
MatchDistance = 40: 14 (0.01%)
MatchDistance = 41: 13 (0.01%)
MatchDistance = 42: 15 (0.01%)
MatchDistance = 43: 12 (0.01%)
MatchDistance = 44: 3 (0.00%)
MatchDistance = 45: 2 (0.00%)
MatchDistance = 46: 3 (0.00%)
MatchDistance = 47: 2 (0.00%)
MatchDistance = 48: 4 (0.00%)
MatchDistance = 49: 21 (0.01%)
MatchDistance = 50: 11 (0.01%)
MatchDistance = 51: 7 (0.00%)
MatchDistance = 52: 8 (0.01%)
MatchDistance = 53: 6 (0.00%)
MatchDistance = 54: 3 (0.00%)
MatchDistance = 55: 0 (0.00%)
MatchDistance = 56: 0 (0.00%)
MatchDistance = 57: 2 (0.00%)
MatchDistance = 58: 2 (0.00%)

In [31]:
df_nomatches = lev_matches[(lev_matches['MatchDistance'] > 0) | (lev_matches['MatchDistance'].isna())]

df_nomatches.sort_values('MatchDistance', ascending=True).to_excel('compensation_office_nomatches.xlsx', index=False)

# Replacing Single Tokens

In [32]:
# build sets of all unique tokens in the ground truth and the extracted office names

def normalize(s):
    if not isinstance(s, str):
        return ""
    s = s.lower()
    replacements = {
        "ä": "ae", "ö": "oe", "ü": "ue", "ß": "ss"
    }
    for k, v in replacements.items():
        s = s.replace(k, v)
    s = unicodedata.normalize("NFKD", s)
    s = re.sub(r'[^a-zA-Z\s]', '', s)
    s = re.sub(r'\s+', ' ', s).strip()
    return s

normalized_csv_token_gt = [normalize(office) for office in gt]
normalized_csv_token_corrections = [normalize(office) for office in list_corrections]
normalized_csv_token_further_corrections = [normalize(office) for office in list_further_corrections]
normalized_json_token_list = [normalize(office) for office in df_unmatched_filtered['CompensationOffice1'].tolist()]
normalized_csv_token_list = normalized_csv_token_gt + normalized_csv_token_corrections + normalized_csv_token_further_corrections

def office_token_set(series):
    tokens = set()
    for name in series:
        tokens.update(token for token in re.findall(r"\b\w+\b", name, flags=re.UNICODE)
            if not token.isdigit())
    return tokens

csv_tokens = office_token_set(normalized_csv_token_list)
json_tokens = office_token_set(normalized_json_token_list)

print(f"csv_tokens: {len(csv_tokens)}")
print(f"json_tokens: {len(json_tokens)}")

csv_tokens: 382
json_tokens: 10502

In [33]:
# map the tokens of the extracted office names to the closest equivalent in the ground truth tokens up to a maximal 
# edit distance of half of each token's length
json_to_csv_closest_map = {}
for json_token in json_tokens:
    if json_token in csv_tokens:
        continue
    
    max_distance = len(json_token) // 2
    best_match = None
    best_dist = float('inf')
    
    for csv_token in csv_tokens:
        if len(csv_token) >= 3:
            if abs(len(csv_token) - len(json_token)) > max_distance:
                continue
            dist = distance(json_token, csv_token)
            if dist <= max_distance and dist < best_dist:
                best_dist = dist
                best_match = csv_token
    
    if best_match is not None:
        json_to_csv_closest_map.setdefault(best_dist, []).append((json_token, best_match))

json_to_csv_closest_map = {
    k: sorted(v, key=lambda x: len(x[0]))
    for k, v in sorted(json_to_csv_closest_map.items())
}

print({k: len(v) for k, v in json_to_csv_closest_map.items()})
json_to_csv_closest_map

{1: 761, 2: 1133, 3: 1259, 4: 1047, 5: 821, 6: 634, 7: 386, 8: 310, 9: 222, 10: 139, 11: 76, 12: 38, 13: 23, 14: 12, 15: 11, 16: 5, 17: 3, 18: 1, 20: 3, 21: 1, 22: 1, 23: 1}

{1: [('mn', 'min'),
  ('ib', 'ibr'),
  ('dr', 'der'),
  ('tr', 'str'),
  ('sr', 'str'),
  ('st', 'str'),
  ('mi', 'min'),
  ('bd', 'bad'),
  ('es', 'des'),
  ('ud', 'und'),
  ('de', 'der'),
  ('as', 'das'),
  ('ir', 'ibr'),
  ('ne', 'neu'),
  ('br', 'ibr'),
  ('ba', 'bad'),
  ('da', 'das'),
  ('of', 'ofd'),
  ('od', 'ofd'),
  ('di', 'die'),
  ('lr', 'lrb'),
  ('rb', 'lrb'),
  ('rg', 'reg'),
  ('fd', 'ofd'),
  ('re', 'reg'),
  ('et', 'etc'),
  ('mt', 'amt'),
  ('eg', 'reg'),
  ('fur', 'fuer'),
  ('dos', 'das'),
  ('dei', 'der'),
  ('det', 'der'),
  ('isr', 'ist'),
  ('mad', 'bad'),
  ('cas', 'das'),
  ('sta', 'str'),
  ('bam', 'bad'),
  ('ofs', 'ofd'),
  ('art', 'abt'),
  ('nec', 'neu'),
  ('bfd', 'bad'),
  ('mst', 'ist'),
  ('rea', 'reg'),
  ('dad', 'bad'),
  ('wie', 'die'),
  ('weg', 'reg'),
  ('ver', 'der'),
  ('dat', 'das'),
  ('lra', 'lrb'),
  ('dor', 'der'),
  ('mit', 'min'),
  ('brd', 'bad'),
  ('new', 'neu'),
  ('baw', 'bad'),
  ('ofr', 'ofd'),
  ('sha', 'ksha'),
  ('opd', 'ofd'),
  ('ras', 'das'),
  ('dfd', 'ofd'),
  ('kin', 'min'),
  ('sth', 'str'),
  ('hin', 'min'),
  ('ofg', 'ofd'),
  ('stf', 'str'),
  ('win', 'min'),
  ('rad', 'bad'),
  ('stv', 'str'),
  ('ger', 'der'),
  ('hes', 'hess'),
  ('din', 'min'),
  ('alt', 'abt'),
  ('kst', 'ist'),
  ('wst', 'ist'),
  ('vin', 'min'),
  ('dep', 'der'),
  ('her', 'herr'),
  ('ubt', 'abt'),
  ('ung', 'und'),
  ('wtr', 'str'),
  ('rig', 'reg'),
  ('ovd', 'ofd'),
  ('rin', 'min'),
  ('oed', 'ofd'),
  ('ant', 'abt'),
  ('bie', 'die'),
  ('pas', 'das'),
  ('oft', 'ofd'),
  ('ksh', 'ksha'),
  ('ami', 'amt'),
  ('xes', 'des'),
  ('bay', 'bad'),
  ('drs', 'das'),
  ('ddr', 'der'),
  ('dem', 'der'),
  ('ges', 'des'),
  ('ord', 'ofd'),
  ('lro', 'lrb'),
  ('ast', 'ist'),
  ('stg', 'str'),
  ('bmt', 'amt'),
  ('res', 'reg'),
  ('bav', 'bad'),
  ('sin', 'min'),
  ('stm', 'str'),
  ('bes', 'des'),
  ('neg', 'neu'),
  ('hmt', 'amt'),
  ('lbb', 'lrb'),
  ('baf', 'bad'),
  ('lre', 'lrb'),
  ('beg', 'reg'),
  ('ofb', 'ofd'),
  ('ksa', 'ksha'),
  ('rbg', 'reg'),
  ('end', 'und'),
  ('dhe', 'die'),
  ('wes', 'des'),
  ('ojd', 'ofd'),
  ('kad', 'bad'),
  ('and', 'und'),
  ('mid', 'min'),
  ('ber', 'der'),
  ('doz', 'dez'),
  ('ost', 'ist'),
  ('dar', 'der'),
  ('dfr', 'der'),
  ('ofj', 'ofd'),
  ('qfd', 'ofd'),
  ('den', 'der'),
  ('bau', 'bad'),
  ('rog', 'reg'),
  ('abh', 'abt'),
  ('hst', 'ist'),
  ('uni', 'und'),
  ('dme', 'die'),
  ('rep', 'reg'),
  ('deg', 'der'),
  ('bah', 'bad'),
  ('okd', 'ofd'),
  ('mii', 'min'),
  ('bez', 'dez'),
  ('def', 'der'),
  ('keg', 'reg'),
  ('lad', 'bad'),
  ('abg', 'abt'),
  ('efd', 'ofd'),
  ('lab', 'lrb'),
  ('ofo', 'ofd'),
  ('pin', 'min'),
  ('lfd', 'ofd'),
  ('rey', 'reg'),
  ('xin', 'min'),
  ('deu', 'neu'),
  ('off', 'ofd'),
  ('oder', 'der'),
  ('seer', 'leer'),
  ('breg', 'reg'),
  ('kshs', 'ksha'),
  ('herz', 'herr'),
  ('bona', 'bonn'),
  ('stdt', 'stadt'),
  ('neve', 'neue'),
  ('maiz', 'mainz'),
  ('palz', 'pfalz'),
  ('bsha', 'ksha'),
  ('hund', 'und'),
  ('bohn', 'bonn'),
  ('tier', 'trier'),
  ('wist', 'ist'),
  ('ostr', 'str'),
  ('pres', 'praes'),
  ('kshm', 'ksha'),
  ('bamt', 'amt'),
  ('regv', 'reg'),
  ('fund', 'und'),
  ('ksho', 'ksha'),
  ('huss', 'hess'),
  ('inst', 'ist'),
  ('wuer', 'fuer'),
  ('kshb', 'ksha'),
  ('baud', 'bad'),
  ('amth', 'amt'),
  ('aemt', 'amt'),
  ('samt', 'amt'),
  ('dezf', 'dez'),
  ('mark', 'markt'),
  ('amnt', 'amt'),
  ('pflz', 'pfalz'),
  ('lecr', 'leer'),
  ('koel', 'koeln'),
  ('bund', 'und'),
  ('kshc', 'ksha'),
  ('dhdt', 'adhdt'),
  ('buer', 'fuer'),
  ('tuer', 'fuer'),
  ('mink', 'min'),
  ('west', 'westf'),
  ('mess', 'hess'),
  ('bist', 'ist'),
  ('stad', 'stadt'),
  ('kshv', 'ksha'),
  ('kshd', 'ksha'),
  ('trer', 'trier'),
  ('eamt', 'amt'),
  ('manz', 'mainz'),
  ('dess', 'hess'),
  ('neua', 'neu'),
  ('kein', 'keine'),
  ('ampt', 'amt'),
  ('trie', 'trier'),
  ('pltz', 'platz'),
  ('brak', 'brake'),
  ('oftd', 'ofd'),
  ('wesf', 'westf'),
  ('fink', 'fin'),
  ('amts', 'amt'),
  ('main', 'min'),
  ('plaz', 'platz'),
  ('neus', 'neu'),
  ('koln', 'koeln'),
  ('amft', 'amt'),
  ('vamt', 'amt'),
  ('ksia', 'ksha'),
  ('kaha', 'ksha'),
  ('maink', 'mainz'),
  ('efurt', 'erfurt'),
  ('westu', 'westf'),
  ('buyer', 'bayer'),
  ('mayer', 'bayer'),
  ('pratz', 'platz'),
  ('koelz', 'koeln'),
  ('wesff', 'westf'),
  ('plitz', 'platz'),
  ('westp', 'westf'),
  ('mains', 'mainz'),
  ('wuerm', 'wuert'),
  ('kshan', 'ksha'),
  ('weste', 'westf'),
  ('blatz', 'platz'),
  ('mahnz', 'mainz'),
  ('kshax', 'ksha'),
  ('state', 'stade'),
  ('kshaw', 'ksha'),
  ('westw', 'westf'),
  ('boyer', 'bayer'),
  ('essen', 'hessen'),
  ('neuer', 'neue'),
  ('ksaha', 'ksha'),
  ('kshah', 'ksha'),
  ('triel', 'trier'),
  ('kshaf', 'ksha'),
  ('bunde', 'bundes'),
  ('herrn', 'herr'),
  ('weltf', 'westf'),
  ('trher', 'trier'),
  ('bayes', 'bayer'),
  ('ksham', 'ksha'),
  ('maine', 'mainz'),
  ('piatz', 'platz'),
  ('staat', 'stadt'),
  ('colle', 'celle'),
  ('lands', 'landes'),
  ('tries', 'trier'),
  ('platt', 'platz'),
  ('hoess', 'hess'),
  ('boenn', 'bonn'),
  ('kshao', 'ksha'),
  ('melle', 'celle'),
  ('kshae', 'ksha'),
  ('fayer', 'bayer'),
  ('ptalz', 'pfalz'),
  ('wcstf', 'westf'),
  ('plaiz', 'platz'),
  ('triar', 'trier'),
  ('wuerf', 'wuert'),
  ('neues', 'neue'),
  ('glatz', 'platz'),
  ('kshag', 'ksha'),
  ('neuen', 'neue'),
  ('freib', 'freie'),
  ('meinz', 'mainz'),
  ('praef', 'praes'),
  ('yelle', 'celle'),
  ('trien', 'trier'),
  ('trler', 'trier'),
  ('triern', 'trier'),
  ('weinst', 'weinstr'),
  ('gerlin', 'berlin'),
  ('oblenz', 'koblenz'),
  ('iwestf', 'westf'),
  ('einstr', 'weinstr'),
  ('maintz', 'mainz'),
  ('tremen', 'bremen'),
  ('iplatz', 'platz'),
  ('koelnn', 'koeln'),
  ('rpfalz', 'pfalz'),
  ('wuertt', 'wuert'),
  ('hremen', 'bremen'),
  ('berger', 'buerger'),
  ('bayers', 'bayern'),
  ('grafsh', 'grafsch'),
  ('bracke', 'brake'),
  ('munden', 'minden'),
  ('strass', 'strasse'),
  ('jenner', 'jenaer'),
  ('arburg', 'warburg'),
  ('lindau', 'landau'),
  ('landos', 'landes'),
  ('amburg', 'hamburg'),
  ('aremen', 'bremen'),
  ('brakel', 'brake'),
  ('bumdes', 'bundes'),
  ('fragen', 'frauen'),
  ('weinsr', 'weinstr'),
  ('staedt', 'stadt'),
  ('astadt', 'stadt'),
  ('menden', 'minden'),
  ('sozial', 'soziale'),
  ('plaetz', 'platz'),
  ('linden', 'minden'),
  ('beglin', 'berlin'),
  ('koelny', 'koeln'),
  ('minder', 'minden'),
  ('bremer', 'bremen'),
  ('innere', 'innern'),
  ('rheinl', 'rhein'),
  ('plaatz', 'platz'),
  ('auvich', 'aurich'),
  ('neuied', 'neuwied'),
  ('landesk', 'landes'),
  ('kobleuz', 'koblenz'),
  ('weisstr', 'weinstr'),
  ('marburg', 'warburg'),
  ('richler', 'riehler'),
  ('goslari', 'goslar'),
  ('frauend', 'frauen'),
  ('koblens', 'koblenz'),
  ('koblanz', 'koblenz'),
  ('hanover', 'hannover'),
  ('kasselb', 'kassel'),
  ('reiburg', 'freiburg'),
  ('rnsberg', 'arnsberg'),
  ('graisch', 'grafsch'),
  ('munchen', 'muenchen'),
  ('auriach', 'aurich'),
  ('cattbus', 'cottbus'),
  ('berlins', 'berlin'),
  ('munster', 'muenster'),
  ('weinsfr', 'weinstr'),
  ('goeslar', 'goslar'),
  ('koblinz', 'koblenz'),
  ('rishler', 'riehler'),
  ('dinnern', 'innern'),
  ('bremens', 'bremen'),
  ('sarburg', 'saarburg'),
  ('bundesk', 'bundes'),
  ('noblenz', 'koblenz'),
  ('neumark', 'neumarkt'),
  ('weimstr', 'weinstr'),
  ('bremmen', 'bremen'),
  ('detmola', 'detmold'),
  ('harburg', 'hamburg'),
  ('sociale', 'soziale'),
  ('bayerns', 'bayern'),
  ('laendes', 'landes'),
  ('wernstr', 'weinstr'),
  ('beziege', 'bezuege'),
  ('neuried', 'neuwied'),
  ('kassell', 'kassel'),
  ('barburg', 'warburg'),
  ('arnberg', 'arnsberg'),
  ('homburg', 'hamburg'),
  ('kassels', 'kassel'),
  ('betmold', 'detmold'),
  ('neusadt', 'neustadt'),
  ('rastock', 'rostock'),
  ('gratsch', 'grafsch'),
  ('weinsstr', 'weinstr'),
  ('neuwiedt', 'neuwied'),
  ('grafisch', 'grafsch'),
  ('arosberg', 'arnsberg'),
  ('desernat', 'dezernat'),
  ('riehlker', 'riehler'),
  ('searburg', 'saarburg'),
  ('freiberg', 'freiburg'),
  ('graftsch', 'grafsch'),
  ('neuwiedw', 'neuwied'),
  ('riehlner', 'riehler'),
  ('arnswerg', 'arnsberg'),
  ('baarburg', 'saarburg'),
  ('armsberg', 'arnsberg'),
  ('darstadt', 'darmstadt'),
  ('finanzon', 'finanzen'),
  ('degernat', 'dezernat'),
  ('nenstadt', 'neustadt'),
  ('beustadt', 'neustadt'),
  ('neussadt', 'neustadt'),
  ('vkoblenz', 'koblenz'),
  ('meustadt', 'neustadt'),
  ('arnaberg', 'arnsberg'),
  ('arneberg', 'arnsberg'),
  ('prnsberg', 'arnsberg'),
  ('aensberg', 'arnsberg'),
  ('finanzan', 'finanzen'),
  ('oldeburg', 'oldenburg'),
  ('helstedt', 'helmstedt'),
  ('koblentz', 'koblenz'),
  ('bielfeld', 'bielefeld'),
  ('kalsruhe', 'karlsruhe'),
  ('osterode', 'osterodeh'),
  ('mannover', 'hannover'),
  ('finanzer', 'finanzen'),
  ('arnsoerg', 'arnsberg'),
  ('aunsberg', 'arnsberg'),
  ('frnsberg', 'arnsberg'),
  ('arnoberg', 'arnsberg'),
  ('karsruhe', 'karlsruhe'),
  ('karlruhe', 'karlsruhe'),
  ('wartburg', 'warburg'),
  ('koblensz', 'koblenz'),
  ('vermoege', 'vermoegen'),
  ('arnsherg', 'arnsberg'),
  ('chamnitz', 'chemnitz'),
  ('andesamt', 'landesamt'),
  ('lezernat', 'dezernat'),
  ('farnsberg', 'arnsberg'),
  ('harnsberg', 'arnsberg'),
  ('muenchens', 'muenchen'),
  ('ahrnsberg', 'arnsberg'),
  ('aegierung', 'regierung'),
  ('ebehoerde', 'behoerde'),
  ('behoerden', 'behoerde'),
  ('detzernat', 'dezernat'),
  ('president', 'praesident'),
  ('finanzzen', 'finanzen'),
  ('neustadtv', 'neustadtw'),
  ('weinsteig', 'weinsteige'),
  ('aernsberg', 'arnsberg'),
  ('ibreisgau', 'breisgau'),
  ('manistrat', 'magistrat'),
  ('finanzsen', 'finanzen'),
  ('toebingen', 'tuebingen'),
  ('vbehoerde', 'behoerde'),
  ('rogierung', 'regierung'),
  ('karlshuhe', 'karlsruhe'),
  ('tdezernat', 'dezernat'),
  ('schauburg', 'schaumburg'),
  ('neustadtb', 'neustadtw'),
  ('bezirksam', 'bezirksamt'),
  ('vormoegen', 'vermoegen'),
  ('arnswberg', 'arnsberg'),
  ('cldenburg', 'oldenburg'),
  ('regierang', 'regierung'),
  ('veraltete', 'verwaltete'),
  ('meustadtw', 'neustadtw'),
  ('wienbaden', 'wiesbaden'),
  ('mdweinstr', 'adweinstr'),
  ('hannovera', 'hannover'),
  ('arnssberg', 'arnsberg'),
  ('verwaltet', 'verwaltete'),
  ('nordbuden', 'nordbaden'),
  ('stuttgard', 'stuttgart'),
  ('hannoverl', 'hannover'),
  ('arnstberg', 'arnsberg'),
  ('franzfurt', 'frankfurt'),
  ('maristrat', 'magistrat'),
  ('nordboden', 'nordbaden'),
  ('hessische', 'hessisches'),
  ('hiesbaden', 'wiesbaden'),
  ('bayersche', 'bayerische'),
  ('niesbaden', 'wiesbaden'),
  ('arnnsberg', 'arnsberg'),
  ('behoerdet', 'behoerde'),
  ('oltenburg', 'oldenburg'),
  ('vermoeger', 'vermoegen'),
  ('derzernat', 'dezernat'),
  ('ministers', 'minister'),
  ('bezirkamt', 'bezirksamt'),
  ('gildesheim', 'hildesheim'),
  ('kaerlsruhe', 'karlsruhe'),
  ('bayesische', 'bayerische'),
  ('regierungs', 'regierung'),
  ('vewbezirks', 'verwbezirks'),
  ('bekirksamt', 'bezirksamt'),
  ('bundesamts', 'bundesamt'),
  ('landeesamt', 'landesamt'),
  ('bayrisches', 'bayerisches'),
  ('neustadtew', 'neustadtw'),
  ('verwalteto', 'verwaltete'),
  ('rabteilung', 'abteilung'),
  ('braesident', 'praesident'),
  ('verwalteta', 'verwaltete'),
  ('neustadtwv', 'neustadtw'),
  ('landsesamt', 'landesamt'),
  ('hussisches', 'hessisches'),
  ('bayetische', 'bayerische'),
  ('bildesheim', 'hildesheim'),
  ('palzberlin', 'pfalzberlin'),
  ('laendesamt', 'landesamt'),
  ('bazirksamt', 'bezirksamt'),
  ('bexirksamt', 'bezirksamt'),
  ('vorwaltete', 'verwaltete'),
  ('spinkenhof', 'sprinkenhof'),
  ('sayerische', 'bayerische'),
  ('dusseldorf', 'duesseldorf'),
  ('mayerische', 'bayerische'),
  ('sildesheim', 'hildesheim'),
  ('verwbeirks', 'verwbezirks'),
  ('karlsruher', 'karlsruhe'),
  ('verfolgter', 'verfolgte'),
  ('bayedische', 'bayerische'),
  ('payerische', 'bayerische'),
  ('frankfurtn', 'frankfurtm'),
  ('osterodehz', 'osterodeh'),
  ('vermoegens', 'vermoegen'),
  ('vrwbezirks', 'verwbezirks'),
  ('landesamts', 'landesamt'),
  ('desseldorf', 'duesseldorf'),
  ('praesidenc', 'praesident'),
  ('verwaltets', 'verwaltete'),
  ('pflzberlin', 'pfalzberlin'),
  ('verfolgtes', 'verfolgte'),
  ('dezirksamt', 'bezirksamt'),
  ('karlsruhes', 'karlsruhe'),
  ('bayersches', 'bayerisches'),
  ('verfolgten', 'verfolgte'),
  ('hikdesheim', 'hildesheim'),
  ('ministerie', 'ministerin'),
  ('freiburgdr', 'freiburgbr'),
  ('helmsstedt', 'helmstedt'),
  ('alstaedter', 'altstaedter'),
  ('praesidenz', 'praesident'),
  ('lezirksamt', 'bezirksamt'),
  ('karlshruhe', 'karlsruhe'),
  ('xpraesident', 'praesident'),
  ('nayerisches', 'bayerisches'),
  ('verwalteter', 'verwaltete'),
  ('rayerisches', 'bayerisches'),
  ('muesseldorf', 'duesseldorf'),
  ('verwbezirke', 'verwbezirks'),
  ('gpraesident', 'praesident'),
  ('bayerischen', 'bayerisches'),
  ('verwaltgete', 'verwaltete'),
  ('schauemburg', 'schaumburg'),
  ('sprenkenhof', 'sprinkenhof'),
  ('versbezirks', 'verwbezirks'),
  ('schlaumburg', 'schaumburg'),
  ('verwbekirks', 'verwbezirks'),
  ('noerdlicher', 'noerdliche'),
  ('hildesheimm', 'hildesheim'),
  ('auerstrasse', 'auestrasse'),
  ('varwbezirks', 'verwbezirks'),
  ('osanabrueck', 'osnabrueck'),
  ('benzirksamt', 'bezirksamt'),
  ('bezirkssamt', 'bezirksamt'),
  ('frankfurtmp', 'frankfurtm'),
  ('merwbezirks', 'verwbezirks'),
  ('schnaumburg', 'schaumburg'),
  ('arcistrasse', 'arcisstrasse'),
  ('vorwbezirks', 'verwbezirks'),
  ('weilstrasse', 'weinstrasse'),
  ('frankfurtma', 'frankfurtm'),
  ('werwbezirks', 'verwbezirks'),
  ('sarbruecken', 'saarbruecken'),
  ('verwalteten', 'verwaltete'),
  ('springenhof', 'sprinkenhof'),
  ('schaeumburg', 'schaumburg'),
  ('yerwbezirks', 'verwbezirks'),
  ('spraesident', 'praesident'),
  ('ministerien', 'ministerin'),
  ('obezirksamt', 'bezirksamt'),
  ('bayernische', 'bayerische'),
  ('bayernsches', 'bayerisches'),
  ('beezirksamt', 'bezirksamt'),
  ('osnaubrueck', 'osnabrueck'),
  ('bezirksamts', 'bezirksamt'),
  ('bayerischer', 'bayerisches'),
  ('zustaendige', 'zustaendig'),
  ('vermbezirks', 'verwbezirks'),
  ('schauumburg', 'schaumburg'),
  ('frankfurtam', 'frankfurtm'),
  ('verwaltetes', 'verwaltete'),
  ('payerisches', 'bayerisches'),
  ('verwbezirksk', 'verwbezirks'),
  ('nshaertfonds', 'nshaertefonds'),
  ('bayernisches', 'bayerisches'),
  ('bremenohaven', 'bremenhaven'),
  ('verwbezirkes', 'verwbezirks'),
  ('ministeriums', 'ministerium'),
  ('regpresident', 'regpraesident'),
  ('weinsstrasse', 'weinstrasse'),
  ('verwxbezirks', 'verwbezirks'),
  ('kontrolliert', 'kontrollierte'),
  ('verswbezirks', 'verwbezirks'),
  ('meisestrasse', 'meiserstrasse'),
  ('hannoverlind', 'hannoverland'),
  ('verwbezirksm', 'verwbezirks'),
  ('regpraesidet', 'regpraesident'),
  ('verwbezirksx', 'verwbezirks'),
  ('regpraesidnt', 'regpraesident'),
  ('vertriebenen', 'vertriebene'),
  ('dlandkreises', 'landkreises'),
  ('nshaetefonds', 'nshaertefonds'),
  ('rpfalzberlin', 'pfalzberlin'),
  ('regprasident', 'regpraesident'),
  ('zentralkartei', 'centralkartei'),
  ('aussensstelle', 'aussenstelle'),
  ('regpraesidenz', 'regpraesident'),
  ('bundesarchive', 'bundesarchiv'),
  ('begpraesident', 'regpraesident'),
  ('bundesarchivs', 'bundesarchiv'),
  ('rugpraesident', 'regpraesident'),
  ('ausssenstelle', 'aussenstelle'),
  ('bahnhoofplatz', 'bahnhofplatz'),
  ('rheindorfersr', 'rheindorferstr'),
  ('landesarchive', 'landesarchiv'),
  ('refpraesidium', 'regpraesidium'),
  ('begierungsamt', 'regierungsamt'),
  ('baundesarchiv', 'bundesarchiv'),
  ('rogierungsamt', 'regierungsamt'),
  ('landesarchivs', 'landesarchiv'),
  ('verfolgtenamts', 'verfolgtenamt'),
  ('regierungsaemt', 'regierungsamt'),
  ('meisserstrasse', 'meiserstrasse'),
  ('kontrollierter', 'kontrollierte'),
  ('kheinlandpfalz', 'rheinlandpfalz'),
  ('staufenbergstr', 'stauffenbergstr'),
  ('regpraesidenta', 'regpraesident'),
  ('innernminister', 'innenminister'),
  ('kontrolliertes', 'kontrollierte'),
  ('regpraesidient', 'regpraesident'),
  ('iedergutmachung', 'wiedergutmachung'),
  ('pelfkantkreises', 'selfkantkreises'),
  ('wedergutmachung', 'wiedergutmachung'),
  ('rheindorfersstr', 'rheindorferstr'),
  ('ragierungsbezirk', 'regierungsbezirk'),
  ('regierungsbesirk', 'regierungsbezirk'),
  ('wiadergutmachung', 'wiedergutmachung'),
  ('kegierungsbezirk', 'regierungsbezirk'),
  ('goettlingenstadt', 'goettingenstadt'),
  ('hegierungsbezirk', 'regierungsbezirk'),
  ('staatministerium', 'staatsministerium'),
  ('wienergutmachung', 'wiedergutmachung'),
  ('versorgungstelle', 'versorgungsstelle'),
  ('rogierungsbezirk', 'regierungsbezirk'),
  ('regierungsdezirk', 'regierungsbezirk'),
  ('goetttingenstadt', 'goettingenstadt'),
  ('regierungsbezirks', 'regierungsbezirk'),
  ('hundesministerium', 'bundesministerium'),
  ('zentralregistatur', 'zentralregistratur'),
  ('wiedergutmachtung', 'wiedergutmachung'),
  ('mundesministerium', 'bundesministerium'),
  ('aurichstfriesland', 'aurichostfriesland'),
  ('niedersaechsische', 'niedersaechsisches'),
  ('rundesministerium', 'bundesministerium'),
  ('fwiedergutmachung', 'wiedergutmachung'),
  ('pundesministerium', 'bundesministerium'),
  ('verwaltungsbezirk', 'verwaltungsbezirks'),
  ('nundesministerium', 'bundesministerium'),
  ('wiedergutmachungs', 'wiedergutmachung'),
  ('bundesministeriums', 'bundesministerium'),
  ('nordrheinwestfales', 'nordrheinwestfalen'),
  ('niedersaechsischen', 'niedersaechsisches'),
  ('landesbeirksstelle', 'landesbezirksstelle'),
  ('niedersaechsischer', 'niedersaechsisches'),
  ('oberstaedtdirektor', 'oberstadtdirektor'),
  ('aurichoatfriesland', 'aurichostfriesland'),
  ('verwaltungsbezirke', 'verwaltungsbezirks'),
  ('staatsministeriums', 'staatsministerium'),
  ('justizministeriums', 'justizministerium'),
  ('landsverwaltungsamt', 'landesverwaltungsamt'),
  ('regierungsbezirksam', 'regierungsbezirksamt'),
  ('regerungspraesident', 'regierungspraesident'),
  ('regierungbezirksamt', 'regierungsbezirksamt'),
  ('regierungsprasidium', 'regierungspraesidium'),
  ('entschaedigungssamt', 'entschaedigungsamt'),
  ('regierungspraesidet', 'regierungspraesident'),
  ('verwaltungsbezirksx', 'verwaltungsbezirks'),
  ('verwaltungsbezirksm', 'verwaltungsbezirks'),
  ('vermogensverwaltung', 'vermoegensverwaltung'),
  ('verwaltungsbezirkes', 'verwaltungsbezirks'),
  ('regierungsbezirkamt', 'regierungsbezirksamt'),
  ('egierungspraesident', 'regierungspraesident'),
  ('wiedergutmachungamt', 'wiedergutmachungsamt'),
  ('landeshezirksstelle', 'landesbezirksstelle'),
  ('landesbozirksstelle', 'landesbezirksstelle'),
  ('regierungsbezirksnmt', 'regierungsbezirksamt'),
  ('regierungspraefident', 'regierungspraesident'),
  ('regierungsbesirksamt', 'regierungsbezirksamt'),
  ('landesentschaedigung', 'landesentschaedigungs'),
  ('ragierungsbezirksamt', 'regierungsbezirksamt'),
  ('regierungsbezirkspmt', 'regierungsbezirksamt'),
  ('rogierungspraesidium', 'regierungspraesidium'),
  ('begierungspraesident', 'regierungspraesident'),
  ('kegierungsbezirksamt', 'regierungsbezirksamt'),
  ('negierungspraesident', 'regierungspraesident'),
  ('rogierungsbezirksamt', 'regierungsbezirksamt'),
  ('negierungsbezirksamt', 'regierungsbezirksamt'),
  ('regierungsdezirksamt', 'regierungsbezirksamt'),
  ('hegierungsbezirksamt', 'regierungsbezirksamt'),
  ('regierungsbezirkssamt', 'regierungsbezirksamt'),
  ('landesverwaltungsamts', 'landesverwaltungsamt'),
  ('regierungspraesidient', 'regierungspraesident'),
  ('regierungspraesidente', 'regierungspraesident'),
  ('wiedergutmachungsaamt', 'wiedergutmachungsamt'),
  ('raegierungsbezirksamt', 'regierungsbezirksamt'),
  ('regierungsbezirksgamt', 'regierungsbezirksamt'),
  ('regierungsbezirksoamt', 'regierungsbezirksamt'),
  ('regierungsbezirkscamt', 'regierungsbezirksamt'),
  ('regierungsbezirksamti', 'regierungsbezirksamt'),
  ('regierungsbezirksammt', 'regierungsbezirksamt'),
  ('regierungsbezirksamts', 'regierungsbezirksamt'),
  ('wiedergutmachungssamt', 'wiedergutmachungsamt'),
  ('laendesverwaltungsamt', 'landesverwaltungsamt'),
  ('entscheidungsbekoerde', 'entscheidungsbehoerde'),

In [34]:
tokens_to_replace = []
tokens_to_replace.extend(json_to_csv_closest_map[1])
tokens_to_replace.extend(json_to_csv_closest_map[2])
tokens_to_replace.extend(json_to_csv_closest_map[3])
tokens_to_replace.remove(('main', 'mainz'))
tokens_to_replace.remove(('essen', 'hessen'))

ValueError: list.remove(x): x not in list

In [ ]:
unique_distance1_token_map = {
    json_token: csv_candidates
    for json_token, csv_candidates in tokens_to_replace
}

def replace_unique_distance1_tokens(text):
    text = "" if pd.isna(text) else str(text)
    return re.sub(
        r"\b\w+\b",
        lambda match: unique_distance1_token_map.get(match.group(0).lower(), match.group(0)),
        text,
        flags=re.UNICODE
    )

df_unmatched_filtered['CompensationOffice_token_swap'] = df_unmatched_filtered['CompensationOffice1'].apply(normalize).apply(replace_unique_distance1_tokens)

print(f"Unique token replacements available: {len(unique_distance1_token_map)}")

results = df_unmatched_filtered['CompensationOffice_token_swap'].apply(get_min_distance_dynamic_normalized)
df_matches_token_swap = pd.DataFrame({
    'CompensationOffice1': df_unmatched_filtered['CompensationOffice1'],
    'MatchedOffice': results.apply(lambda x: x[1]),
    'MatchDistance': results.apply(lambda x: x[0])
})

df_matches_token_swap.head(20)

Unique token replacements available: 3151

,CompensationOffice1,MatchedOffice,MatchDistance
7,Amt für Wiedergutmachung des Selbstkantkreises...,amtfuerwiedergutmachungdesselfkantkreisesgeile...,9.0
51,Kreisaußerhelfsausschübe,NaN,NaN
55,Der Innernister des Landes Nordrhein-Westfalen...,derinnenministerdeslandesnordrheinwestfalenabt...,6.0
72,Kreissonderhilfsschübe Peine,kreissonderhilfsausschussdelmenhorst,14.0
84,Regierungsbezirksamt für Wiedergutmachung und ...,regierungsbezirksamtfuerwiedergutmachungundver...,13.0
108,Bayerische Kartei,NaN,NaN
111,Entschädigungsamt,entschaedigungsamtberlin,6.0
113,Kreissonderhilfsausschuss Springe,kreissonderhilfsausschussdelmenhorst,10.0
115,Der Regierungspräsident - Dez. 14 - in Detmold,derregierungspraesidentindetmold,7.0
122,Bayerische Kartei,NaN,NaN
145,Landesentschädigungsausschuss,blandesentschaedigungsamt,9.0
190,Bayerisches Landesamt für digungssam,bayerischeslandesentschaedigungsamt,11.0
192,Regierungsbezirkamt für Wiedergutmachung,saarburgbezirksamtfuerwiedergutmachung,10.0
222,Regierungsbezirksamt für Wiedergutmachung und ...,regierungsbezirksamtfuerwiedergutmachungundver...,16.0
255,Bayerische Kartei,NaN,NaN
279,Kreissozialhilfsausschuss des Landkreises Gött...,kreissonderhilfsausschussdeslandkreisesgrafsch...,16.0
302,Regierungsbezirkstelle für Wiedergutmachung un...,regierungsbezirksamtfuerwiedergutmachungundver...,13.0
312,"United Restitution Office, Frankfurt/Main, Grü...",NaN,NaN
332,Kreissozialhilfsausschuss Land Hadeln,kreissonderhilfsausschussdelmenhorst,14.0
343,Entscheidungsbehörde,entschaedigungsbehoerdekoeln,8.0

In [ ]:
df_matches_token_swap[df_matches_token_swap['MatchDistance'] == 0]

        CompensationOffice1     MatchedOffice  MatchDistance
3519         Oldenburg/Old.         oldenburg            0.0
15458              Augsburg          arnsberg            0.0
20453     Begirussregierung  bezirksregierung            0.0
20946      Bekirskregierung  bezirksregierung            0.0
23574              Würzburg         lueneburg            0.0
...                     ...               ...            ...
1886447            Brauburg          saarburg            0.0
1886767             Sarbrüg          saarburg            0.0
1893810             Sarbrüg          saarburg            0.0
1894003           Secerburg          saarburg            0.0
1900241              Dachau            aachen            0.0

[573 rows x 3 columns]

In [ ]:
df_matches_token_swap[df_matches_token_swap['MatchDistance'].isin([1, 2])]

,CompensationOffice1,MatchedOffice,MatchDistance
1680,BayHues,bayern,1.0
3753,Regierung Arnswerg (Welf.),regierungarnsbergwestf,2.0
3920,Regierung Arnberg (Welf.),regierungarnsbergwestf,2.0
4507,Bayerisches Landesentschädigungsgesamt,bayerischeslandesentschaedigungsamt,1.0
7022,Regierungsamt Arnsherg (Welf.),regierungsamtarnsbergwestf,2.0
...,...,...,...
1895020,R.Pfz.-Berlin,rhpfalzberlin,2.0
1896680,Regierung Prensborg (Westf.),regierungarnsbergwestf,2.0
1896688,Bundesentschädigungssamt,blandesentschaedigungsamt,1.0
1897298,Regierung Finnsberg (Welf.),regierungarnsbergwestf,2.0
1898588,Regierung Arnswerg (Welf.),regierungarnsbergwestf,2.0

In [ ]:
df_matches_token_swap[df_matches_token_swap['MatchDistance'].isin([1, 2])]

,CompensationOffice1,MatchedOffice,MatchDistance
1680,BayHues,bayern,1.0
3753,Regierung Arnswerg (Welf.),regierungarnsbergwestf,2.0
3920,Regierung Arnberg (Welf.),regierungarnsbergwestf,2.0
4507,Bayerisches Landesentschädigungsgesamt,bayerischeslandesentschaedigungsamt,1.0
7022,Regierungsamt Arnsherg (Welf.),regierungsamtarnsbergwestf,2.0
...,...,...,...
1895020,R.Pfz.-Berlin,rhpfalzberlin,2.0
1896680,Regierung Prensborg (Westf.),regierungarnsbergwestf,2.0
1896688,Bundesentschädigungssamt,blandesentschaedigungsamt,1.0
1897298,Regierung Finnsberg (Welf.),regierungarnsbergwestf,2.0
1898588,Regierung Arnswerg (Welf.),regierungarnsbergwestf,2.0