In [102]:
import pandas as pd
from Levenshtein import distance
import numpy as np
import re
import unicodedata

In [103]:
#read the Compensation Office csv file into a dataframe
df_csv = pd.read_excel('/Users/mva/Desktop/Post-processing/2025_06_03_Liste der Entschädigungsämter mit Adressen, Varianten, Normalisierungen und Archiven.xlsx')
df_csv.sample(20)

,Layout class,Filename,Bundesland,Transkription Compensation Office,Normalisierung Compensation Office1,Normalisierung Compensation Office2,Zuständiges Archiv,Zuständiges Archiv - GND-Nummer,Unnamed: 8
28,BW-Hauptphase,1880_00_00_243_0,Baden-Württemberg,Landesamt für die Wiedergutmachung \nStuttgart...,Landesamt für die Wiedergutmachung Stuttgart,NaN,Landesarchiv Baden-Württemberg,10107080-9,NaN
230,offizielle Bezeichnungen und Adressen,NaN,Rheinland-Pfalz,Neustadt a.d. Weinstraße,NaN,NaN,Amt für Wiedergutmachung Saarburg,1354917804,NaN
54,BY-Spätphase,1924_01_12_84_0,Bayern,"Landesentschädigungsamt\nPrinz-Ludwig-Str. 5, ...",Landesentschädigungsamt München,NaN,Bayerisches Hauptstaatsarchiv,2005486-5,NaN
271,offizielle Bezeichnungen und Adressen,NaN,Niedersachsen,Der Präsident des Verwaltungsbezirks in Oldenb...,NaN,NaN,Niedersächsisches Landesarchiv,6510041-4,NaN
120,HH-NI-NRW-SH-Hauptphase (abweichend 2),1927_05_06_17_0,Niedersachsen,Reg.-Präsident Hildesheim,Regierungspräsident Hildesheim,NaN,Niedersächsisches Landesarchiv,6510041-4,NaN
52,BY-Spätphase,1908_01_15_69_0,Bayern,Bayerisches\nLandesentschädigungsamt\nPrinz-Lu...,Bayerisches Landesentschädigungsamt München,NaN,Bayerisches Hauptstaatsarchiv,2005486-5,NaN
378,RLP-Frühe-Phase,1903_02_04_83_0,Rheinland-Pfalz,Regierungsbezirksamt\nfür Wiedergutmachung\nun...,Regierungsbezirksamt für Wiedergutmachung und ...,NaN,Landesarchivverwaltung Rheinland-Pfalz,2029741-5,NaN
216,offizielle Bezeichnungen und Adressen,NaN,Rheinland-Pfalz,Bezirksamt für Wiedergutmachung Trier,NaN,NaN,Amt für Wiedergutmachung Saarburg,1354917804,NaN
422,Tabellen-Typ (abweichend),1909_01_22_88_0,Bund,Oberfinanzdirektion: Freiburg,Oberfinanzdirektion Freiburg,NaN,Bundesarchiv (Koblenz),39454-3,Landesarchivverwaltung Rheinland-Pfalz
35,BW-Hauptphase,1876_01_04_2_0,Baden-Württemberg,Landesamt für die Wiedergutmachung\nStuttgart ...,Landesamt für die Wiedergutmachung Stuttgart,NaN,Landesarchiv Baden-Württemberg,10107080-9,NaN
331,offizielle Bezeichnungen und Adressen,NaN,Bremen,Bremerhaven,NaN,NaN,Staatsarchiv Bremen,2022524-6,NaN
69,HE-Hauptphase,1904_01_08_38_0,Hessen,Darmstadt,Darmstadt,NaN,Hessisches Landesarchiv,1051993385,NaN
304,offizielle Bezeichnungen und Adressen,NaN,Hessen,Der Regierungspräsident - Wiesbaden,NaN,NaN,Hessisches Landesarchiv,1051993385,NaN
323,offizielle Bezeichnungen und Adressen,NaN,Hamburg,Behörde für Soziales und Familie - Versorgung...,NaN,NaN,Staatsarchiv (Hamburg),2022556-8,NaN
346,offizielle Bezeichnungen und Adressen,NaN,Berlin,Landesverwaltungsamt Berlin - Entschädigungsbe...,NaN,NaN,Berlin. Landesamt für Bürger- und Ordnungsange...,10116661-8,NaN
401,RLP-Hauptphase,1917_03_30_57_0,Rheinland-Pfalz,Rheinland-Pfalz \nBerlin,Rheinland-Pfalz Berlin,NaN,Amt für Wiedergutmachung Saarburg,1354917804,NaN
233,offizielle Bezeichnungen und Adressen,NaN,Rheinland-Pfalz,Regierungsbezirksamt für Wiedergutmachung und ...,NaN,NaN,Amt für Wiedergutmachung Saarburg,1354917804,NaN
188,offizielle Bezeichnungen und Adressen,NaN,Saarland,"Landesamt für Soziales, Gesundheit und Verbrau...",NaN,NaN,Landesarchiv (Saarbrücken),1035413-X,NaN
61,HB-Spätphase,1924_03_15_233_0,Bremen,FREIE HANSESTADT BREMEN\nDer Senator für Arbei...,"Der Senator für Arbeit und Frauen, Landesamt f...",NaN,Staatsarchiv Bremen,2022524-6,NaN
375,RLP-Frühe-Phase,1876_01_31_11_0,Rheinland-Pfalz,Regierungsbezirksamt \nfür Wiedergutmachung\nu...,Regierungsbezirksamt für Wiedergutmachung und ...,NaN,Landesarchivverwaltung Rheinland-Pfalz,2029741-5,NaN

In [104]:
#creaae a list of unique compensation offices from the csv file
gt = df_csv['Transkription Compensation Office '].unique().tolist()
print("Number of unique compensation offices: ", len(gt))

Number of unique compensation offices:  428

In [ ]:
#read the sliced extracted data jsonl file into a dataframe
df_json = pd.read_json('compoff_extracted.jsonl', lines=True)
df_json.sample(20)

,CompensationOffice1,BZKNr,filename
412139,Entschädigungsamt Berlin,374 179,1912_02_25_62_0.jpg
1458848,Bezirksamt für Wiedergutmachung KOBLENZ,448425,1907_08_27_99_0.jpg
339879,Stuttgart,122946/VII/37913,1934_07_19_13_0.jpg
1233523,Hess. Staatsministerium,16713,1892_05_11_38_0.jpg
1299202,Köln,19079a,1896_10_28_84_0.jpg
73446,Entschädigungsbehörde Köln,Art. V-56-II-Nr.: 66 508,1916_07_14_18_0.jpg
171729,Bezirksamt für Wiedergutmachung Koblenz,156968,1922_02_12_7_0.jpg
554391,Bezirksamt für Wiedergutmachung Koblenz,319125,1928_02_22_79_0.jpg
1698451,Köln,609 429,1919_12_08_17_0.jpg
1779047,NaN,BEG 38652,1902_04_15_63_0.jpg
256627,Freie und Hansestadt Hamburg Sozialbehörde Amt...,170321,1921_03_17_55_0.jpg
981278,Entschädigungsbehörde Köln,Art. V-56-II-Nr.: 47 589,1890_07_00_4_0.jpg
722812,NaN,62802 / VI / 7844,1932_07_08_16_0.jpg
1055501,Regierungsbezirksamt für Wiedergutmachung und ...,101723,1940_02_13_20_0.jpg
622832,Köln,627 443,1893_01_04_48_0.jpg
108176,NaN,22 224/V/1643,1903_06_22_95_0.jpg
255510,Freiburg/Br.,12368,1921_09_24_58_0.jpg
524733,Amt für Wiedergutmachung des Landes Rheinland-...,516 888,1915_03_03_66_0.jpg
735969,Köln,425444,1932_08_01_27_0.jpg
746754,Der Regierungspräsident Düsseldorf,235 002a/448,1881_08_13_24_0.jpg

In [105]:
#create a dataframe with the entries that have a non-null value in the CompensationOffice1 column
print("Number of cards: ",len(df_json))
mask_not_null = df_json['CompensationOffice1'].notna()
print(f'Number of non-null entries: {mask_not_null.sum()}')

Number of cards:  1901284
Number of non-null entries: 1825946

In [106]:
#create a function to normalise the compensation office names by removing punctuation and whitespace, converting to lowercase and replacing umlauts with their equivalent

#def normalise(word):
#    return re.sub(r'\s+', ' ', str(word)).strip().lower()
def normalize(s):
    if not isinstance(s, str):
        return ""
    
    s = s.lower()

    # Normalize umlauts and ß
    replacements = {
        "ä": "ae", "ö": "oe", "ü": "ue", "ß": "ss"
    }
    for k, v in replacements.items():
        s = s.replace(k, v)
    
    # Normalize unicode (just in case)
    s = unicodedata.normalize("NFKD", s)
    
    # Remove punctuation and whitespace
    s = re.sub(r'[\W_]+', '', s)
        
    return s

gt_normalized = [normalize(office) for office in gt]

In [107]:
#create a mask for the entries in the json dataframe that match any of the normalized compensation office names in the gt list
mask_matched_0 = df_json['CompensationOffice1'].apply(normalize).isin(gt_normalized)
print(f'Number of matches: {mask_matched_0.sum()}')

df_unmatched = df_json[mask_not_null & ~mask_matched_0]
print(f'Number of unmatched entries: {len(df_unmatched)}')

Number of matches: 1494694
Number of unmatched entries: 331252

In [ ]:
#print the unique values in the CompensationOffice1 column of the unmatched dataframe and their counts
print(len(df_unmatched['CompensationOffice1'].unique().tolist()))
df_unmatched['CompensationOffice1'].value_counts()

27629

CompensationOffice1
Bezirksamt für Wiedergutmachung Köln                                   32785
Hess. Staatsministerium                                                29978
Freie und Hansestadt Hamburg Sozialbehörde Amt für Wiedergutmachung    16429
Landesamt für die Wiedergutmachung                                     14641
Hansestadt Hamburg, Sozialbehörde, Amt für Wiedergutmachung            11836
                                                                       ...
Regierung Aachen (Welt.)                                                   1
Regierungspräsident Arasberg                                               1
Kreisssonderhilfsausschuss des Landkreises Garsch. Schlaumburg             1
Bayerisches Landesamt für den Regierungsbezirk München                     1
Reg.-Präsident /Präsident des Vereinsbezirks Hannover                      1
Name: count, Length: 27629, dtype: int64

In [191]:
#create a list of manually corrected compensation office names that are not in the gt list but are in the json dataframe and normalise them
list_corrections = ["Bezirksamt für Wiedergutmachung Köln", "Hess. Staatsministerium", "Freie und Hansestadt Hamburg Sozialbehörde Amt für Wiedergutmachung", "Hansestadt Hamburg, Sozialbehörde, Amt für Wiedergutmachung", 
                    "Der Innenminister des Landes Nordrhein-Westfalen", "Landesamt für die Wiedergutmachung Baden-Württemberg", "Oberfinanzdirektion Niedersachsen", "Statistisches Landesamt Nordrhein-Westfalen" , "Oberfinanzdirektion Niedersachsen"
                    , "Rhein. Pfalz - Berlin", "Regierungsbezirksamt für Wiedergutmachung und verwaltete Vermögen Köln", "Aachen", "Landesbeirat für die Wiedergutmachung, Stuttgart", "Freiburg i.Br.", "Hamburg, Sozialbehörde, Amt für Wiedergutmachung",
                    "Freie und Hansestadt Hamburg", "Regierungsbezirk Mainz", "Hessisches Ministerium für Jugend, Familie und Gesundheit" , "Reg.-Präsident / Präsident des Verw.-Bezirks Hannover", "Amt für Wiedergutmachung des Landes Rheinland/Pfalz in Berlin Hauptabteilung II",
                    "Schleswig-Holstein in Kiel", "Kreissozialamt Hannover", "Reg.-Präsident Hannover", "Amt für Wiedergutmachung Rheinland-Pfalz" , "Saarburg Bezirksamt für Wiedergutmachung", "Freie und Hansestadt Hamburg, Arbeits- und Sozialbehörde, Amt für Wiedergutmachung",
                    "Niedersachsen-Präsident / Präsident des Verwaltungsbezirks Hannover", "Regierungsbezirksamt für Wiedergutmachung und verwaltete Vermögen Neustadt a. d. Weinstraße", "KSHA Hannover", "Regierungsbezirk für Wiedergutmachung und verwaltete Vermögen Trier",
                    "Oberfinanzdirektion Magdeburg", "Regierungsbezirkskammer für Wiedergutmachung und verwaltete Vermögen Mainz","Regierungsamt Arnsberg (Westf.)", "Regierungsbezirkskammer für Wiedergutmachung und verwaltete Vermögen Mainz",
                    "Regierungsbezirksamt für Wiedergutmachung und verwaltete Vermögen München", "Landesamt für die Wiedergutmachung Baden-Württemberg Stuttgart"]

list_corrections_normalized = [normalize(office) for office in list_corrections]
gt_completed = gt_normalized + list_corrections_normalized
df_json['CompensationOffice1'] = df_json['CompensationOffice1'].str.replace("Bayrische", "Bayerische")
mask_matched_1 = df_json['CompensationOffice1'].apply(normalize).isin(gt_completed)
print(f'Number of matches: {mask_matched_1.sum()}')
df_unmatched = df_json[mask_not_null & ~mask_matched_1]
print(f'Number of unmatched entries: {len(df_unmatched)}')
print(f"Unique unmatched entries: {len(df_unmatched['CompensationOffice1'].unique().tolist())}")
percentage = len(df_unmatched) / len(mask_not_null) * 100
print(f"Percentage of unmatched entries: {percentage:.2f}%")

Number of matches: 1628175
Number of unmatched entries: 197771
Unique unmatched entries: 27325
Percentage of unmatched entries: 10.40%

In [192]:
df_unmatched['CompensationOffice1'].value_counts().head(30)

CompensationOffice1
Landesamt für die Wiedergutmachung                                       14641
Bayerische Kartei                                                         9925
Regierungsbezirksamt für Wiedergutmachung und verwaltete Vermögen         7261
Bundeskartei                                                              4884
Bezirksamt für Wiedergutmachung                                           4130
HNG                                                                       3402
Regierungsbezirksamt für Wiedergutmachung und kontrollierte Vermögen      3354
Bayerisches Landesarchiv                                                  2585
Regierungsbezirks-Amt für Wiedergutmachung und kontrollierte Vermögen     2557
Bezirksamt für Wiedergutmachung 65 Mainz                                  1304
Bayerisches Landesamt für Verfolgtenfragen                                1291
Kreissonderhilfsausschuss                                                 1101
Barburg                                                                    987
Kreissozialamt                                                             958
Baarburg                                                                   950
Bundesminister der Finanzen                                                904
Entschädigungsbehörde                                                      863
Hamburg 1                                                                  840
Bundesamt                                                                  834
König                                                                      825
Bayerisches Landesamt für Vertriebene                                      815
Reg.-Präsident / Präsident des Verw.-Bezirks                               752
KSHA                                                                       750
Der Herr Regierungspräsident in Detmold                                    745
Kreissozialhilfsausschuss                                                  712
Landesentschädigungsamt                                                    602
Landesamt für Wiedergutmachung                                             586
Bundesamt für Vertriebene                                                  560
Landesamt für Vertriebene                                                  541
Kön                                                                        526
Name: count, dtype: int64

# Matching based on Levenshtein Distance

In [193]:
#  return the minimum distance and the best match up to a threshold of half the length of the cleaned name
def get_min_distance_dynamic_normalized(name):
    name_clean = normalize(name)
    threshold = len(name_clean) // 2
    
    min_dist = float('inf')
    best_match = None
    for office in gt_completed:
        office_clean = normalize(office)
        d = distance(name_clean, office_clean)
        if d == 0:
            return 0, office
        if d < min_dist:
            min_dist = d
            best_match = office
    if min_dist <= threshold:
        return min_dist, best_match
    return np.nan, None

results = df_unmatched['CompensationOffice1'].apply(get_min_distance_dynamic_normalized)

lev_matches = pd.DataFrame({
    'CompensationOffice1': df_unmatched['CompensationOffice1'],
    'MatchedOffice': results.apply(lambda x: x[1]),
    'MatchDistance': results.apply(lambda x: x[0])
})

In [194]:
#print the matches with a distance of 1 and 2
df_matches_2 = lev_matches[lev_matches['MatchDistance'].isin([1, 2])]
df_matches_2.sample(25)

,CompensationOffice1,MatchedOffice,MatchDistance
1005098,Am. für Wiedergutmachung und kontrollierte Ver...,amtfuerwiedergutmachungundkontrolliertevermoeg...,1.0
551242,LR8 NW,lrbnw,1.0
750459,Thür,trier,2.0
1150474,R.A. Pfalz-Berlin,rhpfalzberlin,1.0
569787,Sassburg,saarburg,2.0
800643,Regierungspräsident Arnberg,regierungspraesidentarnsberg,1.0
1620622,Landesamt für die Wiedergutmachung Stuttgart N...,landesamtfuerdiewiedergutmachungstuttgartneuew...,1.0
1616184,HöIn,koeln,2.0
314510,Hamburg I,hamburg,1.0
552476,Holn,koeln,2.0
1560357,Der Inneminsister des Landes Nordrhein-Westfalen,derinnenministerdeslandesnordrheinwestfalen,2.0
1243701,Regierungsbezirksamt für Wiedergutmachung und ...,regierungsbezirksamtfuerwiedergutmachungundver...,1.0
737884,KSH Hannover,kshahannover,1.0
410993,"Oberfinanzdirektion Köln, Riehler Pl.2, 5000 Köln",oberfinanzdirektionkoelnriehlerpl25000koeln1,1.0
1390299,Regierungsbezirksamt für Wiedergutmachung und ...,regierungsbezirksamtfuerwiedergutmachungundver...,1.0
203370,R. Pialz - Berlin,rhpfalzberlin,2.0
1454446,Amt für Wiedergutmachung des Landes Rheinland/...,amtfuerwiedergutmachungdeslandesrheinlandpfalz...,2.0
903898,Landesamt für die Wiedergutmachung Stuttgart T...,landesamtfuerdiewiedergutmachungstuttgarttheod...,2.0
361518,"Bayerisches Landesentschädigungsamt München 2,...",bayerischeslandesentschaedigungsamtmuenchen2me...,1.0
146852,Baarburg,saarburg,1.0
1128510,Buyer. Landesentschädigungsamt,bayerlandesentschaedigungsamt,1.0
259179,Bezirksamt für Wiedergutmachung NEUSTADT q. d....,bezirksamtfuerwiedergutmachungneustadtadweinstr,1.0
786255,Regierungsbezirksamt für Wiedergutmachung und ...,regierungsbezirksamtfuerwiedergutmachungundver...,1.0
1203751,Begirdsregierung,bezirksregierung,2.0
1462959,Der Regierungspräsident - Dezernat 14 - in Det...,aderregierungspraesidentdezernat14indetmold,1.0

In [195]:
#print the counts of the match distances of 1 and 2
df_matches_2['MatchDistance'].value_counts()
print(f"Number of matches with distance 1 or 2: {len(df_matches_2)}")
print(f"Number of unmatched entries after adding the close matches: {len(df_unmatched) - len(df_matches_2)}")

Number of matches with distance 1 or 2: 27826
Number of unmatched entries after adding the close matches: 169945

In [201]:
#remove the matches with distance 1 and 2 from the unmatched dataframe
df_unmatched_filtered = df_unmatched[~df_unmatched['CompensationOffice1'].isin(lev_matches[lev_matches['MatchDistance'].isin([1, 2])]['CompensationOffice1'])]
df_unmatched_filtered['CompensationOffice1'].value_counts().iloc[30:40]

CompensationOffice1
Amt für Wiedergutmachung des Landes Rheinland-Pfalz                470
Regierung Arnsberg (Wf.)                                           459
Doppelmeldung                                                      449
Amt für Wiedergutmachung Stadt Bonn                                447
Bundesamt für Wiedergutmachung                                     439
Niedersachsen-Präsident / Präsident des Verwaltungsgerichtshofs    437
Regierung Köln                                                     421
Bundesarchiv                                                       408
Reg.-Präsidium Hildesheim                                          396
Entscheidungsbehörde Köln                                          396
Name: count, dtype: int64

In [202]:
df_matches_correctable = lev_matches.dropna()
print(len(df_matches_correctable))
df_matches_impossible = lev_matches[lev_matches['MatchedOffice'].isna()]
impossible_list = df_matches_impossible['CompensationOffice1'].tolist()
print(len(impossible_list), len(set(impossible_list)))
# print the unique values in the impossible list and their counts in descending order
for office in sorted(set(impossible_list), key=impossible_list.count, reverse=True):
    count = impossible_list.count(office)
    print(f"{office}: {count}")

145672
52099 7005
Bayerische Kartei: 9925
Bundeskartei: 4884
HNG: 3402
Bayerisches Landesarchiv: 2585
Kreissozialamt: 958
Bundesamt: 834
KSHA: 750
Kreissozialhilfsausschuss: 712
Köln, Riehler Pl.2, 5000 Köln 1: 477
Doppelmeldung: 449
Bundesarchiv: 408
Erfurt: 386
An Bundeskartei: 371
BHF: 346
BEG: 340
Bayerisches Hauptstaatsarchiv: 321
Magistrat der Stadt Bremen: 306
Montabaur: 291
BMF: 269
K81: 268
K81n: 267
Frankfurt/M.: 267
Ansbach: 257
Sondervermögens-u. Bauverwaltung: 242
Bayerisches Landesamt: 241
Aurich/Ostfriesland: 235
Magistrat der Stadt Bremenhaven: 224
VB3: 218
Bayerisches Verfolgtenamt: 209
Landeszentrale für die Vergütung von Opfern des Nationalsozialismus: 206
KSH: 205
Köln, Riehler Pl. 2, 5000 Köln 1: 204
Watenstedt-Salzgitter: 185
Bayerisches Landeszentrum für die Opfer des Nationalsozialismus: 181
Pirmasens: 181
Kaiserslautern: 178
Bayerisches Landesamt für die Opfer des Nationalsozialismus: 173
Höherer Kommissar der Vereinten Nationen für Flüchtlinge: 166
Kreissonderhilfsschübe: 163
EG: 160
Der Niedersächsische Minister des Innern: 159
Burgdorf: 152
Tr.: 137
Bayerisches Verwaltungsamt: 137
Bekannt: 123
Köln, Riehlstr. Pl.2, 5000 Köln 1: 122
Bundesverwaltungsamt: 117
Aurich i.Ostfriesl.: 114
BMF - VB4: 109
K61n: 108
Bebra: 104
K81m: 101
Bayerisches Landesamt für Verfolgte des Nationalsozialismus: 100
Nienburg-Weser: 94
Bay: 94
KSHA Göttingen: 93
Suchkartei für Bez. Reg.: 93
K8In: 85
Stadt Bonn: 84
Bad Kreuznach: 80
KSHA Wilhelmshaven: 79
Neuwied: 78
Kreisaußerhelfsausschuss: 76
Kreis Lindau: 73
Doppelmeldung München: 73
He: 72
K61: 71
Sondervermögens- u. Bauverwaltung: 71
ERFURT: 71
Bayerisches Verfolgtenzentrum: 70
Regierung Ansbach: 70
Bundesstelle: 69
Landkreis Osterholz: 69
Kreissonderhilfsschul: 66
Aurich / Ostfriesland: 66
Höherer Kommissar der Vereinigten Nationen für Flüchtlinge: 65
Bayerisches: 63
DOPPELMELDUNG: 62
Frankfurt a.M.: 61
KSHA Gifhorn: 60
KSHA Goslar-Land: 60
KSHA Emden: 58
Doppel Meldung: 58
Doppelvermerk: 58
Ludwigshafen am Rhein: 57
BHT: 56
Kreisaußerhilfsausschuss: 56
KSHA Celle/Land: 54
KSHA Winsen/Luhe: 52
Regierung Aachen (Wf.): 52
Aussensenstelle Freiburg i.Br.: 51
United Restitution Office, Frankfurt/Main, Grüneburgweg 119: 51
Bayerisches Verfolgungsausschuss: 50
Hauptbescheid: 48
Bundeskartothek: 48
KSHA Soltau: 48
Sondervermögens- und Bauverwaltung: 46
Frankfurt: 45
Doppelmeldung Berlin: 45
Doppelmeldung Köln: 45
Baastrup: 44
KSHA Springe: 44
Rostock: 43
KSHA Wittmund: 41
Kreisonderrhilfsausschuss: 41
Sondervermögens-u. Bauerverwaltung: 41
Nordhorn: 41
KSHA Watenstedt-Salzgitter: 40
Anstalt des Bundes: 39
Braunau: 39
Bayerisches Verfolgungsamt: 39
KSHa: 39
LG: 38
Doppelmeldung Stuttgart: 38
K817: 38
KSHA Holzminden: 38
Wolfenbüttel: 38
K51n: 37
Hamburg 36, Drehbahn 36IV: 37
Anspruchsberechtigter: 36
Stadthaus: 36
KSHA Zellerfeld: 36
An Bundesamt: 36
Frankfurt a. M.: 36
KSHA Hild. Marb.: 35
KSHA Neustadt a.Rbge.: 35
BHF - VB4: 34
KSHA Cloppenburg: 34
Landkreis Göttingen: 34
Nordden: 34
KSHA Northheim: 34
BHF-VB3: 33
Landesstelle für die Regelung von Schadensersatzansprüchen: 33
Hamburger Stiftung Hilfe für NS-Verfolgte: 32
Hauptstelle: 32
Landeszentrale für die Vergütung: 32
München 2, Arcisstraße 11: 32
BMF-VB4: 31
Bonn: 31
KSHA Ammerland: 31
K51: 31
KSHA Burgdorf: 30
Stuttgart-S, Neue Weinsteige 21: 30
HNC: 30
Frankfurt-Main: 29
Köln, Riehlstr. Pl. 2, 5000 Köln 1: 29
Nazi Germany Compensation Office: 29
KSHA Mepen: 29
BFD West: 28
Bundessstelle: 28
Bezirksamt von Koblenz: 28
Doppelmeldung Koblenz: 28
KSHA Winsen-Luhe: 28
Königreich-Preußen Berlin: 28
Kreissonderhilfsschüle: 28
Ludwigshafen a. Rh.: 27
Minister des Innern: 27
Hu: 27
BMF-UB4: 27
Service-Center Köln: 27
Frankfurt am Main: 27
Kreissozialhilfsschul: 26
KSHA Wesermünde: 26
Kreissozialhilfeausschuss: 26
KSHA Nörtheim: 26
Kreissonderhilfsausschub: 26
United Restitution Office, Frankfurt/Main, Gruneburgweg 119: 26
KSHA Uelzen: 25
Bundeszentralstelle für Verfolgte: 25
Doppelmeier: 25
Sondervermögens-U. Bauverwaltung: 25
Hamburger Stiftung: 25
KSHA Wolffenbüttel: 25
Landau/Pfalz: 25
Regierung München (Wf.): 25
Landeszentrale für die Vergütung der Opfer des Nationalsozialismus: 24
Hauptstaatsarchiv München: 24
Syke: 24
Landesbeiratstelle: 24
KSHA Delmenhorst: 23
Einbeck: 23
Landesbezirksstelle: 23
Sachverständigenstelle für Bez. Reg.: 23
51: 23
Schw.: 23
Soest: 23
United Restitution Office: 22
Landesverwaltungsamt München: 22
BHF-VB4: 22
K8lm: 22
Stiftung: 22
Landesbeirat: 22
: 21
Doppelmelung: 21
Holm: 21
Höherer Kommissar der Vereinten Nationen für Flüchlinge: 21
KSHC: 21
United Restitution Office, Frankfurt/M., Grünburgweg 119: 21
Aurich I. Ostfriesland: 21
Doppelmayr: 21
KSHA Colle/Land: 21
KSHA Northeim: 21
BHF-UB4: 21
Landesamt für: 21
Kn: 20
KSHA Veckta: 20
Altenkirchen Westerw.: 20
BRD: 20
A.Z.: 20
Landesarchiv München: 20
KSHA Friesland: 20
Regierung München: 20
Alfeld/Leine: 20
Köln, Riehler Pl.2, 5000 Köln: 19
K8: 19
K810: 19
United Restitution Office, Frankfurt: 19
K81a: 19
BayHStA: 19
Dudersfeld: 19
Ausgl. Amt Bremen: 19
Si.: 19
K814: 19
DHF: 19
An Bundesarchiv: 19
Bayerische Landeszentrale für die Opfer des Nationalsozialismus: 18
United Restitution Office, Frankfurt/M., Gruneburgweg 119: 18
H81n: 18
Bundesverwaltungsamt Köln: 18
Landeszentrale für die Opfer des Nationalsozialismus: 18
KSHA Nordhorn: 18
Landesamt für Kultur und Wissenschaft: 18
Bayerisches Verfolgungsausschussamt: 18
BEG-Kartei: 18
KSHA Münden: 18
K61m: 18
Bielefeld: 18
Kreis Lindenau: 18
Doppelmeldung Hamburg: 18
KSHA Neustadt a. Rbge.: 17
Aurich I.Ostfriesland: 17
81: 17
Kln: 17
Friesland: 17
Doppelvermerk München: 17
BMF - VBH: 17
B.V.: 16
K 51: 16
Bayerisches Landeszentrum für Opferberatung und Opferhilfe: 16
Alfeld: 16
Bundeskärtei: 16
KSHA Ganderkesheim: 16
Holz: 16
Frankfurt/Main: 16
Landeszentrale für politische Opferhilfe: 16
Kreissonderhilfsschule: 16
Doppelvermerkung: 16
Kreissonderhilfsschüf: 15
KSHA Winsen/L.: 15
United Restitution Office, Frankfurt/M.: 15
Doppelvermögen: 15
An Bundesekartei: 15
Ländeszentrale für die Opfer des Nationalsozialismus: 15
Gifhorn: 15
Landau/Pf.: 15
Delmenhorst: 15
K8m: 15
United Restitution Office, Frankfurt/M., Grüneburgweg 119: 15
Stadtverwaltung Stadthagen: 15
KSHA Melle: 15
Kreisonderhelfsausschuss: 15
Niedersachsen-Präsident / Präsident des Landes: 15
Landesamt: 15
51n: 15
K812: 15
KSHA Mappen: 15
BMF - VB 4: 15
KSHA Diepholz: 14
Regierung Bamberg: 14
Bundeskammer: 14
Aurich i.Ostfriesland: 14
BHF- VB4: 14
Köln, Riehler Pl.2: 14
Higher Commissioner of the United Nations for Refugees: 14
Ve: 14
Bayer. Landeszentrale: 14
Kreissonderbehelfsausschuss: 14
Bundesländer: 14
Fallingbostel: 13
KSHA Alfeld: 13
Doppel Meldung München: 13
Wehrmacht: 13
Landesarchiv Muenchen: 13
Gerichtsurteil: 13
Landesbeiratssstelle: 13
AfW Aachen-Stadt: 13
K 81: 13
Wiedergutmachung und verwaltete Vermögen: 13
Landesverwaltungsamt München II: 13
Hohes Kommissariat der Vereinten Nationen für Flüchtlinge: 13
Aurich i. Ostfriesl.: 13
KSHA Aschendorf/Ems: 13
KSHA Verden: 12
KSHA Wolfsenbüttel: 12
Bayisches Landesarchiv: 12
R81n: 12
Kreisonderschutzbehörde: 12
Landeszentrale für politische Opferentschädigung: 12
Köln, Reichler Pl.2, 5000 Köln 1: 12
Bayerisches Archiv für Sozialgeschichte: 12
KSHA Stadt Hameln: 12
Doppel Meldung Stuttgart: 12
Braunfels: 12
Sondervermögens-u. Baubewaltung: 12
Deutsches Zentrales Stelle: 12
KSHA Schaußburg-Lippe: 12
K816: 12
Landkreis Grafschaft Lippe: 12
KSHA f.d. Reg. Bez. Hildesheim: 12
Sondervermögens-Bauverwaltung: 11
Bayerisches Verfolgten: 11
DOPPELMELDUNG München: 11
Bayerisches Landesamt für Verfolgtenaufwandsentschädigung: 11
Haltestelle: 11
Regional Office for Compensation and Administration of Assets, Mainz: 11
Aurich / Ostfriesl.: 11
Aussensenstelle Freiburg: 11
Weimar: 11
Doppelmeidung: 11
KSM: 11
KSHA Brake: 11
We: 11
KSHA Schauburg-Lippe: 11
Landesamt für Vertriebene, Flüchtlinge und Kriegsgeschädigte: 11
Bayerisches Landeszentrale: 11
DOPPELMELDUNG Berlin: 11
Sondervermögens-u. Bäuerwaltung: 11
Bavarian Compensation Office: 11
Landkreis Grafschaft Goya: 11
Wiedergutmachung, Stuttgart: 10
Regionalverwaltungsgericht Koblenz: 10
BZK: 10
K51m: 10
K6: 10
KSHA Minden: 10
KSHA Götttingen: 10
Regionalverwaltungsbehörde für Wien: 10
K818: 10
Doppelmedlung: 10
Bundesarchive: 10
DOPPELMELDUNG Köln: 10
Burgdorf (Hann.): 10
Kreissonderhilfesauschuss: 10
KSHA Hamm: 10
Bayer. Landesarchiv: 10
R8ln: 10
Landesbeauftragte: 10
Aussenstelle Freiburg i.Br.: 10
Schwerin: 10
An Bundeseskartei: 10
KSHA Celle-Land: 10
Ko: 10
BHF - VB3: 10
KSHA Cologne/Land: 10
Wittlage: 10
Bundesverwaltungsamt in Köln: 10
Regierung Hessen: 10
Köln, Riehler Pl. 2: 10
Der hessische Landtag: 10
Kai: 10
Doppelvermeldung: 10
KSHA Bremervörde: 10
Regional Office for Compensation and Administration of Assets, Neustadt a.d. Weinstr.: 10
Landesamt für die Rückstellung: 9
Holzminden: 9
Düsseldorfer Regierungspräsidium: 9
Sen. f. Fin: 9
Bezirksamt: 9
KSHB: 9
Bayerisches Kartei: 9
KSHA Wittlage: 9
61n: 9
Ankunftskartei: 9
Braun: 9
K: 9
Bundes: 9
Aussensestelle Freiburg i.Br.: 9
Wittmund: 9
Regierung Münster: 9
Kreissonderhilfsschutz: 9
Krois Lindau: 9
Heimat: 9
Bayerisches Verfolgtenarchiv: 9
KSHA Nürnberg: 9
Sondervermögens- u. Bauerverwaltung: 9
Doppelmelung München: 9
Bundes-Verw.-Amt: 9
Sachkartei für Bez. Reg.: 9
DM 500: 9
Doppelmedung: 9
KSHA Gelle/Land: 9
Beg: 9
Aussensenstelle Freiburg/Br.: 9
Landesjustizverwaltung: 9
KSHA Hameln-Pyrmont: 9
Regierung München (MfV): 9
Kreisondeserhifsausschuss: 8
Doppelmeldung Kiel: 8
KSHA Linggen: 8
Leipzig: 8
Bayerisches Zentralarchiv: 8
Köln, Riehler Pl. 2, 5000 Köln: 8
Königlich-Preußische: 8
K811: 8
Ministerium des Innern: 8
Bayerisches Landeszentrale für die Opfer des Nationalsozialismus: 8
Bundesarchiv Berlin-Lichterfelde: 8
Doppelmeilung: 8
K81nt: 8
KSHA Köln/Land: 8
Landesheiratstelle: 8
KBl: 8
United Restitution Office, Frankfurt/Main, Grünburgweg 119: 8
KBlm: 8
Aurich I.Ostfriesl.: 8
61: 8
Bauverwaltung: 8
BVA: 8
Landesamt für die Regelung von Vermögensangelegenheiten: 8
K815: 8
Kreisonderhilfsausschub: 8
LG Frankfurt: 8
Bay. Landesarchiv: 8
Haftbeschädigte: 8
Regional Office for Compensation and Administration of Assets, Koblenz: 8
Aurich /Ostfriesland: 8
Noin: 8
Hauptescheide: 8
Völker: 8
Schwabach: 8
Landesbeirksstelle: 8
Kreisaußerhelfsausschub: 8
K31n: 8
KSHA Norden: 8
KSHA Einbeck: 8
A.D.I.V.A. Bureau de Restitution: 8
Öl: 8
Bayerisches Verwaltungsgericht: 8
Regionalverwaltungsgericht München I: 7
An Bundeeskartei: 7
Regionalverwaltungsgericht Trier: 7
Landesbeirat Stuttgart: 7
Südliches Zentralstelle: 7
K61a: 7
81n: 7
Landsgericht München I: 7
KSHA Fallingbostel: 7
Wiener Landesgericht: 7
Ausgl.Amt Bremen: 7
Bayerisches Archiv für Zeitgeschichte: 7
Doppelmeldung Mainz: 7
Regierung Pommern: 7
An der Bundeskartei: 7
Allianz: 7
Bayerisches Landesamt für Jugend und Verwahrlosungsschutz: 7
Bln: 7
KSHA Zellerafeld: 7
BayHauptstelle: 7
Landesamt für die Rückstellung von Opfern des Nationalsozialismus: 7
Kreissozialhilfsschulung: 7
DOPPELMELDUNG Stuttgart: 7
Bezirksamt Koblenz: 7
Paris: 7
Landesamt für die Verfolgten des Nationalsozialismus: 7
Staatsministerium für Innerdeutsche Beziehungen: 7
Leer/Ostfriesl.: 7
KSHC Cuxhaven: 7
Stadtverwaltung: 7
KOM: 7
Landesarchiv Münster: 7
K31: 7
Kreisondertshilfsausschuss: 7
Uel: 7
Doppelvermögensbehörde: 7
KSH Nord: 7
Kreisverwaltung - Amt f. Wiedergutmachung - Höxter/Weser: 7
Doppelmeldeamt: 7
Kreis Linden: 7
Bundeskartell: 7
Doppelvermögens-u. Bauverwaltung: 7
St. H.: 7
United Restitution Office, Frankfurt/M. Grünburgweg 119: 7
Köln, Riehlstr. Pl.2, 5000 Köln.1: 7
Bund: 7
Bundeskarte: 7
Kreisverwaltung Paderborn: 6
Tr. Bayerisches Landesarchiv: 6
KSHC Celle/Land: 6
Landau, Pf.: 6
Karlsruhe Aussenstelle Freiburg i.Br.: 6
KSHA Hammeln-Pyrmont: 6
Bayerisches Archiv: 6
KSHA Darmenber/Elbe: 6
Kreisonderrhilfsausschub: 6
Staatsanwalt Hamburg: 6
Birkenfeld: 6
Hauptzuständige Behörde: 6
Haftbescheinigung: 6
Landsgericht München II: 6
A: 6
Landeszentrale: 6
Hamburg 36, Drehbahn 37IV: 6
Regionalverwaltungsbehörde für Wien und Niederösterreich: 6
KSHa Celle/Land: 6
Staatsanwalt Köln: 6
Kreissonderhilfsschuss: 6
BMF- VB4: 6
Anstalt des Bundes Oldenburg: 6
Schreiber: 6
HHG: 6
K819: 6
Efurt: 6
Landkreis Oschersleben: 6
EfrA: 6
Bayer. Landesamt: 6
Hauptbesoldung: 6
Hund. Verw. Amt: 6
Tr. 11: 6
Sen. f. Fin.: 6
Vergütungsausschuss: 6
Landesrentenbehörde: 6
Kreissonderhilfsschüfe: 6
Bureau de Restitution: 6
Bundesarchiv Koblenz: 6
KSHA Meppe: 6
Sondervermögens- und Baufondsverwaltung: 6
Landesamt für Verbraucherschutz und Lebensmittelsicherheit: 6
HJ: 6
BHF - VB 4: 6
Doppelmeidung München: 6
Ausland: 6
Niedersächsische Ersatzbehörde: 6
KAI: 6
Norden: 6
Hauptbeschwerde: 6
Bundes'kartei: 6
Bundesstelle Köln: 6
K&In: 6
Kreissozialhilfesausschuss: 6
Landesjustizverwaltung München: 6
Sachverständigenstelle für BZK: 6
BayHaupt: 6
Höherer Kommissar der Vereinigten Nationen für Flüchlinge: 6
KSH Hamm: 6
VORGANG an Köln: 6
Rheinland: 6
Regierung: 6
Landesjustizverwaltung, Stuttgart: 6
Nazi Victims Compensation Office: 6
BAfT: 6
Aurich/Ostfriesl.: 6
A.f.W. Rhein. Pfalz: 6
Ravensburger Kartei: 6
OLDB: 6
Emden: 6
KSHA Rottenburg/H.: 5
An Bundes'kartei: 5
KSHA Vehta: 5
Königreich-Preuß Berlin: 5
Landkreis Osierholz: 5
K 8 In: 5
BZA: 5
Bayerisches Verfolgungsgesamt: 5
Doppelmeldung Karlsruhe: 5
Bayerisches Landesamt für Akten und Archivwesen: 5
Higher Commissioner of the Allied Powers for Refugees: 5
Landau Pf.: 5
Bay. Landesamt: 5
An Bundeskammer: 5
Sondervermögens-u. Bautverwaltung: 5
Dr. Müller: 5
Härtefonds: 5
H81m: 5
Tr. Landeszentrale für die Vergütung von Opfern des Nationalsozialismus: 5
Bayer. Landesjustizverwaltung: 5
Bay. Kartei: 5
BFA: 5
Nazi Germany: 5
Aussenstelle Freiburg: 5
Bayerische Landeszentrale: 5
Wolm: 5
Sondervermögens- und Bauerverwaltung: 5
Köln (Brüssel): 5
Sozialgericht Berlin: 5
London: 5
United Restitution Office, Frankfurt am Main, Grünburgweg 119: 5
Faulenstraße 69, 28195 Bremen: 5
ES/A: 5
Ausg. Amt Bremen: 5
Higher Commissioner for Refugees of the United Nations: 5
Bekanntmachung: 5
Regionalverwaltungsbehörde: 5
An Bundeseskartei Hannover: 5
Bundesverwaltungsamt - Abteilung II: 5
Landesbeamtenschaft: 5
Karlsruhe, Außenstelle Freiburg i.Br.: 5
In: 5
Ni/La: 5
Fu.: 5
Magistrat der Stadt Braunschweig: 5
Schreibtisch: 5
Bayerisches L.E.A.: 5
Süddeutsche: 5
Landesamt für Vertriebenenwesen Köln: 5
Landeszentrale - Registrierung: 5
An Bundeskartellamt: 5
Doppelung: 5
Zentralstelle für NS-Opfer: 5
Regionalverwaltungsgericht München: 5
Ga: 5
Doppel Meldung Köln: 5
H8In: 5
H8m: 5
Rinteln: 5
X8In: 5
AfW Mettmann RP Düsseldorf: 5
Wiedergutmachung Mainz: 5
K5: 5
Landesentschädigungsstelle für die Bundesrepublik Deutschland: 5
ö1: 5
R8In: 5
Hauptstaatsarchiv: 5
Kreisaußerhelfsausschuß: 5
Höherer Kommissar der Vereinigten Nationen für Deutschland: 5
KSHA Winsen - Luhe: 5
Köln, Riehler, Pl.2, 5000 Köln 1: 5
BHF-VR4: 5
Landeszentrale für politische Opferfürsorge: 5
Bayerisches Verfolgungsarchiv: 5
Landgericht München: 5
Dannenberg/Elbe: 5
W81n: 5
Regierung Posen: 5
Kreissozialhilfsschule Peine: 5
Doppelvermerkung Berlin: 5
Reg.-Träger Münster: 5
Landkreis Isarloh: 5
K510: 5
Kreisonderhlfasschul: 5
United Restitution Office, Frankfurt/Main: 5
Bayerisches Verfolgungssamt: 5
United Restitution Office, Frankfurt/M, Grünburgweg 119: 5
Südliches Zentralbüro: 5
Deutsches Versicherungsamt: 5
Komm: 5
KdF: 5
Köln, Riehl Pl.2, 5000 Köln 1: 5
K610: 5
Stadtverwaltung Stadthaus: 5
Fu: 5
Kreissozialhilfsschule Braunschweig-Stadt: 5
Karlsruhe Außenstelle Freiburg i.Br.: 4
K51a: 4
Sachbearbeitung BZK Reg.: 4
KO: 4
DOPPELUNG: 4
Kreissozialhilfsschule Osnabrück-Stadt: 4
Israel: 4
Regional Office for Compensation and Administration of Seized Assets, Koblenz: 4
Breslau, Gutenbergstr. 18: 4
An Bundesakartei: 4
Aurich, Ostfriesland: 4
Neuried: 4
Wolffenbüttel: 4
Bayerisches Landesamt für staatsbürgerliche Angelegenheiten: 4
An Bundeskärtei: 4
BMF/IVB4: 4
Haupt: 4
Bekirksamt: 4
Bayerisches Versäumnisamt: 4
KSHA Nienburg/Weser: 4
KSHA d. Reg. Bez. Hildesheim: 4
Altenkirchen Westerwald: 4
Regional Office for Compensation and Administration of Assets: 4
Bayerische Landesstelle: 4
KSHA Rinteln: 4
Güteverfahren: 4
DSHF: 4
Doppelmeilung Berlin: 4
Kd: 4
Bundeszentralstelle für Opfer des Nationalsozialismus: 4
Miltam Israel Office: 4
Honer Kommissar der Vereinten Nationen für Flüchtlinge: 4
Landesverwaltungsamt Bayern: 4
BHT-VB3: 4
Hauptverwaltungsamt: 4
Bayerisches Verfolgtenmuseum: 4
Deutschland: 4
Doppelmeldung nicht erforderlich, Akte wurde von Bayern überstellt.: 4
Rhd.-Pfalz: 4
Senatsentscheid: 4
Nienburg/Weser: 4
Hohner Kommissar der Vereinten Nationen für Flüchtlinge: 4
Deutscher: 4
Südwest: 4
Claims Conference: 4
Wattenscheid-Salzgitter: 4
Kreisonderschutz: 4
Altenkirchen, Westerw.: 4
Kreissozialamt Landkreis Grafschaft Goya: 4
KreisaußerordentlicherHilfsausschuss: 4
Niedersachsen-Präsident / Landesarchiv Hannover: 4
Bundeszentrale für die Opfer des Nationalsozialismus: 4
Tr. Landesarchiv München: 4
K618: 4
Bund. Verw. Amt: 4
Kreis Linz: 4
Köln, Riehler Pl. 2, 5000 Köln 41: 4
Lindau: 4
Kann: 4
Kreissozialhilfsschule Goslar-Stadt: 4
Regierung Hessen (Wf.): 4
Tr. Samt: 4
Niedersachsen-Präsident / Reg.-Präsident: 4
Landeszentrale für die Vergütung nationalsozialistischer Opfer: 4
Doppelmeierung: 4
Kreissozialhilfsschulze: 4
Vorgang an Koblenz: 4
Schw. Landesamt: 4
Landsmannschaft der Verfolgten des Nationalsozialismus: 4
Efrat: 4
Anstalt des Bundes für die Verwaltung von Vermögensverzeichnissen: 4
unbekannt: 4
KSHA Solttau: 4
Hauptbeschädigte: 4
Bayerisches Landesamt für Vertriebene und Flüchtlinge: 4
Ausgl.AmtBremen: 4
Finanzamt: 4
Kreissozialamt Landkreis Grafschaft Lippe: 4
Der Niedersächsische Minister des Innern Hannover: 4
Kreisonderhlfasschuf: 4
Kreissozialamt Landkreis Grafschaft Hoya: 4
Landesbeauftragte für die Opfer des Nationalsozialismus: 4
Kurzstelle: 4
Kreis Nordhorn: 4
Kreisonderholfasschuf: 4
Staatsanwaltschaft Hamm: 4
Köln, Riehler Pl.2, 5000 Köln 4: 4
Krois Linder: 4
Reichsverwaltungsamt: 4
Hdn: 4
Kreissozialamt des Landkreises Göttingen: 4
Bayerisches Staatsarchiv: 4
Karlruhe Aussenstelle Freiburg i.Br.: 4
München 2, Arcistraße 11: 4
H8ln: 4
LVA Dörf: 4
Sondervermögens-u. Beauftragung: 4
H8lm: 4
BMT: 4
Landesentschädigungsbehörde für die Bundesrepublik Deutschland: 4
BMF-VT4: 4
Einst. Behörde Köln: 4
Neuendettelsau: 4
Doppelmaßung: 4
Baden-Württemberg: 4
K6lm: 4
K8 In: 4
Deutsches Zentrum für die Opfer des Nationalsozialismus: 4
RA. United Restitution Office, Frankfurt/Main: 4
An Bundesländer: 4
Sudkartei für Bez. Reg.: 4
Feststellungsbescheid in Stuttgart: 4
BPA: 4
BVAmt: 4
United Restitution Office, Frankfurt am Main, Gruneburgweg 119: 4
Regierung Hamburg: 4
Auschwitz: 4
Dudorf: 4
Tr. des Verfolgten: 4
Bundesamt Köln: 3
BZA. Zeigledorf: 3
Zentral-Registratur: 3
Doppelmeldung Bremen: 3
KSHA Hild. Marienb.: 3
EK: 3
Karlruhe, Außenstelle Freiburg i.Br.: 3
Bezirksamt von Trier: 3
Landeszentrale für politische Opferhilfe München: 3
KSHA Landkreis Lüneburg: 3
Kreissozialhilfsschule Gifhorn: 3
Frankfurt/M: 3
Höherer Kommissar der Verwaltung für Flüchtlinge: 3
Tr. Landeszentrale für die Vergütung der Opfer des Nationalsozialismus: 3
BMFT: 3
Jörg: 3
Kreisondeserhifsausschub: 3
BayHJ: 3
K&I: 3
Aussenstelle Freiburg/Br.: 3
Bezirksamt München: 3
An Bunde: 3
KZ: 3
KSHA Wolfsenbittel: 3
Haftbefehl: 3
Doppelvermögens: 3
Köln, Riehlener Pl. 2, 5000 Köln 1: 3
Kreis-Sonderhilfsausschub: 3
Wiedergutmachung Karlsruhe: 3
Rundesammlung der Finanz: 3
Nord: 3
Doppelverteilung: 3
Härtedefonds: 3
HAn: 3
Bayer. Kartei: 3
Landesamt für Verfolgungsgeschädigte: 3
Aussensestelle Freiburg: 3
Der Bundesbeauftragte für die Vermögensverwaltung: 3
LG Bochum: 3
RA. United Restitution Office, Frankfurt/M.: 3
K 81 n: 3
Landesamt für Vertriebene in Köln: 3
Wehrmachtbericht: 3
Kreisonderrhfsausschuss: 3
3HF: 3
Landesarchiv Baden-Württemberg, Stuttgart: 3
Kreissozialamt Blankenburg (Brit. Zone) Braunschweig: 3
Büro: 3
Trägerschaft: 3
KSHA Hamein-Pyrmont: 3
Shanghai-Gruppe: 3
DME: 3

In [203]:
print(f"Max MatchDistance: {lev_matches['MatchDistance'].max()}")

Max MatchDistance: 58.0

In [205]:
total = len(lev_matches)-len(df_matches_impossible)
max_dist = int(lev_matches['MatchDistance'].max()) + 1
for i in range(1, max_dist):
    count = (lev_matches['MatchDistance'] == i).sum()
    pct = count / total * 100    
    print(f'MatchDistance = {i}: {count} ({pct:.2f}%)')

MatchDistance = 1: 17610 (12.09%)
MatchDistance = 2: 10216 (7.01%)
MatchDistance = 3: 9283 (6.37%)
MatchDistance = 4: 7249 (4.98%)
MatchDistance = 5: 25033 (17.18%)
MatchDistance = 6: 7157 (4.91%)
MatchDistance = 7: 5696 (3.91%)
MatchDistance = 8: 23344 (16.03%)
MatchDistance = 9: 5215 (3.58%)
MatchDistance = 10: 3719 (2.55%)
MatchDistance = 11: 5334 (3.66%)
MatchDistance = 12: 2539 (1.74%)
MatchDistance = 13: 3634 (2.49%)
MatchDistance = 14: 3022 (2.07%)
MatchDistance = 15: 2023 (1.39%)
MatchDistance = 16: 2193 (1.51%)
MatchDistance = 17: 2679 (1.84%)
MatchDistance = 18: 2706 (1.86%)
MatchDistance = 19: 1229 (0.84%)
MatchDistance = 20: 1014 (0.70%)
MatchDistance = 21: 1700 (1.17%)
MatchDistance = 22: 362 (0.25%)
MatchDistance = 23: 375 (0.26%)
MatchDistance = 24: 360 (0.25%)
MatchDistance = 25: 477 (0.33%)
MatchDistance = 26: 168 (0.12%)
MatchDistance = 27: 105 (0.07%)
MatchDistance = 28: 294 (0.20%)
MatchDistance = 29: 202 (0.14%)
MatchDistance = 30: 113 (0.08%)
MatchDistance = 31: 55 (0.04%)
MatchDistance = 32: 170 (0.12%)
MatchDistance = 33: 62 (0.04%)
MatchDistance = 34: 65 (0.04%)
MatchDistance = 35: 61 (0.04%)
MatchDistance = 36: 43 (0.03%)
MatchDistance = 37: 17 (0.01%)
MatchDistance = 38: 12 (0.01%)
MatchDistance = 39: 8 (0.01%)
MatchDistance = 40: 14 (0.01%)
MatchDistance = 41: 13 (0.01%)
MatchDistance = 42: 15 (0.01%)
MatchDistance = 43: 12 (0.01%)
MatchDistance = 44: 3 (0.00%)
MatchDistance = 45: 2 (0.00%)
MatchDistance = 46: 3 (0.00%)
MatchDistance = 47: 2 (0.00%)
MatchDistance = 48: 4 (0.00%)
MatchDistance = 49: 21 (0.01%)
MatchDistance = 50: 11 (0.01%)
MatchDistance = 51: 7 (0.00%)
MatchDistance = 52: 8 (0.01%)
MatchDistance = 53: 6 (0.00%)
MatchDistance = 54: 3 (0.00%)
MatchDistance = 55: 0 (0.00%)
MatchDistance = 56: 0 (0.00%)
MatchDistance = 57: 2 (0.00%)
MatchDistance = 58: 2 (0.00%)

In [209]:
df_nomatches = lev_matches[(lev_matches['MatchDistance'] > 0) | (lev_matches['MatchDistance'].isna())]

df_nomatches.sort_values('MatchDistance', ascending=True).to_excel('compensation_office_nomatches.xlsx', index=False)